### PR TITLE
Add Phuc's image and information to student section

### PR DESCRIPTION
**Pull request by Jerry2001**
My task: https://codein.withgoogle.com/tasks/5741070096793600/?sp-is_beginner=False
My gh page: https://github.com/Jerry2001/gci16.fossasia.org/commit/61e071fbb410454a5d46bd1cdcc57292c9af6f55

### CODE REVIEW

**Comment by codein-dwij** [comment]
Please provide live gh-pages link for easy review! The link you have provided is not correct

**Comment by Jerry2001** [comment]
Is these right? https://github.com/Jerry2001/gci16.fossasia.org/blob/gh-pages/_data/blogs.yml

**Comment by Jerry2001** [comment]
https://github.com/Jerry2001/gci16.fossasia.org/tree/gh-pages/images/students

**Comment by oanarosca** [comment]
Your link is https://jerry2001.github.io/gci16.fossasia.org. It's the link containing your live version of the gh-pages, don't forget to add it to your PRs! Good job, I'll merge this :tada:

**Comment by Jerry2001** [comment]
Forgive me, I'm new to Git. Where can I get that link?

**Comment by codein-dwij** [comment]
It works in this way : 
[user_username].github.io/[repository_name]
In this case:
jerry2001.github.io/gci16.fossasia.org

**Pull request merged**
