### PR TITLE
Resolves #414 and #235. Making Coala to apply patches and Travis CI to push back the changes

### LINKED ISSUE #414: Making coala auto applying patches
We don't want our code to be bad so we have introduced travis CI tests with coala bears to check them and report. However, we have recent findings that tests are irritating new users and are forcing them to leave the arena of FOSSASIA. We can't ignore both, we want good code and happy contributors for our society so I put forward the concept of making coala to auto apply the patches, this is form the coala documentation:

> Often you don’t want to look at trivial results like spacing issues. For that purpose coala includes a special setting called default_actions that allows you to set the action for a bear that shall be automatically applied on run. We have a command line alias --apply-patches to make it easier to use.

@jig08 @hemantjadon @niccokunzmann @Princu7 @fossasia/gci16-maintainers can I add this functionality, this would both improve our code and also lead to more happy contributors :) What are your opinions hall I proceed with it.

### PR DESCRIPTION
**Pull request by abishekvashok**
**Coala has the capability to auto apply patches, it would apply patches and travis will commit it and push it back to our repository. This is the main idea done in the PR**

This PR would help to resolve two issues namely #235 and #414. The first one was to accomplish trailing white space errors and no newline at end of file (EOF) errors, this will be accomplished by coala auto applying the patches and the second one was to initiate what was done in this.

_After this PR we will surely get more and more happy contributors as code quality will be 99% fixed by coala. The rest 1% goes to the errors where it cannot apply patches like the 'id' errors._ 

@hemantjadon @niccokunzmann @Princu7 @jig08 @robbyoconnor please take a look.

**Travis wont make a push on PR's as it would produce an authentication failure
From the docs of Travis CI:**
> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

**This helps us further as the changes by coala would only be pushed after a new PR is merged as Travis CI will only autheticate properly when the PR is merged. This is a really good boon for us as if we give the coala-autofix-bot write access Travis can push without any need for us to manually merge the changes.**

Here is a flowchart of what will be done by travis after this PR:
screenshot from 2016-12-19 16 29 37

and one to explain what is done currently [before this PR]:
screenshot from 2016-12-19 16 30 03

_Sorry for a bad flow chart if you think it's bad :)_

Further I had tested it on another branch of my repository and I was able to accomplish the good results. Here is a preview (Travis works only when PR is merged):
image

Done as part of GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6288634963558400/

Hope you'd review and merge

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Abhi2424shek You may want to use [Travis Enviroment Variables](https://docs.travis-ci.com/user/environment-variables/) for username/password.
Check [Encrypted data in Travis](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) for more info.
Check your PR at https://github.com/Abhi2424shek/gci16.fossasia.org/pull/1

**Comment by abishekvashok** [comment]
@m1guelpf thanks for creating the user and the password, but I could'nt incorporate it as it failed to authenticate properly, I've created a new user account.

**Comment by Abhi2424shek** [comment]
@m1guelpf @fossasia/gci16-maintainers @hemantjadon @Princu7 can you debug this, an authentication failure, I added it to the settings in travis but still authentication failure!
image
can you check.

**Comment by Abhi2424shek** [comment]
I am retrying added a new commit waiting for Travis

**Comment by m1guelpf** [comment]
@Abhi2424shek Ready for merge?

**Comment by abishekvashok** [comment]
@m1guelpf sure but we could wait for more review on my part I am 100% ready.

**Comment by m1guelpf** [comment]
@Abhi2424shek So it's working?

**Comment by abishekvashok** [comment]
@m1guelpf yes working very well. Only Travis will give new PR after a PR is merged is'nt that good ?

**Comment by niccokunzmann** [comment]
@Abhi2424shek should this be merged or are you discussing and testing?

**Comment by abishekvashok** [comment]
@niccokunzmann debugging has been done followed by testing which ran succesfully and produced positive results. If you doubt see the PR body there is an image where it has been tested on my repo and it ran successfully [See the Travis commit in the image].

It is ready to be merged sir.

**Comment by abishekvashok** [comment]
@niccokunzmann you'd need to give "coala-autofix-bot" write access. That would prevent us the need to merge the PRs pushed by travis.

**Comment by niccokunzmann** [comment]
I invited the bot: https://github.com/fossasia/gci16.fossasia.org/invitations

**Comment by abishekvashok** [comment]
@niccokunzmann let me switch over and accept it!
Accepted it now Travis will start doing the job from the moment the next PR is merged! :)

**Comment by abishekvashok** [comment]
@niccokunzmann I thought that I could ping you for reviewing my GCI task:
https://codein.withgoogle.com/dashboard/task-instances/6288634963558400/

**Comment by m1guelpf** [comment]
@Abhi2424shek Not working:
```
The command "git remote add orgin-pages https://coala-autofix-bot:$COALA_FIXER@github.com/fossasia/gci16.fossasia.org.git" exited with 0.
0.35s$ git push --quiet --set-upstream orgin-pages coala-fix
remote: Invalid username or password.
fatal: Authentication failed for 'https://coala-autofix-bot:@github.com/fossasia/gci16.fossasia.org.git/'
```

**Comment by robbyoconnor** [comment]
@niccokunzmann -- ...why was this merged? -- it broke travis (the image checker path and filename changed) 

There should have been a very obvious merge conflict...I had the travis build green. This broke it.

**Comment by robbyoconnor** [comment]
FYI: I fixed the probelems in 3025ed14d6eb6206027d90c149b5990c1902e5c4 and 629fe047f6beae42a7141037e7b3b95a1a769398 

- The first, the path to the image checker is `./scripts/image_checker.rb`
- The second, you need to rebase before you push to a remote branch, otherwise it will fail when you try to push (for obvious reasons), this, I added that in. The build is now green!

**Comment by robbyoconnor** [comment]
FYI: I fixed the probelems in 3025ed14d6eb6206027d90c149b5990c1902e5c4 and 629fe047f6beae42a7141037e7b3b95a1a769398 

- The first, the path to the image checker is `./scripts/image_checker.rb`
- The second, you need to rebase before you push to a remote branch, otherwise it will fail when you try to push (for obvious reasons), this, I added that in. The build is now green! 

@Abhi2424shek when you resolve merge conflicts -- always take the upstream changes unless you did something that updated that line of code. In your case, you didn't have the updated image checker path.

**Comment by abishekvashok** [comment]
@robbyoconnor thatnks sorry for that, happy to see the coala auto applying patches!

**Comment by robbyoconnor** [comment]
@Abhi2424shek, it didn't -- i cherry-picked the fix into the gh-pages branch from the coala-fix branch. It did however commit the fixes.

**Pull request merged**
