### PR TITLE
Fixed footer

### PR DESCRIPTION
**Pull request by oanarosca**
Solves issue #663, see the changes [here](https://oanarosca.github.io/gci16.fossasia.org/).

### CODE REVIEW

**Comment by ankitrgadiya** [comment]
@oanarosca Can't we use Font Awesome as they are know, its lighter then pictures surely!

**Comment by oanarosca** [comment]
@ankitrgadiya I considered this when I first created the footer, but I found these icon images to be better-looking, plus they are only 48x48, so I don't think that does create a great problem. I can easily change them, no a problem, let's see other opinions as well :blush:

**Comment by Elgayar** [comment]
@oanarosca Using images is not preferable in such matter, instead it is much more recommended to use icons such as FontAwesome or Glyphicons by Bootstrap.

**Comment by robbyoconnor** [comment]
@oanarosca, you do realize that font-awesome icons can be any color you want and can even be bold/italicized/underline

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
Don't use images. Use FontAwesome or Glyphicons. 

I'm with @Elgayar here.

**Comment by oanarosca** [comment]
Okay! I'll fix it just now.

**Comment by abishekvashok** [comment]
@oanarosca you could have made a work around here, anyways keep up the good work

**Pull request closed without merging**
