### PR TITLE
Fixed students section

### PR DESCRIPTION
**Pull request by abishekvashok**
Resolved a huge bug of the site, now the student section is back ok

### CODE REVIEW

**Comment by abishekvashok** [comment]
@hemantjude @jig08 @daminisatya please review and merge quickly, the bug is so huge on the site!

**Comment by hemantjadon** [comment]
@Abhi2424shek Squashing please :)

**Comment by abishekvashok** [comment]
@hemantjadon squashing

**Comment by abishekvashok** [comment]
@hemantjadon squashed now please merge on. Here are the previews: https://abhi2424shek.github.io/gci16.fossasia.org/

**Comment by hemantjadon** [comment]
Nice and consistent design.
Good work @Abhi2424shek 
Is it associated with any task ??

**Comment by abishekvashok** [comment]
No please merge it @hemantjadon

**Pull request merged**
