### PR TITLE
Add image slider

### PR DESCRIPTION
**Pull request by hoangvanthien**

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@hoangvanthien 

* Could you pls give an appropriate description of the issue being resolved or the feature being added here ?

Also,

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Review by daminisatya — CHANGES_REQUESTED** [review]
Code looks good to me , but as @jig08 mentioned provide us with the task description and link, demoing your changes. Also the merge conflicts (Y)

**Comment by hoangvanthien** [comment]
@jig08 
A few minutes ago, I merged conflicts as my mentor guided and succeeded. However, up here, it is seemingly that conflicts are not resolved. What should I do?

Furthermore, can you guide me how to squash all commits into one?

Thanks.

**Comment by daminisatya** [comment]
@hoangvanthien Yes, if you are using the command prompt here are the steps to go. 

There are two ways in which you can do this.
* While pushing another commit, you can amend to the previous commit. git commit --amend (when you already have a commit existing and you want to amend to it) instead of doing ```git commit -m "message"``` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 5 commits of yours which you want to squash into single, then the command goes ```git rebase -i HEAD~5```. Which leads to an editor where you will be asked for every commit whether you want to pick to squash. type squash for all the 5 commits present and exit. The rebase continues and you have force push the changes, as in git push -f origin <branch>. 

This might be a bit confusing, but please watch this [video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Comment by daminisatya** [comment]
Hope you are clear with resolving merge conflicts and squashing! :)

**Comment by hoangvanthien** [comment]
@daminisatya How to know if conflicts have been resolved, may I ask?

**Comment by daminisatya** [comment]
When you push the changes, github will automatically tell you, grey for conflicts not being resolved. Green for being resolved. 
selection_341

**Comment by hoangvanthien** [comment]
Sorry for spam commit. But more important, I fail check of Travis. What should I do?
https://hoangvanthien.github.io

**Review by daminisatya — APPROVED** [review]
Good to go! I approve from my side, @SaptakS | @jig08 
Can you give a brief review

**Comment by Princu7** [comment]
@hoangvanthien The Travis Build is failing. It happens due to space, line length and similar type of inconsistencies. You can have a look at the reasons for the failed build by looking at the details. Additionally, you can use coala to properly lint the code. Cheers!!

**Comment by hoangvanthien** [comment]
@Princu7 Okay I will have a look at that.
@daminisatya I have seen the video you sent me. I get a bit confused of `git rebase -i HEAD~5`. When she (the video maker) type that command and hit enter, sublime text automatically open, showing content of a text file. But in my side, the content is shown inside terminal and the terminal was like "frozen" there because I cannot do any more action on that. Could you please: guide me how to config like the video-maker (1) and how to work with text file in terminal whenever text is shown inside it (2) ?

**Comment by daminisatya** [comment]
@hoangvanthien Share the screenshot i will guide you through.

**Comment by hoangvanthien** [comment]
@Princu7 
Finally there is no red sign anymore. :) Please consider to merge.
https://hoangvanthien.github.io

**Comment by abishekvashok** [comment]
@hoangvanthein please don't add students statically, see the index.html code

**Comment by hoangvanthien** [comment]
@Abhi2424shek What do you mean? I didn't do anything with the student section.

**Comment by abishekvashok** [comment]
@hoangvanthien see the code I've added line comments

**Comment by hoangvanthien** [comment]
@Abhi2424shek 
Please review.

Now I've got to learn how to squash commit. @daminisatya why when I did as in the video a message was shown saying that there are CONFLICTS? What does this mean? Is my current state conflict with previous state?

**Comment by daminisatya** [comment]
You have a lot of code updates pulled from the main branch in between. It's fully convoluted. I would suggest you to open a pull request! ;)

**Comment by abishekvashok** [comment]
@hoangvanthein I also suggest u start a new PR after creating a new fork

**Comment by hoangvanthien** [comment]
Yeah maybe I've done so many stupid thing that I've had to fix it again and again and again and it is completely different from the first commit of this pull request. So now, I must close and open another PR?

**Comment by daminisatya** [comment]
@hoangvanthien Yes go ahead. But be glad that you had learnt a lot today :) cheers for that

**Comment by abishekvashok** [comment]
We all learn from mistakes bro great that you learned a lot today, happy. Open a new one and show your creativity I believe you can @hoangvanthein

**Pull request closed without merging**
