### PR TITLE
Added Jason Wong's image and details.

### PR DESCRIPTION
**Pull request by phreakyphoenix**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by robbyoconnor** [comment]
please rebase

**Comment by robbyoconnor** [comment]
the easiest way is to delete your fork and refork. closing this one.

**Comment by phreakyphoenix** [comment]
Should I make a new pull request?

**Comment by abishekvashok** [comment]
@TechGuyAditya yep delete your fork and refork please

**Pull request closed without merging**
