### PR TITLE
Added my MBDyn logo design to website

### PR DESCRIPTION
**Pull request by Dodecane**

### CODE REVIEW

**Comment by Dodecane** [comment]
What is wrong?

**Comment by Princu7** [comment]
@LeeCareGene Your patch is not passing the Travis CI build. It means there are some space or line length  issues in it. You can click on the details button given above to get an idea about what causes the build to fail. Correct the mistakes. 
You can also use coala to properly lint the code.

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Please also check for merge conflicts

**Comment by Abhi2424shek** [comment]
@LeeCareGene why did you close this!

**Pull request closed without merging**
