### PR TITLE
Added Victoria Juan to student section

### PR DESCRIPTION
**Pull request by vickyjjj**

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@vickyjjj Thanks.

* Is your image in `images` folder already and data in `students.yml` ?
* Rename your commit to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

Cheers !

**Comment by hemantjadon** [comment]
@vickyjjj 
Please provide Links to gh-pages branch and to task

**Comment by jigyasa-grover** [comment]
@vickyjjj 

> * Is your image in `images` folder already and data in `students.yml` ?

Is it ? Or are you updating `index.html` directly ?

> * Rename your commit to something meaningful, such as "Adding <-your-name-> in students/mentors section"

I meant renaming the commit and not the PR itself :)
Check this out [Github: Rewriting the most recent commit message](https://help.github.com/articles/changing-a-commit-message/)

> * Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

Example: vickyjjj.github.io/gci16.fossasia.org or relevant screenshots showing the change.

Thanks !

**Review by daminisatya — CHANGES_REQUESTED** [review]
conflicts and update mentor's comments!

**Comment by vickyjjj** [comment]
Sorry, I had gone to sleep earlier without finishing your instructions. I had already added my image and information in students.yml in an earlier pull request but forgot to do this part of editing the index.html, so it's in a separate pull request. 

I just changed the commit title, thank you for the informative link!

Attached is a screenshot of the change, with my profile in the third row.

**Comment by vickyjjj** [comment]
I also need help finding the conflicts mentioned.

**Comment by hemantjadon** [comment]
Resolve the merge conflicts please. Refer to the slack channel there are many Pinned Messages there which can help you to solve the merge conflicts.
Cheers :)

**Comment by vickyjjj** [comment]
I fixed the merge conflict (or at least, I just learned how to). Let me know if it works out.

**Comment by jigyasa-grover** [comment]
@vickyjjj Yes, you fixed the merge conflicts successfully !
@hemantjadon Pls can you look into the TravisCI failure ?

**Comment by abishekvashok** [comment]
@jig08 the travis tests failed because HTMLLintBear doesn't want tabs at lines 261 and 277
`HTMLLintBear: Indentation: Do not use tabs: Remove the tabs.`

**Comment by hemantjadon** [comment]
Hey @vickyjjj ,
@Abhi2424shek  correctly specified that there are Tabs used instead of spaces in some places in your index.html. You will need to fix them.

This is the build log of your latest commit 
https://travis-ci.org/fossasia/gci16.fossasia.org/builds/180912848
(Oh btw you can view the build log any time by clicking on "Details" of checks failed; See Below)

You should try to use coala to fix up all the errors. Here is something which will help.
https://asciinema.org/a/42968

Cheers :)

**Comment by vickyjjj** [comment]
Alright, I just tried to fix those spacing issues, sorry about that. I also resolved the merge conflicts that have arisen since last time.

**Comment by vickyjjj** [comment]
OK, wait, I'll try to fix the rest.

**Comment by vickyjjj** [comment]
Ok, I think I updated everything to match with all the changes that are happening in the main repo....

**Comment by hoangvanthien** [comment]
@vickyjjj Please review. You need not to write in the file index.html. Everything now is generated from students.yml file. The structure is broken. http://gci16.fossasia.org/

**Comment by vickyjjj** [comment]
I only edited the index.html file a few days ago because that was how people were adding themselves in, then this pull request got dragged on so then I had to pull from the main repo's index.html and delete the things I had added. 

Lee Care Gene's info/picture and Adarsh's picture are being repeated because they're stuck in the for loop. I'm not sure how their code got in, and I apologize. I'll put in a new pull request.

**Comment by hemantjadon** [comment]
@vickyjjj Do you need any help out here? Please ask without hesitation.

Cheers :)

**Comment by vickyjjj** [comment]
Well, I created pull request #150 if you want to check on it. Thanks!

**Pull request merged**
