### PR TITLE
Update blogs.yml

### PR DESCRIPTION
**Pull request by Denisa03**

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Denisa03 Please remove all your extra spaces

**Comment by m1guelpf** [comment]
@Denisa03 Please squash your commits

**Comment by niccokunzmann** [comment]
Can you add your entries to a random position in the file? May be you want to update this pull-request or open a new one. Several other people want to do the same task and if all add it to the end, several-1 people fail and need to do again. You can also talk to them, and collaborate.

**Comment by jigyasa-grover** [comment]
Copy here https://github.com/fossasia/gci16.fossasia.org/pull/396, closing this.

**Pull request closed without merging**
