### PR TITLE
changed my image.

### PR DESCRIPTION
**Pull request by itsguneetsingh**
hope this is fine

### CODE REVIEW

**Comment by itsguneetsingh** [comment]
First of all I need myself to be clear with what a "live link" and "PR body" means can anyone tell me about it

**Comment by animeshsinghweb** [comment]
@Guneetconvent2002 PR means Pull Request and Live link, where your Github page is live. In your case the live link is: https://guneetconvent2002.github.io/gci16.fossasia.org/ Please remember this URL.

**Comment by itsguneetsingh** [comment]
OK, so can just provide my live link here or I need to do it again

**Comment by animeshsinghweb** [comment]
@Guneetconvent2002 I had already merged the Pull Request.
But the next time do remember to mention the live link I provided.

**Comment by itsguneetsingh** [comment]
ok thanks for your help, bye

**Pull request merged**
