### PR TITLE
Added note for maintainers

### PR DESCRIPTION
**Pull request by ankitrgadiya**
Even though I'm not a maintainer, I feel like this should be done by maintainers so I added it.

### CODE REVIEW

**Comment by tradzik** [comment]
Nice, thank you. Remember some issues are closed automatically when PR is merged, though.

**Comment by ankitrgadiya** [comment]
@tradzik Do they close automatically? I didn't know that, most issues I follow are closed by some maintainers. Also I would like to add there exist a lot of issues which are reported more then once, Please maintainers check them, I've added comment in most of them.

**Comment by hoangvanthien** [comment]
@ankitrgadiya The issue will be automatically closed if one writes a keyword in the commit message or PR. https://github.com/blog/1506-closing-issues-via-pull-requests. :)

**Comment by ankitrgadiya** [comment]
@hoangvanthien Okay so should I update the contributor.md then?

**Comment by abishekvashok** [comment]
@ankitrgadiya only ones with push access can directly close it in the way @hoangvanthien mentioned.

**Review by hoangvanthien — APPROVED** [review]

**Review by robbyoconnor — COMMENTED** [review]
FYI this can be done via the commit message by typing "Fixes #xx"

**Pull request merged**
