### PR TITLE
Adding Chien to students section

### PR DESCRIPTION
**Pull request by wermarter**

### CODE REVIEW

**Review by jigyasa-grover — COMMENTED** [review]
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

Cheers !

**Comment by niccokunzmann** [comment]
@Wermarter Thanks for your contribution. It helps us keeping the overview if we know that there are duplicate pull-requests. You can reference them like this: #94

**Comment by niccokunzmann** [comment]
If you need a squashing tutorial, you can look into the contributing.md file.

**Comment by niccokunzmann** [comment]
Let me us know if you need help.

**Review by daminisatya — DISMISSED** [review]
Good to see a pull request from you, but let us make this process more interesting. As mentors @jig08 @niccokunzmann Mentioned, Please squash the commits.

**Comment by wermarter** [comment]
@daminisatya Squashing the commits you mean this [https://github.com/fossasia/gci16.fossasia.org/pull/234/commits/334ff858df27a1e934c5d074f9b871b428268b0a](url) or all the commits?

**Comment by abishekvashok** [comment]
All commits

**Comment by wermarter** [comment]
@Abhi2424shek Including the merging?

**Comment by abishekvashok** [comment]
@Wermarter that would be an empty commit right, lets see if the mentors could squash and merge

**Comment by jigyasa-grover** [comment]
@Wermarter Thanks for your persistence !

**Comment by niccokunzmann** [comment]
@Wermarter Can you provide a link to the task, so we can approve?

**Comment by wermarter** [comment]
@niccokunzmann 
https://codein.withgoogle.com/dashboard/task-instances/6286829517012992/

**Comment by niccokunzmann** [comment]
@Wermarter Thanks! The additional commits you pushed - if they should be merged - please put in another pull-request.

**Pull request merged**
