### PR TITLE
Feature1

### PR DESCRIPTION
**Pull request by AlexTurning**
Added credential and photo-Sa

### CODE REVIEW

**Review by daminisatya — CHANGES_REQUESTED** [review]
Always pull the latest updates, before creating a pull request to avoid merge conflicts.

**Comment by AlexTurning** [comment]
I did try to pull but it says   unable to access 'https://github.com/AlexTurning/gci16.fossasia.org.git/': Couldn't resolve host 'github.com'

**Comment by daminisatya** [comment]
screenshot?

**Comment by AlexTurning** [comment]
screenshot 34

**Comment by daminisatya** [comment]
type the following command and send me the screenshot (u can also use snipping tool) 
* vim .git/config

**Comment by AlexTurning** [comment]
capture

**Comment by daminisatya** [comment]
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/AlexTurning/gci16.fossasia.org.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
        url = https://github.com/fossasia/gci16.fossasia.org.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "gh-pages"]
        remote = origin
        merge = refs/heads/gh-pages

```

Paste this in that file(page)
And type this command to update the current branch. 

```git pull upstream gh-pages```

**Comment by AlexTurning** [comment]
sorry but nothing happened after i typed that command

or maybe i should try making another pull request from beginning?

**Comment by hemantjadon** [comment]
@AlexTurning New pull request will not solve the issue.
Is the issue same as previous ?

**Comment by jigyasa-grover** [comment]
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
