### PR TITLE
Made students section dynamic and added Abishek V Ashok to stuent's section

### LINKED ISSUE #119: Student section is currently static, make it dynammic
The student section of the website is currently static and nothing in the students.yml shows up. Let's make it dynamic, so students need just to insert there info to the students.yml file.

### PR DESCRIPTION
**Pull request by abishekvashok**
Made students section dynamic and added Abishek V Ashok to stuent's section, resolves #119.
Here are the previews: https://abhi2424shek.github.io/gci16.fossasia.org/
Here are the screenshots of the preview:

image
image

Now the students just need to update students.yml and place their pics in images/students folder and no need of static changing on index.html page

@jig08 @Princu7 @daminisatya @hemantjadon please review and merge... :) Happy coding
Thanks

### CODE REVIEW

**Review by shubham-padia — APPROVED** [review]

**Comment by abishekvashok** [comment]
@shubham-padia please merge it. Here's the link to task: https://codein.withgoogle.com/dashboard/task-instances/5169781940420608/

**Comment by hemantjadon** [comment]
Nice Persistance @Abhi2424shek :)

Keep it up  👍 

Just try to be a little patient from next time.

Cheers :)

**Comment by abishekvashok** [comment]
@hemantjadon please accept my task

**Comment by abishekvashok** [comment]
Sure I will be @hemantjadon Thanks 😂 😃

**Pull request merged**
