### PR TITLE
Google Code-In

### PR DESCRIPTION
**Pull request by ykumar21**
Added student information and image

### CODE REVIEW

**Comment by codethejason** [comment]
Please fix your GitHub credentials in Git to make sure your username and email match those on GitHub. Also, please squash your commits into one commit.

**Review by SaptakS — CHANGES_REQUESTED** [review]
Please remove the Thumbs.db as that is not required to this project. Thanks.

**Comment by abishekvashok** [comment]
Hey just insert the changes to students.yml

**Review by jigyasa-grover — COMMENTED** [review]
@Tandoori-Momos 


* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Review by jigyasa-grover — COMMENTED** [review]
Remove `Thumbs.db`

**Comment by jig08** [comment]
Wrt https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md, closing this.

**Comment by jigyasa-grover** [comment]
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
