### PR TITLE
Added wacing octocat and removed commented JavaScript Code

### PR DESCRIPTION
**Pull request by Elgayar**
Solving the issue #605
Added a nice looking waving octocat that is fixed on the corner, and removed the previously added ribbon that only existed on the slider and wasn't good looking.

I as well removed some JavaScript code that was commented by me in a previous task!

### CODE REVIEW

**Comment by Elgayar** [comment]
Live Link: https://elgayar.github.io/gci16.fossasia.org/

**Comment by Elgayar** [comment]
Screenshot: 
image

**Comment by abishekvashok** [comment]
Nice job next time you modify the index add this:

`<!-- Safe Edit -->`

**Comment by Elgayar** [comment]
Yeah I know, I did. :) @Abhi2424shek

**Comment by Elgayar** [comment]
`<!-- Safe edit -->`

**Comment by abishekvashok** [comment]
Add safe edit as a comment that's what I meant

**Comment by abishekvashok** [comment]
K let's restart the build then shall I open and close i am on mobile

**Comment by abishekvashok** [comment]
Nah restarted let's wait for Travis

**Comment by Elgayar** [comment]
I restarted

**Comment by Elgayar** [comment]
The travis build still fails.

**Comment by abishekvashok** [comment]
@Elgayar it's of danger, lets restart again,

**Comment by abishekvashok** [comment]
@Elgayar now Travis is ok! :)

**Comment by Elgayar** [comment]
Thank youy

**Comment by abishekvashok** [comment]
@Elgayar welcomee

**Comment by Elgayar** [comment]
It seems like the waving octocat isn't being friendly when the website is opened from mobile.

I will fix it as soon as I wake up in an hour.

**Comment by abishekvashok** [comment]
@Elgayar sure

**Comment by Elgayar** [comment]
Okay turns out that adding the waving octocat isn't the source of the mobile view bug.
This will be a new issue, away from that PR.

**Pull request merged**
