### PR TITLE
Added coala markdown linting

### PR DESCRIPTION
**Pull request by idealadarsh**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added coala markdown linting.
- Live link: https://adarsh-ideal.github.io/gci16.fossasia.org
- Fixes: https://github.com/fossasia/gci16.fossasia.org/issues/817

### CODE REVIEW

**Comment by jayvdb** [comment]
Well that was badly done.
It was auto-patched https://github.com/fossasia/gci16.fossasia.org/commit/39c4abcf4a66 , and tools make mistakes like we can see on https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md .  This is why humans are still useful.

**Comment by robbyoconnor** [comment]
Should we remove the auto-patcher @jayvdb ?

**Comment by jayvdb** [comment]
@robbyoconnor , I see you had to [fix it](https://github.com/fossasia/gci16.fossasia.org/commit/e3808de49f) ;-(  I tip my hat to your dedication to keeping this repo afloat for the GCI program.

**Comment by robbyoconnor** [comment]
@jayvdb Perk of being unemployed -- I'm bored soo...

**Comment by robbyoconnor** [comment]
Will continue discussion in #828

**Pull request merged**
