### PR TITLE
Few fixes

### PR DESCRIPTION
**Pull request by ankitrgadiya**
- Fixed image in Design v2 section
Original
screenshot from 2016-12-24 16-46-07
Changed
screenshot from 2016-12-24 16-46-42
- Design v2 Cards fixed to match Design v1 section
Original
screenshot from 2016-12-24 16-47-45
Changed
screenshot from 2016-12-24 16-48-10
- Fixed margins between few sections to make it consistent throughout the site.
Original
screenshot from 2016-12-24 16-49-55
Changed
screenshot from 2016-12-24 16-50-53

[Live Link](https://ankitrgadiya.github.io/gci16.fossasia.org/)

```
<!-- Safe Edit -->
```

### CODE REVIEW

**Comment by niccokunzmann** [comment]
These are several changes, you make. Could you create one PR for each change? Eventually one will get merged. I do not want to merge it now, because 

1. The top menu does not scroll to the section (name changed)
2. The comment stated that there shall be no height specified, which you removed and specified - which makes it more for a discussion. Can you add the one who created like line with the comment to your pull-request(s) to ask this person's input?

**Comment by ankitrgadiya** [comment]
@niccokunzmann 
- Fixed top menu scroll to section problem.

About 2<sup>nd</sup> I did it to make the section consistent with design section v1.

**Comment by abishekvashok** [comment]
@ankitrgadiya nice work.

**Comment by abishekvashok** [comment]
@ankitrgadiya I would restart the build for you now...
=> Restarted!

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Thanks.
@niccokunzmann How can I find the one who added comment?

**Comment by abishekvashok** [comment]
@ankitrgadiya use git blame but besure not to blame him ;)

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Oh boy, git blame is so awesome.

**Comment by abishekvashok** [comment]
@ankitrgadiya yes it is! Hope you got the needed help!

**Comment by ankitrgadiya** [comment]
@niccokunzmann: @louisgag added the comment.

**Comment by ankitrgadiya** [comment]
@niccokunzmann I'll create separate PRs. Closing this one.

**Comment by louisgag** [comment]
Hi guys, I've made the logov2 section purposely different from the v1 to have the proper aspect ratio and avoid the white bar that shows above the images because of the hover script.. It seems someone keeps changing it back to v1 style...

**Pull request closed without merging**
