### PR TITLE
Added info and picture for GCI task

### PR DESCRIPTION
**Pull request by jmurzaku**
Added info and picture in order to complete this GCI task: https://codein.withgoogle.com/dashboard/task-instances/5684472433344512/

### CODE REVIEW

**Review by daminisatya — APPROVED** [review]
Great! :)

**Comment by hemantjadon** [comment]
Please resolve the merge conflicts.

**Comment by jig08** [comment]
@JamMurz Nice :)

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Review by jigyasa-grover — COMMENTED** [review]
@JamMurz Nice :)

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Pull request closed without merging**
