### PR TITLE
Improved Socal Media part

### PR DESCRIPTION
**Pull request by rhemon**
Have a look at here too see the changes : https://rhemon.github.io/gci16.fossasia.org/

I simply made the first two row’s items equal size
and made the youtube one entered

### CODE REVIEW

**Comment by PolBaladas** [comment]
Okay!

**Comment by PolBaladas** [comment]
Do you think you could make the youtube frame bigger?

**Comment by rhemon** [comment]
can you suggest me the width and height? i gave that because it fitd in mobile aswell. I think i will fix it with media queries

**Comment by abishekvashok** [comment]
Ok @rhemon go for media queries and give out a commit.

**Comment by abishekvashok** [comment]
The Travis checks failed because of pine length issue no line should be larger than 100 words, that includes spaces also, check the lines from 250

**Comment by rhemon** [comment]
i am sorry @Abhi2424shek , could explain me the error and suggest how to fix

**Comment by abishekvashok** [comment]
It's line length issue, in lines 254, 257, 264, 266 and 270, the letter per line goes more than 100 which is not a good convention. Hence, you get these errors

**Comment by PolBaladas** [comment]
@rhemon As @Abhi2424shek says, it's a matter of code conventions, "style" if you wanna call it that way. When you are collaborating in open source projects it is very important to keep this ideas in mind.

**Comment by rhemon** [comment]
ok thanks, will try fixing it

**Comment by rhemon** [comment]
@Abhi2424shek @PolBaladas @hemantjadon Please have a look at it now https://rhemon.github.io/gci16.fossasia.org/

**Comment by rhemon** [comment]
rather than using media queries i went to with bootstrap's responsive embed class

**Comment by rhemon** [comment]
that way I dont have to do the nifty work

**Comment by rhemon** [comment]
noo not again

**Comment by hemantjadon** [comment]
@rhemon Please check for failing build.

Also there is huge gap between youtube and flickr please check it.

**Comment by rhemon** [comment]
yeah just realised, on it

**Comment by rhemon** [comment]
why the hell is this showing errors of that I didn't even touch

**Comment by rhemon** [comment]
Tired, gonna work on this later. Although I would love if someone told me what do I need to do? Like in some places its just the link, now how do I make that less then 100, and why hasn't it shown it before?
Sorry but I am getting tired so after getting some rest I will work on it again

**Pull request closed without merging**
