### PR TITLE
Fixed UI and UX of SocialMedia section and gave it a new design

### PR DESCRIPTION
**Pull request by animeshsinghweb**
The social media grids systems, design and UX has been updated.

**Earlier it was like this: **
Earlier

**After my modifications**
After Modification of Social Media Section

[My Live link](https://animeshsinghweb.github.io/gci16.fossasia.org/)

### CODE REVIEW

**Comment by abishekvashok** [comment]
@animeshsinghweb can I have the preview tested in smaller screen sizes please.

**Comment by animeshsinghweb** [comment]
@Abhi2424shek Check the live link in the small browser window. 👍

**Comment by abishekvashok** [comment]
@animeshsinghweb I am on a tablet no developer options here bro, I would test it on my PC wait....

**Comment by abishekvashok** [comment]
It's flowing out:
image

And on PC:
image

**Comment by animeshsinghweb** [comment]
In Mobile Viewport

**Comment by m1guelpf** [comment]
@animeshsinghweb LGTM

**Pull request merged**
