### PR TITLE
Added image and credentials

### PR DESCRIPTION
**Pull request by BohJieQi**

### CODE REVIEW

**Comment by hemantjadon** [comment]
@BobJoeTom 
The task specifies you to add your own profile image. Please do that :)

**Review by hemantjadon — CHANGES_REQUESTED** [review]
@BobJoeTom
The task specifies you to add your own profile image. Please do that :)

**Comment by BohJieQi** [comment]
Sorry, is my github picture okay?

**Comment by hemantjadon** [comment]
Please add "your" pic as it will be much more elegant on the website.

Also according to the task you must add your information in the student section of the website.
So please do these two things so we can proceed.

**Comment by BohJieQi** [comment]
I have added my picture, and my information is inside the students.yml file.

**Comment by hemantjadon** [comment]
This seems okay to me.

But according to task you have to add your image to the student section of the website.
Please do this so we can move ahead.

**Comment by hemantjadon** [comment]
Check for merge conflicts and please provide link to gh-pages of your merge.

**Comment by BohJieQi** [comment]
I have displayed my image and fixed the merge conflicts, sorry for the inconvenience!

**Comment by BohJieQi** [comment]
Link to gh-pages: https://bohjieqi.github.io/gci16.fossasia.org/

**Comment by hemantjadon** [comment]
Your image seems to be out of place with respect to others. Please ensure that the size is same.
Rest of the things are okay with me.
Please do provide the task link and link to your gh-pages.

**Comment by BohJieQi** [comment]
I have edited the picture to a 1:1 ratio
Link to gh-pages: https://bohjieqi.github.io/gci16.fossasia.org/

**Comment by hemantjadon** [comment]
It's better but check that why the 4th image is going into last column of second row.

**Comment by hemantjadon** [comment]
Nice Dedication @BohJieQi Keep It up :)

Just solve the merge conflicts and we are good to go :)

Also please add your task url.

**Comment by BohJieQi** [comment]
Sorry for the late response, the irregular arrangement is due to the lack of another div with a row class once the 3 spaces in each row are filled up.
I resolved the merge conflict and the grid issue

Github pages URL: https://bohjieqi.github.io/gci16.fossasia.org/
Task URL: https://codein.withgoogle.com/dashboard/task-instances/5878378523525120/

**Review by hemantjadon — APPROVED** [review]

**Comment by hemantjadon** [comment]
Good work @BohJieQi 
This seems perfect.

Keep It up :) 

In future please read the task description thoroughly before submitting. It will be good for you and us both :) 

Cheers :)

**Pull request merged**
