### PR TITLE
GCI

### PR DESCRIPTION
**Pull request by ishan710**

### CODE REVIEW

**Review by ishan710 — COMMENTED** [review]
Added my details for the website

**Review by ishan710 — COMMENTED** [review]
Adde image

**Comment by ishan710** [comment]
ishan710

**Comment by Elgayar** [comment]
@ishan710 Can you please fix travis and percy's issues so that you can have your commit merged?

**Comment by robbyoconnor** [comment]
You need to remove the image that is not `240x240`. @Elgayar percy failing is fine -- there's a change to the page...it's expected to be different...

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
Resize images to 240x240 and remove photos which do not comply.

**Comment by Elgayar** [comment]
@robbyoconnor Okayy, thanks for telling me that!! I'll take care next time.

**Comment by robbyoconnor** [comment]
@ishan1604 -- ping

**Comment by robbyoconnor** [comment]
Closing due to lack of activity. Please open a new one when you have the chance. 

@ishan710 -- you need to address all issues mentioned here.

**Pull request closed without merging**
