### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by ghost**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ x ] Read and understood (see CONTRIBUTING.md)
- [ x ] Included a live link or preview screenshot
- [ x ] Images are `240 x 240` [w x h]
- [ x ] Resolved merge conflicts
- [ x ] Included a description of my change below

# Things done in this Pull Request

- There was error with the image so, I fix it and re uploaded the image
live link: https://github.com/balderasdiana27/gci16.fossasia.org

### CODE REVIEW

**Comment by abishekvashok** [comment]
Wasn't he added in #864 @balderasdiana27

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Please explain what are you trying to achieve as he was already added by you in #864

**Comment by ghost** [comment]
i know he is already added in #864 but is image is not showing up

**Comment by balderasdiana27** [comment]
image

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
there was a mistake using png instead of jpg

**Review by abishekvashok — CHANGES_REQUESTED** [review]
An image 'Bill Acha' exists pls remove that and add the image and don't touch the mentors.l in this PR please.

**Comment by abishekvashok** [comment]
@balderasdiana27 an image exists remove it also and don't modify the mentors.yml file if you are updating the image only :) ;)

**Pull request closed without merging**
