### PR TITLE
Update students.yml

### PR DESCRIPTION
**Pull request by sudo-panda**
Added Info and Photo

### CODE REVIEW

**Review by daminisatya — APPROVED** [review]
great job! :)

**Comment by daminisatya** [comment]
@Baidya99 It would be cool if you rename your image file's name.

**Comment by sudo-panda** [comment]
Thank you for approving.

**Comment by daminisatya** [comment]
So @Baidya99 you have a merge conflict now, any doubt regarding clearing the conflict please do ask !

**Comment by sudo-panda** [comment]
I have changed students.yml in another pull request.

**Comment by sudo-panda** [comment]
Could you please tell me something about loklak.

**Comment by jigyasa-grover** [comment]
>I have changed students.yml in another pull request.

@Baidya99 Pls do the photo upload and changes in `students.yml` all in the same pull request for easy review. Cheers !

**Comment by jigyasa-grover** [comment]
With reference to PR #39 , closing this.

I'd suggest you to add the picture in that PR and then squash the commits into one meaningfully naming the commit as " Added < your name > in students section"

**Pull request closed without merging**
