### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Dodecane**

### CODE REVIEW

**Review by Princu7 — CHANGES_REQUESTED** [review]
Thanks for the request. Please post a link to the task and your gh-pages for faster reviewing.

**Comment by Dodecane** [comment]
https://codein.withgoogle.com/dashboard/task-instances/4811085861355520/
https://leecaregene.github.io/

**Comment by Princu7** [comment]
@LeeCareGene You seem to have put the wrong link of your task instance. Please correct it. Also, it seems like your gh-pages is not in sync with this branch. For example, there is no student section on your pages. You can compare it to the official website http://gci16.fossasia.org/  Please review it. Thanks!

**Comment by Dodecane** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5464377371131904/
I fixed my Github page.

**Pull request closed without merging**
