### PR TITLE
Modified the social media section and moved contributors at the top

### PR DESCRIPTION
**Pull request by oanarosca**
View the result on https://oanarosca.github.io/gci16.fossasia.org/

### CODE REVIEW

**Review by hemantjadon — APPROVED** [review]
Nice Work @oanarosca

**Comment by daminisatya** [comment]
@oanarosca great! But would like to see the task link :)

**Review by daminisatya — APPROVED** [review]

**Comment by oanarosca** [comment]
It's not a particular task, but I've been told that I can contribute even without claiming one. I hope that isn't a problem :smile:

**Comment by daminisatya** [comment]
Never! You are free to contribute :) just wanted to confirm about the task, since i havent seen on the list.

**Pull request merged**
