### PR TITLE
Issue #632: Combine stylesheets to improve page load

### PR DESCRIPTION
**Pull request by gaeun**
I combined some stylesheets into main.css, which partly solves #632. The Google page speed insights provides three less errors for my live link page compared to the current website.
Live link: https://gaeun.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by Elgayar** [comment]
Did you compare your live link with the original one in Google PageSpeed Insights? If there is no difference then this pull is needless because it will just cause confusion, as the separate stylesheets were necessary for organization. @gaeun

**Comment by Elgayar** [comment]
Okay I did the tests: 
First one is your live link..
image

Second is the original..
image

Which means that your change isn't any better, it in fact decreased the performance, @gaeun

**Comment by gaeun** [comment]
@Elgayar Oh dear, I mixed up two tabs when I ran the tests. Nvm I'll find a better way to optimize :)

**Comment by Elgayar** [comment]
No worries! Keep coding and you'll do better :)

**Pull request closed without merging**
