### PR TITLE
Add myself to GCI16 site

### PR DESCRIPTION
**Pull request by dive0**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

I added my name, image, position, social media id, and my bio in students.yml. I also added my image in the images folder.

live link: dive0.github.io/gci16.fossasia.org

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@dive0, the instructions say to add it at a random location in the file, you have merge conflicts.

Don't add a unicode checkmark, rather check it within the PR as you read it. Github looks for an `[x]`

**Comment by robbyoconnor** [comment]
@dive0 I resolved your merge conflict -- what you linked wasn't a live link to your site. 

Before you make a pull request, make sure you pull from the upstream repo

**Comment by robbyoconnor** [comment]
FYI the live link is this: dive0.github.io/gci16.fossasia.org

**Comment by robbyoconnor** [comment]
Your image is in the wrong location. I can fix this on my end after merging. Please look at how others have done it next time. :)

**Comment by dive0** [comment]
@robbyoconnor do I have to squash the 2 commits?

**Comment by robbyoconnor** [comment]
you realize I merged this right @dive0 ?

**Comment by robbyoconnor** [comment]
We can squash when we merge.

**Comment by dive0** [comment]
Okay, thank you @robbyoconnor

**Pull request merged**
