### PR TITLE
Added the image of mentor and description

### PR DESCRIPTION
**Pull request by Srijanjha**

### CODE REVIEW

**Comment by codein-dwij** [comment]
Can I know what are you trying to do?
#674 #675 #687 and this one ? One mentor 4 pull requests -_- 3 are merged by yourself that shouldn't have been the case.

**Comment by Srijanjha** [comment]
That was done by mistake

**Comment by Srijanjha** [comment]
ok ill not merge it

**Comment by codein-dwij** [comment]
But what are you doing again and again?

**Comment by Srijanjha** [comment]
That was just done by mistake. i dont know all about that earlier

**Comment by Srijanjha** [comment]
how would i know that my pr is implimented

**Comment by robbyoconnor** [comment]
Once is a mistake...

**Comment by robbyoconnor** [comment]
You'd know your PR is implemented by looking at the site.

**Pull request closed without merging**
