### PR TITLE
Will Kaye added to student section

### PR DESCRIPTION
**Pull request by ghost**
http://will747.github.io 
Task: https://codein.withgoogle.com/dashboard/task-instances/6082868264566784/

### CODE REVIEW

**Comment by m1guelpf** [comment]
Looks good to me, but let's wait for Travis.

**Comment by ghost** [comment]
ok

**Comment by m1guelpf** [comment]
@Will747 as @checkbot said, you have to join FOSSASIA org.
Also, you have to fix the travis build.
Normally, this is caused by trailing spaces and EOF without line.

**Comment by ghost** [comment]
I filled out the form a few days ago, what do I need to correct?

**Comment by ghost** [comment]
OK, I will do that now

**Comment by m1guelpf** [comment]
Also, @Will747 cool profile pic!

**Pull request closed without merging**
