### PR TITLE
Added my MBDyn logo and profile

### PR DESCRIPTION
**Pull request by zehata**
https://zehata.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by zehata** [comment]
I would like to add my MBDyn logo and my profile as part of 2 GCI tasks.

**Comment by zehata** [comment]
https://zehata.github.io/gci16.fossasia.org/

**Comment by Princu7** [comment]
@zehta Your changes look nice. Please post the links to the task description.

**Comment by jigyasa-grover** [comment]
@zehata Clean work ✌️

**Pull request merged**
