### PR TITLE
Fixed footer

### PR DESCRIPTION
**Pull request by oanarosca**
Solves issue #663, see the changes [here](https://oanarosca.github.io/gci16.fossasia.org). As suggested, I replaced the images with Font Awesome icons.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Now restarting the build for you...

**Comment by robbyoconnor** [comment]
Merging.

**Review by robbyoconnor — APPROVED** [review]

**Comment by codein-dwij** [comment]
Great

**Comment by robbyoconnor** [comment]
Great work! Keep up the awesome work!

**Pull request merged**
