### PR TITLE
added blog details

### PR DESCRIPTION
**Pull request by arpnakumari**
it's block details

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Please do what @checkbot  has told you to do.

**Comment by robbyoconnor** [comment]
Can you please do this as one pull request not 3...

**Comment by arpnakumari** [comment]
@robbyoconnor can u elaborate? I didn't get it.

**Comment by robbyoconnor** [comment]
You made THREE pull requests...make one. Download the code, add all your changes, and then make a pull request. Also link to a live version of the site. Closing this.

**Comment by robbyoconnor** [comment]
Please clone your fork, work on it...add the images as it says...commit the code, and link to your live version...

**Comment by robbyoconnor** [comment]
Type exactly: 
```
git clone https://arpnakumari:yourpassword@github.com/arpnakumari/gci16.fossasia.org.git
git remote add upstream https://github.com/fossasia/gci16.fossasia.org.git
git fetch --all 
git reset --hard upstream/gh-pages
git push --force 
```
Make your changes adding all files to the proper directories in the proper dimensions (240 x 240)
```
git add . 
git commit -m "Added my blog" -a 
git push origin gh-pages  -f 
```

**Comment by robbyoconnor** [comment]
Download git here: https://git-scm.com/downloads

**Comment by robbyoconnor** [comment]
After you've done all of that make a new pull request.

**Comment by robbyoconnor** [comment]
Type exactly: 
```
git clone https://arpnakumari:yourpassword@github.com/arpnakumari/gci16.fossasia.org.git
git remote add upstream https://github.com/fossasia/gci16.fossasia.org.git
```
Make your changes adding all files to the proper directories in the proper dimensions (240 x 240)
```
git add . 
git commit -m "Added my blog" -a 
git pull --rebase upstream master
git push origin gh-pages  
```

**Comment by robbyoconnor** [comment]
There's no reason for there to be three pull requests for the same thing.

**Pull request closed without merging**
