### PR TITLE
Adding myself to the Students section

### PR DESCRIPTION
**Pull request by kartikeya23**
image
Refer to this please for the output

### CODE REVIEW

**Comment by oanarosca** [comment]
Hi! Thanks for your request! Before we can merge your work, please solve the merge conflicts. You can find more information about this in the contributing.md file, and if you need live help, write on slack! Happy contributing!

**Review by jigyasa-grover — COMMENTED** [review]
Why two images ?

**Comment by oanarosca** [comment]
@jig08 it was because the original file was `name.JPG` and the website wouldn't show it, so I asked him to rename it. @kartikeya23 please remove the duplicate image :smiley:

**Comment by jigyasa-grover** [comment]
@oanarosca yes, get it removed... thanks !

**Pull request closed without merging**
