### PR TITLE
updated my credentials and uploaded the picture for entry in students section.

### PR DESCRIPTION
**Pull request by manastaneja**
Thank you for your pull request!

Please acknowledge each of the following before submitting your pull request.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- leave it unchecked. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- 1)Updated my credentials.
   2)Uploaded my picture for the students section of Fossasia website.
Live Link: https://codein.withgoogle.com/dashboard/task-instances/5689112885460992/

### CODE REVIEW

**Comment by gaeun** [comment]
@manastaneja Hi, can you please edit the pull request description by checking the boxes that are applicable to you and adding a change description?

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
Please resize your image to `240 x 240 [w x h]`

Please also include a live link or screenshot. You must always read that template. We included checkboxes for a reason.

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Please resize the image it would be great if you could read the readme.md and contributing.md files please. After you resize your image check the boxes that are applicable to you, if you have doubts you can ask here we are all free to help. Also please read your PR body see some lines which state to be replaced please replace them. As @robbyoconnor stated they are for purpose

**Comment by robbyoconnor** [comment]
@manastaneja your image is *NOT* 240x240. Don't check it unless it is.

**Comment by robbyoconnor** [comment]
Read the README.md file.

**Comment by manastaneja** [comment]
@robbyoconnor i'm on it sir. Actually i am starting from scratch and clearing all the problems. Can you please close this pull request without merging and i'll put up a new pull request with all the corrections?

**Comment by abishekvashok** [comment]
@manastaneja here you go closed it, you can make a new PR it would be nice to delete your fork and re-fork as it is the easiest way to go forward. Read the readme.md and contributing.md files, they are there to help you make good code :) I await all fixed up PR from you.

Happy coding :)

**Pull request closed without merging**
