### PR TITLE
added animeshsinghweb geo location to students.yml

### PR DESCRIPTION
**Pull request by animeshsinghweb**
On the references to https://gci16.fossasia.org/geo/ I updated my
yml geo locations at students.yml, maybe it can be used on future.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@animeshsinghweb Remember that you can't merge your own PR's.
Check the mantainers.md

**Comment by animeshsinghweb** [comment]
@m1guelpf Yes I know, it was basic updated of students.yml, and waited for more than half an hour. Thought maintainers wouldn't mind small changes in the students data, anyway would keep in mind for future PR. 👍

**Comment by m1guelpf** [comment]
@animeshsinghweb As seen in mantainers.md you have to wait al least one day before merging own pr.

**Comment by animeshsinghweb** [comment]
@m1guelpf Seen ;D Would TC next. xD

**Comment by codein-dwij** [comment]
Its the second time you merged your own PR!

**Comment by m1guelpf** [comment]
@codein-dwij I already told him

**Pull request merged**
