### PR TITLE
Fixing MBDYN Logo issue

### PR DESCRIPTION
**Pull request by prabhdeep29**
#478 3 Logos were missing which will be added once this pull request is merged. This was done as a task from Google Code-in. Task Instance - https://codein.withgoogle.com/dashboard/task-instances/5471329681670144/

### CODE REVIEW

**Comment by codein-dwij** [comment]
I have updated your pr body and added reference to the issue :)

**Comment by m1guelpf** [comment]
LGTM

**Comment by m1guelpf** [comment]
@prabhdeep29 
```
The image ./images/logos/Prabhdeep.png is larger than 400px x 220px [w x h]
The image ./images/logos/danny.png is larger than 400px x 220px [w x h]
ImgChecker: There are images which exceed the expected dimensions as specified above
Please resize them sir... Happy coding
```
```
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
|----|    | /app/_data/logos.yml
|    |++++| /app/_data/logos.yml
|  30|  30| 
|  31|  31| - author: Ainesh Sootha
|  32|  32|   img: MBDyn6.png
|  33|    |-  
|    |  33|+
|  34|  34| - author: Prabhdeep Singh
|  35|  35|   img: Prabhdeep.png
|  36|  36|   
[INFO][15:52:17] Applied 'ShowPatchAction' on '_data/logos.yml' from 'SpaceConsistencyBear'.
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
|----|    | /app/_data/logos.yml
|    |++++| /app/_data/logos.yml
|  33|  33|   
|  34|  34| - author: Prabhdeep Singh
|  35|  35|   img: Prabhdeep.png
|  36|    |-  
|    |  36|+
|  37|  37| - author: Alexandru_nasta
|  38|  38|   img: Alexandru.png
|  39|  39| 
[INFO][15:52:17] Applied 'ShowPatchAction' on '_data/logos.yml' from 'SpaceConsistencyBear'.
```

**Comment by animeshsinghweb** [comment]
@m1guelpf Can I fix these?

**Comment by m1guelpf** [comment]
@animeshsinghweb Go ahead!

**Comment by prabhdeep29** [comment]
@m1guelpf Whats the dimensions??

**Comment by prabhdeep29** [comment]
200X200 Are enough????

**Comment by m1guelpf** [comment]
@prabhdeep29 I think so

**Comment by animeshsinghweb** [comment]
@prabhdeep29 Makes the width of the logo grid too dirty.

**Comment by animeshsinghweb** [comment]
@prabhdeep29 Too much commits can be difficult for a moderator to pull. Try squashing a couple before uploading. Any way, I had done this for you. If you think I shouldn't have let me know ASAP to close before it gets merge.

**Comment by prabhdeep29** [comment]
I made the dimensions 150X150

**Comment by prabhdeep29** [comment]
@animeshsinghweb yeaaa u shouldn't have because I have task which says that I have to solve an issue

**Comment by prabhdeep29** [comment]
but you can help me squash the commits as I have no idea how to do that

**Comment by animeshsinghweb** [comment]
@prabhdeep29 
```
I admit squashing is too difficult and risky. But to be in a better side, what you can try is open a new branch (never use your `gh-pages` branch for submit PR).
Have a look at my PR above for an example. To make a new branch use `git checkout -b yourbranchname`
and if you don't want to get into trouble make sure all thing is right before pushing it.
And if you make any changes, instead of recommiting with `git commit -m "my new commit"` you can do `git commit --amend` which would simply merge your new changes to your previous git commit.
```
Please refer the **CONTRIBUTING.md** in the repo for more help or ask mentors in the IRC such as Slack or Gitter.
```
That's confusing.
With :heart: ~ @m1guelpf
```

**Comment by animeshsinghweb** [comment]
@prabhdeep29 I didn't noticed that this is a GCI task. Anyways, you can go ahead and try fixing other issues as well, I know there are many issues which you can handle.

**Comment by animeshsinghweb** [comment]
@prabhdeep29 Also the dimension 150x150 wouldn't help. As they would completely destroy the UX.
In the **Readme.md** I have added a clear instructions to use **400x220**px dimensions for uploading your images, such that the grid doesn't change the UX of the site. It is very crucial.
**And I would re-update the README.md for clear instruction regarding the uploading of logo**

I know that it's not your fault, as those students in #478 had made wrong dimensions of logo, maybe because they where unsure about it. @louisgag can you update the instruction in the task to make the student clear of which dimensions they should use for logo, and make sure they read instructions in
Readme.md before uploading their logo?
Thanks.

**Comment by niccokunzmann** [comment]
@prabhdeep29 Would you like to squash the commits?

**Comment by animeshsinghweb** [comment]
@niccokunzmann I guess he might be sleeping now. It would take some time fo @prabhdeep29 to understand squashing, and he wouldn't mind resolving another UX issues.
Meanwhile you can check @baidya99 or mine PR: #493

**Comment by niccokunzmann** [comment]
I just merged #494 by @Baidya99. This looks quite like it. Let's start collaborating here and now.
Could you have worked together?

**Comment by animeshsinghweb** [comment]
@prabhdeep29 Since this PR (in contrast to PR #494 ) had already been pulled by @niccokunzmann, I am closing this PR.
I hope you don't mind resolving other Issue.

**Pull request closed without merging**
