### PR TITLE
Updated students.yml and mentors.yml

### PR DESCRIPTION
**Pull request by nikhilchandak**
Added my profile with image

Updated mentors.yml data file with Harsh Vardhan's profile

Harsh Vardhan's image added

https://nikhilchandak.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by oanarosca** [comment]
Hi! It seems that there are some merge conflicts, and so we can't merge your PR yet. Please see the contributing.md file for help on how to solve them, or write on slack -- we're there to help you!

**Comment by hillamu2** [comment]
Hello! Apparently there are some merging conflicts with the pr...I recently went through this problem too but don't worry there are several ways to fix the problem : you can either go and watch some tutorials on how to solve the conflicts in the contributing.md section ( example of a link is https://www.youtube.com/watch?v=g8BRcB9NLp4 ) or to create a new branch based on the gh-pages from this repository and make all the changes there and a new PR.
If you are facing other problems..dont be afraid to discuss them with us

**Comment by shubham-padia** [comment]
Closing it in favour of #382 . 
@nikhilchandak Good Job with #382 . But in future, please close the old PR when you create a new one for the same task.

**Comment by nikhilchandak** [comment]
@shubham-padia Okay.

**Comment by nikhilchandak** [comment]
@hillamu2 Thanks for your kind reply. I had created a new PR #382 to resolve the earlier conflicts and it got merged but I forgot to close this one.

**Pull request closed without merging**
