### PR TITLE
Fixed images

### PR DESCRIPTION
**Pull request by abishekvashok**
The image checker had reported that various images where large, I fixed
them to the dimension in readme.md file.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Abhi2424shek Please fix the image that fails the Travis build.

**Comment by niccokunzmann** [comment]
The image aspect ratio is changed. Some images a skewed. Also, the logo images should be available in smaller size and in bigger size.

**Comment by niccokunzmann** [comment]
We can create issues for this, then.

**Comment by abishekvashok** [comment]
@niccokunzmann we could merge this to satisfy the tests then open an issue to let the skewed image authors to post new images... Whats your opinion , if we don't fix the images now it will only be fixed a bit later that will make some of our contributors pale because on my interaction with most of them i find they want a green Travis. ;)

**Pull request merged**
