### PR TITLE
Added redirect

### PR DESCRIPTION
**Pull request by sudo-panda**
Solves #618

### CODE REVIEW

**Comment by sudo-panda** [comment]
@niccokunzmann please merge this.

**Comment by Abhi2424shek** [comment]
@Baidya jekyll doesnot support php parsing.

**Review by abishekvashok — DISMISSED** [review]
Jekyll doesnot support php try the html alternative please @Baidya99

**Comment by sudo-panda** [comment]
@Abhi2424shek will using meta in html be okay or should I add javascript?

**Comment by abishekvashok** [comment]
@Baidya99 meta should do the job for sure, simple and easy.

**Review by m1guelpf — APPROVED** [review]

**Comment by sudo-panda** [comment]
@niccokunzmann please merge this.

**Pull request merged**
