### PR TITLE
GCI Task: Add image slider

### PR DESCRIPTION
**Pull request by hoangvanthien**
https://hoangvanthien.github.io/

### CODE REVIEW

**Comment by hoangvanthien** [comment]
@daminisatya I finally squash commits successfully. And use `git commit --amend` too. Thanks to you for suggesting me and @yukiisbored for guiding me through.

**Comment by abishekvashok** [comment]
@hoangvanthien i cant see the commits being squashed!

**Comment by hoangvanthien** [comment]
@Abhi2424shek What? Is it a bad thing or a good thing?
screen shot 2016-12-04 at 00 14 03

**Comment by abishekvashok** [comment]
@hoangvanthien i can see 3 commits after squashing it has to be one did you pull

**Comment by hoangvanthien** [comment]
I leave 3 as they're 3 separated stuff that I want to see them in the process. It must have been 20 redundant commits before I squashed you know. @Abhi2424shek

**Comment by abishekvashok** [comment]
Nice, but the mentors here want just 1 and that's what they want. @hemantjadon can u help out your views on this.

**Comment by hemantjadon** [comment]
@hoangvanthien The slider's code part seems good to me.
Just squash these three commits into one and we will be good to go.
Also please use images of reduced size as currently they are taking a lot of time to load.

**Comment by hemantjadon** [comment]
@Abhi2424shek @hoangvanthien 

We do not force you to squash the commits just for the sake of doing so.

Squashing commits is required to keep the project history clean an concise.

Suppose we have a project to which someone submits the PR to "Added feature X". Now this PR contains suppose 10 commits Then if we merge directly we will get 10 commits from V1 -> V2.

10 commits for a single feature seems very large. Do we really care about the work in progress(wip) commits in which there are small changes or fixes to your own code? No, we don't.

All we care about is The PR to add that "Feature X" so we squash those commits into one to represent the change from V1 -> V2.

Here are few links to some articles which might help you to understand why squashing is required.

* http://jamescooke.info/git-to-squash-or-not-to-squash.html

* http://softwareengineering.stackexchange.com/a/263172

* https://github.com/blog/2141-squash-your-commits

I hope I am pretty clear that why we follow the best practices require to squash the commits.

**Comment by hoangvanthien** [comment]
@hemantjadon I squashed. There shouldn't be any error from Travis.
UPD: Phew, all passed :D

**Comment by hemantjadon** [comment]
@hoangvanthien 
Good work there :)

Keep Coding :)

**Comment by hoangvanthien** [comment]
I'm trying to fix 404 error which is caused by something unknown. :(

**Pull request merged**
