### PR TITLE
Added Tushar in Students

### PR DESCRIPTION
**Pull request by awesometushar000**
I added myself in students list as the task GCI:2016
https://codein.withgoogle.com/dashboard/task-instances/6371142912704512/

### CODE REVIEW

**Comment by codein-dwij** [comment]
Please resolve the merge commits and provide a link to the live gh-pages :)

**Comment by abishekvashok** [comment]
@meets2tushar nice work, clean code :) This time I resolved your merge conflicts but next time please consider removing them yourselves... @codein-dwij we can also remove the conflicts.

**Comment by codein-dwij** [comment]
@Abhi2424shek Did you resolve the merge conflicts for him?I think you shouldn't do that!

**Comment by abishekvashok** [comment]
@codein-dwij see the maintainers file... we are here to help right :)

**Comment by awesometushar000** [comment]
@Abhi2424shek  what was the merge conflicts ? And my twitter id is missing .

**Comment by codein-dwij** [comment]
@meets2tushar your students.yml was having merge conflicts.
If you want to add your twitter then first edit your file , fix conflicts(they will appear again) and create a new Pull Request

**Comment by awesometushar000** [comment]
Please help me, i am thubreally not getting to understand the concept behind merge conflicts.
I added my twitter account in the file and saw that on my github webpage. And when I add my blog profile then its icon is not showing ?

**Comment by codein-dwij** [comment]
No worries! Please join the slack channel. More info to join - check readme.md

**Pull request merged**
