### PR TITLE
Optimize images for shrinkray-59d5c632-9d38-4c1e-9691-9e1fd49b8181

### PR DESCRIPTION
**Pull request by gaeun**

### CODE REVIEW

**Comment by gaeun** [comment]
Images shrunk 31.25% (160648b -> 110456b)


* images/students/aditya.jpg (10323b -> 10305b)
* images/students/Phuc.jpg (15855b -> 14868b)
* images/students/Baidya.jpg (20852b -> 20276b)
* images/students/Prabhdeep.jpg (38250b -> 13747b)
* images/students/nadunyashmika.jpg (37577b -> 14120b)
* images/students/tushar.jpg (18589b -> 17992b)
* images/mentors/hemantjadon.jpg (6151b -> 6133b)
* images/mentors/mariobehling.jpg (6265b -> 6247b)
* images/mentors/saptaks.jpg (6786b -> 6768b)

**Comment by gaeun** [comment]
Images shrunk 12.96% (173192b -> 150759b)


* images/students/dewansh.jpg (4542b -> 4156b)
* images/students/mukund.jpg (11283b -> 11093b)
* images/blogs/pranavblog.jpg (33500b -> 33482b)
* images/mentors/dishantkhanna.jpg (11910b -> 11892b)
* images/students/hmc.jpg (13015b -> 12575b)
* images/blogs/animeshsinghweb.jpg (82662b -> 61679b)
* images/students/zahari.jpg (8550b -> 8532b)
* images/students/Guneet.jpg (7730b -> 7350b)

**Comment by Abhi2424shek** [comment]
@gaeun pls don't remove the PR template next time pls...

**Comment by gaeun** [comment]
@m1guelpf Thanks for merging, it seems like shrinkray.io worked fairly well!

**Comment by robbyoconnor** [comment]
Good work!

**Pull request merged**
