### PR TITLE
#534 solved UX and UI issues solved

### PR DESCRIPTION
**Pull request by kartikhsr**
live link : https://kartikhsr.github.io/gci16.fossasia.org/
solved issue #534 changing styles of footer

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@kartikhsr There is a conflict in `index.html` file please resolve it first.
You can refer to [**CONTRIBUTING.md**](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) for more info.

**Comment by kartikhsr** [comment]
@animeshsinghweb i have done it
live link : https://kartikhsr.github.io/gci16.fossasia.org/

**Comment by animeshsinghweb** [comment]
@kartikhsr Let me go through them. Also do mention the points you had solved in that Issue. 👍

**Comment by animeshsinghweb** [comment]
@kartikhsr LGTM. It's better and clear. Merging it.

**Pull request merged**
