### PR TITLE
Adding student, Kartikeya

### PR DESCRIPTION
**Pull request by kartikeya23**

### CODE REVIEW

**Comment by gaeun** [comment]
@kartikeya23 Do you have the website preview link? You can find the link at http://your_username.github.io/gci16.fossasia.org/ 
Also, try squashing all your commits if you can :)

**Comment by kartikeya23** [comment]
@gaeun , how do I squash?

**Comment by kartikeya23** [comment]
Please guide...

**Comment by m1guelpf** [comment]
@kartikeya23 You can find squashing instructions in the contribuiting.md file. Also, if you have problems, Github allows to squash and merge, so any mentor/mantainer can squash it for you.

**Comment by abishekvashok** [comment]
@kartikeya23 don't worry about squashing bro and if you are facing any problems feel free to ask

**Pull request closed without merging**
