### PR TITLE
Using media query to fix blogs section on phones

### PR DESCRIPTION
**Pull request by myfrom**
Related to #546 
Part of GCI [task](https://codein.withgoogle.com/dashboard/task-instances/5483972958093312/)

I include only screenshot as I'm gonna need gh-pages of my fork for other demo. Bigger viewports stay unaffected.
screenshot

### CODE REVIEW

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Can you make the blogs a little to the right side more so that they are absolutely at the center, now they are not in the center.

**Comment by myfrom** [comment]
@Abhi2424shek I was trying but it was causing weird problems with box shadow. Also all cards in small viewports are moved a little to the left. Should I try again?

**Comment by abishekvashok** [comment]
@Witus13 take your time.... If you want help I am more than happy to help you out :)

**Comment by myfrom** [comment]
@Abhi2424shek Ok, fixed. Bigger viewports still unaffected. I updated the screenshot.

**Review by abishekvashok — APPROVED** [review]

**Comment by abishekvashok** [comment]
@Witus13 nice and clean work do you know squashing or should I squash and merge for you.

**Comment by myfrom** [comment]
@Abhi2424shek Could you please squash it for me? I was updating my fork using PR from original and it brings mess when I try to squash from console

**Comment by abishekvashok** [comment]
@Witus13 @animeshsinghweb has squashed for you already so no worries :)

**Comment by animeshsinghweb** [comment]
@Witus13 We can understand that, it is difficult to squash when you work on `gh-page` branch and you do pull from the main repo for being updated.
Anyways, as @Abhi2424shek said, Happy Coding! 👍

**Comment by abishekvashok** [comment]
@animeshsinghweb 

> Happy Coding!

That's my tag line 😄. I grant you permission anyway 😆 
Happy coding ❤️

**Comment by animeshsinghweb** [comment]
Thanks @Abhi2424shek for kindness.
My tagline is little weird. Let me know if you can decode by [reading this up](https://wp.me/p8cpP5-2y).

**Pull request merged**
