### PR TITLE
Added animeshsinghweb to _data and modified UX

### PR DESCRIPTION
**Pull request by animeshsinghweb**
I added my image and updated students.yml and blogs.yml with my info and fixed few UX bugs.

My task: https://codein.withgoogle.com/dashboard/task-instances/4646195228049408/
My GH-Pages: https://animeshsinghweb.github.io/gci16.fossasia.org/

Thanks.

### CODE REVIEW

**Comment by shubham-padia** [comment]
There are some spacing inconsistencies. Please have a look at https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181149513 for more details and fix them

**Review by jigyasa-grover — COMMENTED** [review]
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"

* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Comment by jigyasa-grover** [comment]
With reference to [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Comment by animeshsinghweb** [comment]
Sorry for not closing myself, @jig08 thanks for closing.

**Pull request closed without merging**
