### PR TITLE
Info about CodeHeat added

### PR DESCRIPTION
**Pull request by nikhilchandak**
Slider added with links and information about CodeHeat contest with image.

### CODE REVIEW

**Comment by nikhilchandak** [comment]
https://nikhilchandak.github.io/gci16.fossasia.org/

**Comment by niccokunzmann** [comment]
Looks good! Thanks!

**Comment by niccokunzmann** [comment]
Can you have a look if it is correctly displayed and open an issue or PR if not?

**Comment by nikhilchandak** [comment]
@niccokunzmann Great to know that. Happy Contributing!

**Comment by nikhilchandak** [comment]
@niccokunzmann Checking the website...

**Comment by nikhilchandak** [comment]
@niccokunzmann Sorry to report, but the image is too zoomed in and no text is getting displayed on the original website :(

**Comment by niccokunzmann** [comment]
You can create an issue...

**Comment by niccokunzmann** [comment]
And if you like, you are allowed to work on it :)

**Comment by nikhilchandak** [comment]
Issue Created - #434

**Pull request merged**
