### PR TITLE
Add categorisation to "Latest Issues" section

### PR DESCRIPTION
**Pull request by kaine119**
Issues are now categorised by label assigned. If the issue has the label, it's in the category.

[Link to my gh-pages](https://kaine119.github.io/gci16.fossasia.org/)
[Link to gci2016 page](https://codein.withgoogle.com/dashboard/task-instances/4901061976391680/)

### CODE REVIEW

**Comment by m1guelpf** [comment]
@kaine119 Please fix:
```
index.html
| 285| ••••••••••••••••••••••••
|    | [MAJOR] HTMLLintBear:
|    | Trailing Whitespace: Trailing white spaces are unnecessary and can complicate diffs: Remove the '                        ' at the end of the line.

index.html
| 296| ••••••••••••••••••••••••••••<i•class="icon•social_twitter•text-white"></i>
|    | [MAJOR] HTMLLintBear:
|    | ID and Class Name Delimiters: The class names should be lowercase and with hyphens instead of underscores: Remove the offending characters from the class "icon social_twitter text-white".

index.html
| 297| ••••••••••••••••••••••••••••<div•class="tweets-feed"•id="tweets"•data-count=50•data-query="fossasia•#gci">
|    | [MAJOR] HTMLLintBear:
|    | HTML Quotation Marks: Use only double quotes: Change the quotation mark  to '"'.

index.html
| 307| ••••••••••••••••••••••••••••••••&#8592;•&nbsp;•Previous•Tweet!
|    | [MAJOR] HTMLLintBear:
|    | Entity References: Use the unicode equivalent instead: Change "&#8592;" to "←".

index.html
| 310| ••••••••••••••••••••••••••••••••Next•Tweet!•&nbsp;•&#8594;
|    | [MAJOR] HTMLLintBear:
|    | Entity References: Use the unicode equivalent instead: Change "&#8594;" to "→".

index.html
| 230| ••••••••••••••••••••••••<a•href="{{blog.article_link}}"•target="_blank">
|    | [MAJOR] BootLintBear:
|    | Only columns (`.col-*-*`) may be children of `.row`s

index.html
| 232| ••••••••••••••••••••••••••••<div•style="width:•440px"•class="card•col-xs-12•col-sm-12•col-md-6•col-lg-6">
|    | [MAJOR] BootLintBear:
|    | Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

index.html
| 234| ••••••••••••••••••••••••••••<div•style="width:•200px"•class="card•col-xs-12•col-sm-6•col-md-4•col-lg-3">
|    | [MAJOR] BootLintBear:
|    | Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

index.html
| 297| ••••••••••••••••••••••••••••<div•class="tweets-feed"•id="tweets"•data-count=50•data-query="fossasia•#gci">
|    | [MAJOR] BootLintBear:
|    | `.panel-footer` must have a `.panel` or `.panel-collapse` parent

index.html
| 232| ••••••••••••••••••••••••••••<div•style="width:•440px"•class="card•col-xs-12•col-sm-12•col-md-6•col-lg-6">
|    | [MAJOR] BootLintBear:
|    | Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="card col-xs-12 col-sm-12 col-md-6 col-lg-6"` is redundant and can be simplified to `class="card col-xs-12 col-md-6"`

index.html
| 306| ••••••••••••••••••••••••••••<div•class="btn"•id="previous"onclick="lastTweet()">
|    | [MAJOR] BootLintBear:
|    | `.btn` should only be used on `<a>`, `<button>`, `<input>`, or `<label>` elements.

index.html
| 309| ••••••••••••••••••••••••••••<div•class="btn"•id="next"onclick="nextTweet()">
|    | [MAJOR] BootLintBear:
|    | `.btn` should only be used on `<a>`, `<button>`, `<input>`, or `<label>` elements.
```

**Comment by kaine119** [comment]
@m1guelpf Are major issues the only thing that fail the CI? If so, then...
```
| 298| <div•class="tweets-feed•panel"•id="tweets"•data-count=50•data-query="fossasia•#gci">

|    | [MAJOR] HTMLLintBear:

|    | HTML Quotation Marks: Use only double quotes: Change the quotation mark  to '"'.
```
... I have no idea what to do here. There are no single quotes on that line.

**Comment by abishekvashok** [comment]
Did you add ' ' together or " @kaine119 besides there are trailing space errors and others please check it.

**Comment by abishekvashok** [comment]
@kaine119 let's wait for travis

**Comment by m1guelpf** [comment]
@Abhi2424shek @kaine119 Travis log:
```
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
|----|    | /app/_data/blogs.yml
|    |++++| /app/_data/blogs.yml
| 118| 118|   blog_img: Blog.png
| 119| 119|   article: My connection with FOSSASIA
| 120| 120|   article_link: http://prabh29.edublogs.org/2016/12/10/my-connection-to-fossasia-and-gci/
| 121|    |-  
|    | 121|+
| 122| 122| - name: Dwij Jha
| 123| 123|   blog: https://dwijjha.wordpress.com
| 124| 124|   blog_img: blog_dwij.png
[INFO][16:13:16] Applied 'ShowPatchAction' on '_data/blogs.yml' from 'SpaceConsistencyBear'.
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - No newline at EOF.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 616| 616| #next {
| 617| 617|     float: right;
| 618| 618|     color: white;
| 619|    |-}
|    | 619|+}
index.html
| 298| ••••••••••••••••••••••••••••<div•class="tweets-feed•panel"•id="tweets"•data-count=50•data-query="fossasia•#gci">
|    | [MAJOR] HTMLLintBear:
|    | HTML Quotation Marks: Use only double quotes: Change the quotation mark  to '"'.
javascripts/tweet.js
|  13| ••••loklakFetcher.getTweets({},•datahandler);
|    | [NORMAL] JSHintBear:
|    | 'loklakFetcher' is not defined.

javascripts/tweet.js
|  25| ••••parser(stuff);
|    | [NORMAL] JSHintBear:
|    | 'stuff' is not defined.

javascripts/tweet.js
|  39| function•lastTweet()•{
|    | [NORMAL] JSHintBear:
|    | 'lastTweet' is defined but never used.
javascripts/main.js
| 328| ••••for•(var•i•=•0;•i•<•labels.length;•i++)•{
|    | [NORMAL] JSHintBear:
|    | 'i' is already defined.

javascripts/main.js
| 334| ••••••for•(j•=•data.length•-•1;•j•>=•0;•j--)•{
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 334| ••••••for•(j•=•data.length•-•1;•j•>=•0;•j--)•{
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 334| ••••••for•(j•=•data.length•-•1;•j•>=•0;•j--)•{
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 335| ••••••••for•(var•k•=•data[j].labels.length•-•1;•k•>=•0;•k--)•{
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 336| ••••••••••if•(data[j].labels[k].name•===•labels[i].name)•{
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 340| ••••••••••••••••.append($("<span></span>").append(data[j].number))
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 341| ••••••••••••••••.append($("<a></a>").attr("target",•"_blank").attr('href',•data[j].html_url).append(data[j].title))
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 341| ••••••••••••••••.append($("<a></a>").attr("target",•"_blank").attr('href',•data[j].html_url).append(data[j].title))
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 342| ••••••••••••••••.append($("<p>Opened•by•</p>").append($("<a></a>").append(data[j].user.login).attr("href",•data[j].user.html_url).attr('target',•'_blank')))
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 342| ••••••••••••••••.append($("<p>Opened•by•</p>").append($("<a></a>").append(data[j].user.login).attr("href",•data[j].user.html_url).attr('target',•'_blank')))
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 345| ••••••••••••••••••••.attr("href",•data[j].html_url)
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 348| ••••••••••••••••••••.append(data[j].comments))
|    | [NORMAL] JSHintBear:
|    | 'j' used out of scope.

javascripts/main.js
| 339| ••••••••••••issueElement•=•$('<div•class="issue"></div>')
|    | [NORMAL] JSHintBear:
|    | 'issueElement' used out of scope.

javascripts/main.js
| 350| ••••••••••••categoryElement.append(issueElement);
|    | [NORMAL] JSHintBear:
|    | 'issueElement' used out of scope.
```

**Comment by abishekvashok** [comment]
Hey @kaine can you recheck if you can't help out some one among us would submit a new PR resolving them, so @m1guelpf if he is fed up with Travis really much we can review thoroughly and merge right?!

**Comment by m1guelpf** [comment]
@Abhi2424shek I think we can merge it as most Travis problems aren't because of this PR, we'll fix them later with that autopatch applier :smile:

**Comment by kaine119** [comment]
* How might one resolve the "variable already defined/variable used out of scope" issue?
* The `loklak_server` and `stuff` variables in tweet.js are all kinds of strange
* I'm pretty sure there isn't any trailing whitespace in _data/blogs.yml
spaces represented as dots
* I'm also pretty sure that the quotes issue in index.html should be resolved.
screenshot from 2016-12-12 00-24-59

Other than that the other issues should be fine.

Thanks!

**Comment by abishekvashok** [comment]
It's merged

**Pull request merged**
