### PR TITLE
Added Yash Kumar Verma to student section

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Sir/Madam,

I've done the following.
1. Added my credentials to students.yml.
2. added image on index.html page.
3. fixed indentation on index.html code. :)

Thanks

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@YashKumarVerma Please post a link as well or relevant screenshot for easier review. Cheers !

**Review by daminisatya — CHANGES_REQUESTED** [review]
Please provide a link to your changes, as @jig08 mentioned. Also resolve your conflicts. If you need any help you consult the mentor!

**Comment by jig08** [comment]
@YashKumarVerma Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful :)

**Review by jigyasa-grover — COMMENTED** [review]
As @daminisatya suggested, @YashKumarVerma Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful :)

**Pull request closed without merging**
