### PR TITLE
Added Avi Aryan's information

### PR DESCRIPTION
**Pull request by yvars**
Here is a live link: https://yvars.github.io/yvars/
Added @aviaryan 's picture, github and twitter!

### CODE REVIEW

**Comment by yvars** [comment]
This was for the task the Google Code In task also! https://codein.withgoogle.com/dashboard/task-instances/6554726323716096/

**Comment by m1guelpf** [comment]
LGTM

**Comment by yvars** [comment]
Thanks @m1guelpf! Could you please accept it?

**Comment by yvars** [comment]
O its merged did not saw that. Thanks!

**Comment by yvars** [comment]
@m1guelpf can you accept my Google-Code-In task too?

**Comment by m1guelpf** [comment]
@yvars Sorry, but I'm also an student.
You'll have to wait till a mentor logs in.

**Comment by niccokunzmann** [comment]
Thanks! Approved.

**Pull request merged**
