### PR TITLE
Fixes #991 : added info section similar to gci 17 fossasia website

### LINKED ISSUE #991: Add an info section similar to the GCI website 2017 below the header
The info section should include:
* 700+ students
More than 350 successfully completed tasks in Google Code-In with FOSSASIA in 2016.

* 1500+ tasks
1549 tasks were completed this year, from solving issues, to building web apps, setting up applications and creating blog posts.

* 40 mentors
Mentors are developers, engineers, university students, professors, and generally contributors who love to share and be a part of our open source community. They help creating better software for a better and just world.

screenshot from 2018-02-09 12-34-41

### PR DESCRIPTION
**Pull request by abhi40308**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added info section similar to gci17 website.

### CODE REVIEW

**Comment by abhi40308** [comment]
Ping @yashLadha @mariobehling

**Comment by abhi40308** [comment]
screen shot 2018-05-10 at 10 24 40 pm

**Review by yashLadha — APPROVED** [review]
LGTM nice work

**Comment by yashLadha** [comment]
@anshumanv Can you please review it?

**Review by anshumanv — APPROVED** [review]

**Comment by yashLadha** [comment]
Ping @mariobehling  Please merge this.

**Pull request merged**
