### PR TITLE
Task Submission For David Nagli

### PR DESCRIPTION
**Pull request by davidnagli**

### CODE REVIEW

**Review by daminisatya — APPROVED** [review]
Well done!

**Comment by davidnagli** [comment]
I'm new to GCI. How long does it take for a submitted task to be accepted after it has been submitted?

**Comment by daminisatya** [comment]
@davidnagli It depends on the mentor! If the mentor is satisfied with the work submitted it gets approved within seconds!

**Comment by davidnagli** [comment]
@daminisatya Oh, so each submission get's assigned to a mentor

**Comment by daminisatya** [comment]
Yes, I have added a comment on your task. Please check.

**Pull request merged**
