### PR TITLE
Fixing #535

### PR DESCRIPTION
**Pull request by myfrom**
Making blog avatars use `background-size: cover` to avoid squashing images.
[Live demo](https://witus13.github.io/gci16.fossasia.org#blogs)

BTW: I haven't manually changed Gemfile.lock, idk why is it here, I only run a few commands based on what I found in .travis.yml to serve the page locally.

### CODE REVIEW

**Comment by abishekvashok** [comment]
@Witus13 I added a tag to the PR body so that danger wont fail...

**Comment by myfrom** [comment]
What is `danger --verbose` doing? It always breaks Travis

**Comment by abishekvashok** [comment]
@Witus13 that's because you are modifying the core file i.e, the index.html I added a tag in the PR body now it wont fail, I would restart the tests for you, is it ok :)

**Comment by abishekvashok** [comment]
@Witus13 now danger wont hurt you can you mention the exact resolution in the readme file also.

**Comment by myfrom** [comment]
@Abhi2424shek Thanks! But what did you mean by exact resolution?

**Comment by niccokunzmann** [comment]
Thanks for your contribution :)

**Pull request merged**
