### PR TITLE
Optimized images

### PR DESCRIPTION
**Pull request by abishekvashok**
Optimized most of the images so as to improve speed
Here are the previews,
for mobile:
image

see: [https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fabhi2424shek.github.io%2Fgci16.fossasia.org&tab=mobile](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fabhi2424shek.github.io%2Fgci16.fossasia.org&tab=mobile)

for desktop:
image

see: [https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fabhi2424shek.github.io%2Fgci16.fossasia.org&tab=desktop](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fabhi2424shek.github.io%2Fgci16.fossasia.org&tab=desktop)

I improved 42 points for mobile and 30 points for desktop [Initial was both 0][It shows further optimization suggestion because github contributor images are loaded dynamically from github], please take a look at [https://abhi2424shek.github.io/gci16.fossasia.org](https://abhi2424shek.github.io/gci16.fossasia.org)
and see it for yourself :)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Take a look @hemantjadon

**Comment by hemantjadon** [comment]
This seems pretty solid to me. 

Nice work @Abhi2424shek

**Comment by abishekvashok** [comment]
@hemantjadon thanks, can you merge it and accept my task.

**Comment by hemantjadon** [comment]
Can you see why photo of @vickyjjj (Victoria Juan) is not showing up, so that we may give her a heads up.

**Comment by hemantjadon** [comment]
Task links please :)

**Comment by abishekvashok** [comment]
one sec @hemantjadon please wait till I get it sir

**Comment by abishekvashok** [comment]
@hemantjadon here's the link to the task: https://codein.withgoogle.com/dashboard/task-instances/4791381899870208/

**Comment by abishekvashok** [comment]
@hemantjadon @vickyjjj 's photo is not found, may be we will push her to upload it again or do you want me to upload her github pic for her

**Comment by hemantjadon** [comment]
Let us ask her for her photo first.

**Comment by abishekvashok** [comment]
@hemantjadon k

**Pull request merged**
