### PR TITLE
Update for blogs.yml

### PR DESCRIPTION
**Pull request by manrajjuneja**
https://manrajjuneja.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by oanarosca** [comment]
Hi! The changes look good to me, but please provide the link to your gh-pages so we can see the result :smile:

**Comment by m1guelpf** [comment]
@manrajjuneja Please add a link to the live website.

**Comment by m1guelpf** [comment]
@manrajjuneja LGTM, but you have to solve the merge problems. Check contribuiting.md for help.

**Comment by niccokunzmann** [comment]
Closing this beacause #354 is merged. You can open it if you like.

**Pull request closed without merging**
