### PR TITLE
Attempt to fix travis builds

### PR DESCRIPTION
**Pull request by ankitrgadiya**
- Trailing Whitespaces fixed.
- Removed _site folder from .gitignore for percy.
- Fixed Photos as per ImgChecker.rb.

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
This PR is causing troubles while `git pull`ing or `git clone` from the repo.
There were some untracked files, I guess. Please @ankitrgadiya can you check'em out?

**Comment by ankitrgadiya** [comment]
@animeshsinghweb I'm not sure what you're talking about. There were not untracked files

**Comment by animeshsinghweb** [comment]
Try pulling from the official repo of GCI16 to your gh-page branch. Is all going good in your side?

**Comment by ankitrgadiya** [comment]
@animeshsinghweb  Yes?

**Comment by animeshsinghweb** [comment]
It's resolved now. 👍

**Comment by ankitrgadiya** [comment]
Cool

**Pull request merged**
