### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by Rbkovacev**
https://github.com/Rbkovacev/gci16.fossasia.org

I don't know if this works but: https://codein.withgoogle.com/dashboard/task-instances/5753489906991104/

### CODE REVIEW

**Comment by Princu7** [comment]
@Rbkovacev Thanks for the request. Please include the following things in your PR

* A link to your task description which you are solving through this issue. Also, post a link to your live gh-pages for faster and easier reviewing.

* Squash the commits into one and give it a declarative name like "Added New MBDYN Logo". If you are not sure about squashing the commits, you can refer to the contributing guide of this project.
https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md

* Look into the details of the Travis build and see why it is failing. There might be some space inconsistencies or trailing whitespaces in your code which might cause the build to fail.

**Review by Princu7 — CHANGES_REQUESTED** [review]
Please do the mentioned things. If you need any help, you can ask us here or ping in the GCI chat channel on slack.

**Comment by Rbkovacev** [comment]
sorry, the most recent PL was an accident.

**Comment by Rbkovacev** [comment]
I have updated the yml file and submitted a PR again

**Comment by rhemon** [comment]
@Rbkovacev you have merge conflicts you will need to work on that, also please squash your commits, theres too many. If you don't know how to look into [CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md). You will see there are some tutorial links provided on how to solve merge conflicts and and squashing commits.

best of luck 👍

**Comment by rhemon** [comment]
and a correction that is it should be PR(for Pull Request)

**Comment by niccokunzmann** [comment]
@Rbkovacev, you can not remove merge conflicts over the github web interface. Please have a look at the tutorials mentioned [earlier](https://github.com/fossasia/gci16.fossasia.org/pull/254#issuecomment-265654382). Another approach would be to create a new banch based on the gh-pages from this repository and make all the changes there and a new PR. The first solution would be preferable.
Do you need help with this? You can chat in the #gci channel in http://fossasia-slack.herokuapp.com/. or here.

**Comment by hillamu2** [comment]
Hello...Are you having some issues on how to solve merge conflicts? I was going through some difficulties too. You can solve them by watching tutorial such as in this link : https://www.youtube.com/watch?v=g8BRcB9NLp4 or by choosing other solutions in the  CONTRIBUTING.md section . If you're having any other problem don't hesitate to ask and don't give up ;)

**Comment by niccokunzmann** [comment]
@Rbkovacev I found a new way to merge. Could you help me and see if everything is correctly displayed?

**Pull request merged**
