### PR TITLE
Redid everything

### PR DESCRIPTION
**Pull request by Dodecane**

### CODE REVIEW

**Comment by Dodecane** [comment]
Do I still need to squash?

**Comment by Princu7** [comment]
@LeeCareGene It's okay. Just post a link to your task and gh-pages and you are good to go. Nice work.

**Comment by Dodecane** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5464377371131904/
leecaregene.github.io

**Comment by Princu7** [comment]
@LeeCareGene Well done. Keep up the good work!

**Pull request merged**
