### PR TITLE
fixed missing properties and semicolons in main.css file

### PR DESCRIPTION
**Pull request by sanchittechnogeek**
fixed missing properties and semicolons in main.css file

### CODE REVIEW

**Review by abishekvashok — APPROVED** [review]
Nice work

**Comment by jigyasa-grover** [comment]
Similar changes made in PR https://github.com/fossasia/gci16.fossasia.org/pull/407

**Comment by Princu7** [comment]
Nice work. Thanks so much.

**Comment by jig08** [comment]
@Princu7 @Abhi2424shek Dont merge yet.

**Comment by Abhi2424shek** [comment]
I don't have write access so no worries @jig08

**Pull request closed without merging**
