### PR TITLE
Fix html travis fail

### PR DESCRIPTION
**Pull request by niccokunzmann**
https://travis-ci.org/fossasia/gci16.fossasia.org/builds/182853438#L438

Please do not merge until the travis build completes and is green.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@niccokunzmann Already fixed at #386

**Comment by niccokunzmann** [comment]
Thanks, just saw it :)

**Comment by m1guelpf** [comment]
@niccokunzmann Why did you reopen it?

**Comment by niccokunzmann** [comment]
No, I clicked close.

**Comment by niccokunzmann** [comment]
At least the button that is there, usually.

**Comment by m1guelpf** [comment]
Ok, sorry

**Pull request closed without merging**
