### PR TITLE
MBDYN LOGO#

### PR DESCRIPTION
**Pull request by prabhdeep29**
Created LOGO for MBDYN. Task link https://codein.withgoogle.com/dashboard/task-instances/6701828584505344/

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, awesome. Do you have a link where I can view it?

**Review by jigyasa-grover — COMMENTED** [review]
* Rename the commit to something meaningful, such as "Adding <-your-name-> in students/mentors/logos section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Include a link to your Google Code-In task as well to fasten the process.

Cheers !

**Comment by oanarosca** [comment]
Hi! Looking at your code I noticed that you didn't add the div containing your logo inside the existing row div. For the bootstrap columns to work, they must be inside a div with class "row", so please add yours there. And while you're doing it, see why the Travis build failed and correct the inconsistencies. Happy contributing!

**Comment by niccokunzmann** [comment]
@prabhdeep29 I would like to help you understand the test output:

After #################

```
Executing section Default...

|    | [NORMAL] SpaceConsistencyBear:

|    | Line contains following spacing inconsistencies:

|    | - Trailing whitespaces.
                               ######################## There is a whitespace at the end of a line
|----|    | /app/CONTRIBUTING.md

|    |++++| /app/CONTRIBUTING.md

|  36|  36| * [Changing a commit message](https://help.github.com/articles/changing-a-commit-message/)

|  37|  37| 

|  38|  38| ### Merge Commits

|  39|    |-* [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) 

|    |  39|+* [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4)

|  40|  40| 

|  41|  41| ### Squash Commits

|  42|  42| * [Git Rebase (squash last commit)](https://www.youtube.com/watch?v=qh9KtjfjzCU)

[INFO][17:07:33] Applied 'ShowPatchAction' on 'CONTRIBUTING.md' from 'SpaceConsistencyBear'.

Executing section html...

[WARNING][17:07:34] Selected default action 'ShowPatchAction' for bear 'BootLintBear' is not applicable. Action not applied.

[WARNING][17:07:34] Selected default action 'ShowPatchAction' for bear 'BootLintBear' is not applicable. Action not applied.

[WARNING][17:07:34] Selected default action 'ShowPatchAction' for bear 'BootLintBear' is not applicable. Action not applied.

index.html

| 322| ••••••••••••••••<div•class="row">
                            ##################### As oanarosca said: There needs to be something around the row Maybe the other containers have it.
|    | [MAJOR] BootLintBear:

|    | Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

index.html

| 334| ••••••••••••••••<div•class="row">

|    | [MAJOR] BootLintBear:

|    | Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

index.html

| 294| •••••••••••••••••<div•class="col-xs-4•col-sm-3">

|    | [MAJOR] BootLintBear:

|    | Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

Executing section yaml...
```

**Comment by jigyasa-grover** [comment]
With reference to [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
