### PR TITLE
Create Melo5154_MBDyn logo

### PR DESCRIPTION
**Pull request by GramescuDan**
mbdyn logo

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Melo5154 I see you're trying to add a logo...
Please read [our help on adding logos](https://github.com/fossasia/gci16.fossasia.org#adding-logos), apply the changes and ping me when done.
(Ping example: @m1guelpf done)

**Comment by jigyasa-grover** [comment]
@Melo5154 Any update on this ?

**Comment by ashwini0529** [comment]
In author, What name should come?

**Comment by GramescuDan** [comment]
Gramescu dan

**Comment by jigyasa-grover** [comment]
Thanks :)

Modified via commit https://github.com/fossasia/gci16.fossasia.org/commit/6cd8f91591fd034a155a1726b4f6ade358ff6d07

**Pull request closed without merging**
