### PR TITLE
Added Deepraj Pandey to the Students' Section

### PR DESCRIPTION
**Pull request by DeeprajPandey**
Add files via upload

### CODE REVIEW

**Comment by shubham-padia** [comment]
Good job!!

**Comment by hemantjadon** [comment]
Task link please (if completed all parts) so that we can approve.

**Comment by DeeprajPandey** [comment]
@hemantjadon Here's the link. :)
https://codein.withgoogle.com/dashboard/task-instances/5821027697295360/

**Comment by DeeprajPandey** [comment]
Thank you @shubham-padia for merging the code. :)

**Comment by abishekvashok** [comment]
Well done @DeeprajPandey

**Comment by hemantjadon** [comment]
@DeeprajPandey Please complete the other parts of task also :)

**Comment by DeeprajPandey** [comment]
@hemantjadon I think I have completed other parts of the task.

**Comment by DeeprajPandey** [comment]
@hemantjadon sent you all the screenshots via the codein platform.

**Pull request merged**
