### PR TITLE
Fix fossasia/gci16.fossasia.org#213

### PR DESCRIPTION
**Pull request by niccokunzmann**
I added a link to the maintainers so new developers know about this.

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@niccokunzmann Merge conflicts 😅

**Comment by niccokunzmann** [comment]
Uh, how could that happen^^
Is my PR up to all the formalities, you like to see? Do not exclude me from your improvement suggestions, I would like to hear them and improve, too.

**Comment by jigyasa-grover** [comment]
@niccokunzmann The conflicts were due to others adding stuff on the same line, rebasing did the trick.
Also, the build failure was due to trailing white-spaces.

```
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
|----|    | /app/CONTRIBUTING.md
|    |++++| /app/CONTRIBUTING.md
|  38|  38| * [Changing a commit message](https://help.github.com/articles/changing-a-commit-message/)
|  39|  39| 
|  40|  40| ### Merge Commits
|  41|    |-* [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) 
|    |  41|+* [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4)
|  42|  42| 
|  43|  43| ### Squash Commits
|  44|  44| * [Git Rebase (squash last commit)](https://www.youtube.com/watch?v=qh9KtjfjzCU)
[INFO][17:24:49] Applied 'ShowPatchAction' on 'CONTRIBUTING.md' from 'SpaceConsistencyBear'.
Executing section html...
```

**Comment by niccokunzmann** [comment]
@jig08, Ah, Now, I can see.. `- Trailing whitespaces.` Thanks for the explanation.

**Pull request merged**
