### PR TITLE
Added myself to students

### PR DESCRIPTION
**Pull request by vivekkumarsvm**

### CODE REVIEW

**Comment by vivekkumarsvm** [comment]
vivekkumarsvm.github.io/gci16.fossasia.org/

**Comment by animeshsinghweb** [comment]
@vivekkumarsvm You are requested to use your DP of 240x240px wide, please refer README.md

**Comment by vivekkumarsvm** [comment]
Resized image, what is the problem now?

**Comment by Elgayar** [comment]
@vivekkumarsvm Great! Good job, before I merge can you fix percy's issue?

**Comment by vivekkumarsvm** [comment]
@elgayar Can you tell me why I'm getting this error, I have resized the image 240x240px. I can't see any logs to get some idea about the error.

**Pull request merged**
