### PR TITLE
Added Princu7's latitude and longitude

### PR DESCRIPTION
**Pull request by Princu7**

### CODE REVIEW

**Comment by abishekvashok** [comment]
@Princu7 nice work sir, did you use the lattitude longitude locator (https://gci16.fossasia.org/geo), no probs if you have not though!

**Comment by Princu7** [comment]
@Abhi2424shek No need to call me Sir. You know why :smile:. Yeah, I used your tool. This was the best accuracy which I could get from it. Let's hope other mentors will add their details soon.

**Comment by abishekvashok** [comment]
@Princu7 sorry for that, I know it why and it's not my tool it's our tool, I builded it for the community :) 😄

**Comment by Princu7** [comment]
Yeah. That's the spirit. Thanks for the correction.

**Comment by abishekvashok** [comment]
sure :) but we have an issue #528

**Comment by BrainBuzzer** [comment]
Those coordinates are completely insufficient. I recommend getting it from google maps while navigating through your city. Please update them. Those coordinates are so insufficient that it covers almost 1% of the map while coordinate is supposed to be to the point.

**Comment by abishekvashok** [comment]
@BrainBuzzer there are several occassions please take a look at this, thee may be point values but he got a perfect one that's why you think like that and as per the GPS standard only a point of distance :
See the image of @Princu7 :

Zoomed in:
image

Zoomed out:
image

It's because the markers are big in size bro and nothing is wrong about his lattitudes not longitudes.

**Pull request merged**
