### PR TITLE
Adding info in _data/students.yml and photo in images/students

### PR DESCRIPTION
**Pull request by Jerry2001**

### CODE REVIEW

**Comment by Princu7** [comment]
@Jerry2001 Thanks for the request. Please include the following things in your PR

* A link to your task description which you are solving through this issue. Also, post a link to your live gh-pages for faster and easier reviewing.

* Squash the commits into one and give it a declarative name like "Update photo and info". If you are not sure about squashing the commits, you can refer to the contributing guide of this project.
https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md

* Look into the details of the Travis build and see why it is failing. There might be some space inconsistencies or trailing whitespaces in your code which might cause the build to fail.

**Review by Princu7 — CHANGES_REQUESTED** [review]
Please do the mentioned things. If you face any difficulty, you can ask us here or in the chat channel

**Comment by abishekvashok** [comment]
See the tutorials in readme.md for squashing commits

**Comment by Jerry2001** [comment]
Sorry, I'm messing thing up :< I'm new to Git Hub and I don't know what is wrong with my code? :<

**Comment by Jerry2001** [comment]
Sorry sir but i can't find the tutorials in readme.md for squashing commits. Is it in this page? https://github.com/fossasia/gci16.fossasia.org

**Comment by Jerry2001** [comment]
Here is my gh page https://github.com/Jerry2001/gci16.fossasia.org/tree/gh-pages/_data and https://github.com/Jerry2001/gci16.fossasia.org/tree/gh-pages/images/students
My task https://codein.withgoogle.com/dashboard/task-instances/6157869835616256/

**Comment by Jerry2001** [comment]
I'm screwed up :<

**Comment by abishekvashok** [comment]
no your'nt

**Comment by abishekvashok** [comment]
run `git rebase -i HEAD~8` on git terminal.

**Comment by Jerry2001** [comment]
Forgive me but can you tell me a little bit more clearly ? :< I'm type that on Git Bash and it said "fatal: Not a git repository (or any of the parent directories): .git" I'm completely new to git hub

**Comment by hemantjadon** [comment]
Hi @Jerry2001 

We all are here to learn something new each day, so just relax you will definitely me able to squash the commits.

Firstly 
> "fatal: Not a git repository (or any of the parent directories): .git"

This occurs when there is you are not in the correct folder, please use `cd` command to go to appropriate directory(folder).

once you reach the destined folder where all the code of `gci16.fossasia.org`, then follow the tutorials mentioned in [contributing.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md#tutorials) for squashing the commits.

Also there is an automatic tester `travis.ci` set up on this repository. Which is showing some errors.
Please check for the `build log` by clicking "Details" button below (There is a red cross saying "All checks have failed").

If you need any help you can ask here or it will be much more better and helpful if you join "#gci" channel at `slack`.Please refer to this [Finding Suppport](https://github.com/fossasia/gci16.fossasia.org#finding-support)
Cheers :)

**Comment by niccokunzmann** [comment]
I am closing this because of #313. You can re-open it if you like.

**Pull request closed without merging**
