### PR TITLE
Optimize images for shrinkray-917a1baf-4776-4793-8ed0-dcfefcc094b9

### PR DESCRIPTION
**Pull request by gaeun**

### CODE REVIEW

**Comment by gaeun** [comment]
Images shrunk 11.47% (263376b -> 233171b)


* images/students/dewansh.jpg (4542b -> 4156b)
* images/students/mukund.jpg (11283b -> 11093b)
* images/students/Guneet.jpg (7730b -> 7350b)
* images/blogs/ankit.jpg (51163b -> 44897b)
* images/blogs/default.jpg (57019b -> 52877b)
* images/blogs/sanchit.jpg (98984b -> 95220b)
* images/mentors/agatakowalska.jpg (8673b -> 5172b)
* images/mentors/ajinkya.jpg (18374b -> 7258b)
* images/mentors/aviaryan.jpg (5608b -> 5148b)

**Comment by gaeun** [comment]
Images shrunk 13.6% (155559b -> 134414b)


* images/students/AKostiv.jpg (5702b -> 5684b)
* images/students/abishek.jpg (5053b -> 5035b)
* images/students/adarsh.jpg (9787b -> 9769b)
* images/students/aryan.jpg (5683b -> 5665b)
* images/students/david.jpg (13347b -> 13329b)
* images/students/mehant.jpg (5795b -> 5777b)
* images/students/pol.jpg (12655b -> 12637b)
* images/students/shreyas.jpg (7697b -> 7679b)
* images/students/thien.jpg (7178b -> 7160b)
* images/blogs/animeshsinghweb.jpg (82662b -> 61679b)

**Comment by gaeun** [comment]
Images shrunk 32.58% (156806b -> 105727b)


* images/students/manraj.jpg (6481b -> 5576b)
* images/students/tushar.jpg (18589b -> 17992b)
* images/students/Phuc.jpg (15855b -> 14868b)
* images/students/Baidya.jpg (20852b -> 20276b)
* images/students/Prabhdeep.jpg (38250b -> 13747b)
* images/students/nadunyashmika.jpg (37577b -> 14120b)
* images/mentors/hemantjadon.jpg (6151b -> 6133b)
* images/mentors/mariobehling.jpg (6265b -> 6247b)
* images/mentors/saptaks.jpg (6786b -> 6768b)

**Comment by gaeun** [comment]
Images shrunk 31.18% (335614b -> 230973b)


* images/students/aditya.jpg (10323b -> 10305b)
* images/blogs/pranavblog.jpg (33500b -> 33482b)
* images/mentors/dishantkhanna.jpg (11910b -> 11892b)
* images/students/hmc.jpg (13015b -> 12575b)
* images/students/mattpdl.jpg (68550b -> 40478b)
* images/students/Abhijeet.jpg (66980b -> 40518b)
* images/students/Vishalsingh.jpg (33851b -> 18464b)
* images/students/pranav1.jpg (39229b -> 23178b)
* images/students/vivek.jpg (58256b -> 40081b)

**Comment by gaeun** [comment]
Images shrunk 31.9% (88955b -> 60581b)


* images/students/JQ.jpg (12398b -> 3075b)
* images/students/joseph.jpg (20344b -> 10090b)
* images/students/kohyt.jpg (14236b -> 10038b)
* images/students/peircechow.jpg (13648b -> 9467b)
* images/students/samuelchua.jpg (7086b -> 7068b)
* images/students/prajwal.jpg (4963b -> 4961b)
* images/blogs/Guneet.jpg (7730b -> 7350b)
* images/students/zahari.jpg (8550b -> 8532b)

**Comment by gaeun** [comment]
Images shrunk 63.72% (152841b -> 55455b)


* images/students/darshil.jpg (5730b -> 5378b)
* images/students/gaeun.jpg (14207b -> 4278b)
* images/students/gautam.jpg (18584b -> 7137b)
* images/students/kartikeya.jpg (23572b -> 2369b)
* images/students/leecaregene.jpg (14057b -> 4283b)
* images/students/mrgeorgeous.jpg (17765b -> 6591b)
* images/students/ncdai.jpg (13315b -> 3870b)
* images/students/oanarosca.jpg (5777b -> 5432b)
* images/students/sanchit.jpg (22666b -> 9798b)
* images/students/tinhdao.jpg (17168b -> 6319b)

**Comment by gaeun** [comment]
Images shrunk 60.1% (161948b -> 64633b)


* images/mentors/yathannsh.jpg (16185b -> 5587b)
* images/students/Gayar.jpg (15644b -> 5118b)
* images/students/Sa.jpg (13207b -> 3663b)
* images/students/Witus.jpg (19003b -> 7606b)
* images/students/aditodorova.jpg (17403b -> 6359b)
* images/students/ainesh.jpg (16064b -> 5534b)
* images/students/animeshsinghweb.jpg (17959b -> 9199b)
* images/students/ankit.jpg (12253b -> 8864b)
* images/students/arpna.jpg (20003b -> 8256b)
* images/students/bnguyenltt.jpg (14227b -> 4447b)

**Comment by gaeun** [comment]
Images shrunk 26.4% (267932b -> 197221b)


* images/students/victoriajuan.JPG (22699b -> 10073b)
* images/students/will.jpg (17028b -> 6011b)
* images/students/zehata.jpg (14776b -> 4667b)
* images/students/Muktiadi.jpg (33739b -> 17013b)
* images/students/manas.jpg (49021b -> 48456b)
* images/students/benjaminguo.jpg (6562b -> 5985b)
* images/students/kshitij.jpg (8312b -> 7468b)
* images/mentors/sudheesh001.jpg (56041b -> 38253b)
* images/students/EKumar.jpg (9956b -> 9515b)
* images/students/galangkangin.jpg (49798b -> 49780b)

**Comment by gaeun** [comment]
Images shrunk 21.4% (175977b -> 138324b)


* images/students/badami.jpg (40881b -> 39172b)
* images/students/Mridul.jpg (17585b -> 16658b)
* images/students/Shrey.jpg (32807b -> 28330b)
* images/students/Aditya240.jpg (19952b -> 11724b)
* images/mentors/jayvdb.jpg (31826b -> 31808b)
* images/students/KohPR.jpg (32926b -> 10632b)

**Comment by gaeun** [comment]
Images shrunk 60.36% (182657b -> 72422b)


* images/mentors/daminisatya.jpg (22548b -> 9914b)
* images/mentors/harshvardhan.jpg (19056b -> 9544b)
* images/mentors/hpdang.jpg (19755b -> 8121b)
* images/mentors/jgrover.jpg (26256b -> 12470b)
* images/mentors/kamishettysreeja.jpg (12916b -> 3596b)
* images/mentors/louisgagnon.jpg (16929b -> 6097b)
* images/mentors/nghoangphu.jpg (16329b -> 5647b)
* images/mentors/princu7.jpg (16373b -> 5693b)
* images/mentors/robby.jpg (17672b -> 6578b)
* images/mentors/shiven.jpg (14823b -> 4762b)

**Comment by gaeun** [comment]
Images shrunk 3.03% (2381521b -> 2309577b)


* images/students/Pandey_Deepraj.jpg (9163b -> 9145b)
* images/image_slider_crowd.jpg (1050986b -> 1047776b)
* images/image_slider_machine.jpg (461960b -> 458750b)
* images/image_slider_fossasia.jpg (713013b -> 709803b)
* images/students/TanNgoMinh.jpg (59910b -> 35398b)
* images/students/nikhil_chandak.jpg (64365b -> 37542b)
* images/students/SrijanJha.jpg (5687b -> 5372b)
* images/mentors/shubham-padia.jpg (16437b -> 5791b)

**Comment by gaeun** [comment]
Images shrunk 30.36% (113561b -> 79090b)


* images/students/AlejandroHeredia.jpg (10695b -> 3460b)
* images/students/Simon_Narang.jpg (16177b -> 5559b)
* images/students/cagriari_avatar.jpg (14588b -> 4565b)
* images/students/yashvardhan_sharma.jpg (10365b -> 8731b)
* images/students/ShiWeiZheng.jpg (9388b -> 8965b)
* images/mentors/rsz_praveen.jpg (20714b -> 17616b)
* images/students/prince-john.jpg (10633b -> 9622b)
* images/mentors/JasonWong.jpg (10457b -> 10039b)
* images/students/Hesham-Burawi.jpeg (10544b -> 10533b)

**Comment by m1guelpf** [comment]
@gaeun Can this be merged?

**Comment by gaeun** [comment]
Images shrunk 6.76% (199686b -> 186206b)


* images/logos/alexandru.png (21193b -> 15735b)
* images/logos/prabhdeep.png (43993b -> 39916b)
* images/logos/dannymout.png (16987b -> 16807b)
* images/logos/MBDyn1.png (15859b -> 15174b)
* images/logos/MBDyn2.png (17059b -> 16569b)
* images/logos/MBDyn3.png (16998b -> 16617b)
* images/logos/MBDyn5.png (11269b -> 10340b)
* images/logos/logo.png (17405b -> 17203b)
* images/logos/logo1.png (16634b -> 16220b)
* images/logos/mbdyn4.png (22289b -> 21625b)

**Comment by gaeun** [comment]
Images shrunk 7.24% (102868b -> 95430b)


* images/logos/nguyenchanhdai.png (13245b -> 13240b)
* images/projects/activity.png (2779b -> 2564b)
* images/blogs/Blog.png (39513b -> 39275b)
* images/logos/MBDyn6.png (15146b -> 10452b)
* images/students/m1guelpiedrafita.png (12371b -> 10776b)
* images/mentors/member.png (387b -> 369b)
* images/projects/hangman.png (15090b -> 14585b)
* images/ribbon.png (4337b -> 4169b)

**Comment by gaeun** [comment]
Images shrunk 12.43% (255667b -> 223905b)


* images/students/isabellaberry.png (11424b -> 8204b)
* images/students/rileykova.png (11524b -> 8062b)
* images/students/shivam.png (8681b -> 8485b)
* images/students/xuanquang.png (12089b -> 8623b)
* images/logos/MBDyn-animeshsinghweb.png (14826b -> 14729b)
* images/logos/alexandru_nasta.png (67574b -> 57905b)
* images/logos/prabhdeep_singh.png (129549b -> 117897b)

**Pull request merged**
