### PR TITLE
adding myself to the students section

### PR DESCRIPTION
**Pull request by mukundchoudhary28**

### CODE REVIEW

**Comment by abishekvashok** [comment]
@mukundch28 hey hacker, nice to see you here good work but we have conflicts do you know to resolve them?

**Comment by animeshsinghweb** [comment]
@mukundch28 are you having any problems solving Merge Conflicts?
You can refer **Contributions.md** or let me know.

**Comment by animeshsinghweb** [comment]
@mukundch28 Still there are merge conflicts.

**Comment by m1guelpf** [comment]
@mukundch28 LGTM

**Pull request merged**
