### PR TITLE
Added image and student info

### PR DESCRIPTION
**Pull request by S-ulphuric**

### CODE REVIEW

**Review by daminisatya — COMMENTED** [review]
Merge conflicts :) 

Here's a video to help you resolve this. 
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by S-ulphuric** [comment]
I can't really recognize what's the conflict.
Please! Can you tell me what can I do to resolve this conflict?

**Comment by S-ulphuric** [comment]
I can't really recognize what's the conflict.
Please! Can you tell me what can I do to resolve this conflict?

**Comment by S-ulphuric** [comment]
I can't really recognize what's the conflict.
Please! Can you tell me what can I do to resolve this conflict?

**Comment by SaptakS** [comment]
@S-ulphuric did you try out as shown in the video?? Join the slack or IRC channel and if you still have problem, we can fix it there.

**Pull request closed without merging**
