### PR TITLE
Resolves #130

### LINKED ISSUE #130: Problem with Student Section
There is a minor problem with student section.
http://prntscr.com/dettek
If the name of the student comes in two lines you can see that the icons go out of the white box.Hope someone can fix it

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixed line spacing errors, see the preview:
image

Please review and merge @hemantjadon @jig08 

Further onclick gives a box (Bootstrap model) see here: [http://abhi2424shek.github.io/gci16.fossasia.org]( http://abhi2424shek.github.io/gci16.fossasia.org)

[Click works only after full page is loaded due to bootstrap and js code backends]

### CODE REVIEW

**Comment by hemantjadon** [comment]
@jig08  Should we clip off the name of the student? Your views please.

If we are clipping the name we should make done enhancement like on hover the card flips and complete name comes on back side. I have not thought about this much, I guess there can be a solution.

**Comment by abishekvashok** [comment]
Yes i would add it now....

**Comment by jigyasa-grover** [comment]
>If we are clipping the name we should make done enhancement like on hover the card flips and complete name comes on back side. I have not thought about this much, I guess there can be a solution.

@hemantjadon Seems like a nice idea.

**Comment by abishekvashok** [comment]
I would do rather it onClick() what is your views

**Comment by hemantjadon** [comment]
Onclick seems a better solution

**Comment by abishekvashok** [comment]
@hemantjadon please review and merge.

**Comment by hemantjadon** [comment]
@Abhi2424shek please check for the failing build :)
also please specify the demo link

**Comment by abishekvashok** [comment]
Preview link is in the first post, let me resolve the build sir

**Comment by abishekvashok** [comment]
Wait I got something more better will start a new PR, keep clam and expect me.

**Pull request closed without merging**
