### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by AlexTurning**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Add a screenshot and/or live link to demo what you did..

**Comment by robbyoconnor** [comment]
Also what issue are you fixing? NO infornation is given here.

**Comment by robbyoconnor** [comment]
I am closing this as it doesn't look good AT ALL.

**Comment by robbyoconnor** [comment]
There is a reason it is the way it is. This isn't a bug. it looks HORRIBLE when text overflows outside of where you want it to be.

**Comment by robbyoconnor** [comment]
Also @AlexTurning in the future -- add an actual description to your pull requests and have a logical reason explained as to WHY you did it -- because what you added made the design _WORSE_ -- and that's not good.

**Comment by AlexTurning** [comment]
but i had added the auto scroll property--if text is large it won't overflow rather a scroll bar will appear to see the whole text
http://imgur.com/a/8GrCL

**Comment by robbyoconnor** [comment]
No. This is bad.

**Comment by AlexTurning** [comment]
ok. will work better

**Comment by robbyoconnor** [comment]
This was actually done recently.

**Comment by robbyoconnor** [comment]
There are PLENTY of other issues. You're grasping here.

**Pull request closed without merging**
