### PR TITLE
#465 issue point 10 fixing

### PR DESCRIPTION
**Pull request by kartikhsr**
#465 issue point 10 fixing
https://kartikhsr.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@kartikhsr Too much commits, please learn squashing.
Also please do provide live GH-Page link as I had said earlier.

**Comment by kartikhsr** [comment]
@ankitrgadiya @animeshsinghweb we need to resolve padding-left , padding - right issue
@animeshsinghweb okkay , i will check squashing
live link : https://kartikhsr.github.io/gci16.fossasia.org/

**Comment by kartikhsr** [comment]
@animeshsinghweb i have solved the bit issue of padding left, padding right .....  how shall i commit them now ? 
https://kartikhsr.github.io/gci16.fossasia.org/
shall i use squashing?

**Comment by abishekvashok** [comment]
@kartikhsr open a new PR.

**Pull request merged**
