### PR TITLE
Added image and credentials

### PR DESCRIPTION
**Pull request by oanarosca**

### CODE REVIEW

**Review by SaptakS — APPROVED** [review]

**Comment by ajinkya007** [comment]
@SaptakS : The folder hierarchy for the students.yml is not maintained in accordance with the project structure. PR #11 has merge conflicts with this one. Please do have a look at it.

**Comment by SaptakS** [comment]
@ajinkya007 PR #11 has already been merged. And I realised later that this PR was not following the hierarchy but PR #11 fixes it.

**Comment by ajinkya007** [comment]
@SaptakS : The student details from the student.yml are lost for oanarosca

**Comment by SaptakS** [comment]
@ajinkya007 Nopes. They are [there](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/_data/students.yml#L3)

**Comment by mariobehling** [comment]
Just to reconfirm. The desired outcome of the task is to show the student images on the website. Currently there are no images on the page http://gci16.fossasia.org yet. So, let's progress on this. Cheers.

**Pull request merged**
