### PR TITLE
Added Dwij in Student's section and Dwij's blog

### PR DESCRIPTION
**Pull request by codein-dwij**
I have updated the student and blog section :) Updating the blog section
was my codein task
Link to my repository :
https://github.com/codein-dwij/gci16.fossasia.org
GCI Task Link :
https://codein.withgoogle.com/dashboard/task-instances/4638328720719872/
Link to live gh-pages : https://codein-dwij.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by hemantjadon** [comment]
@codein-dwij Please see for the failing build
https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181355847

**Review by jigyasa-grover — COMMENTED** [review]
Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"

**Comment by jigyasa-grover** [comment]
@codein-dwij Great, you finally resolved the build errors :)

**Comment by codein-dwij** [comment]
Yeah

**Comment by codein-dwij** [comment]
You merged it so I don't need to squash the commits now?

**Comment by hemantjadon** [comment]
@codein-dwij no it's done :)
Cheers :)
Keep Coding :)

**Pull request merged**
