### PR TITLE
have done all I could 

### PR DESCRIPTION
**Pull request by itsguneetsingh**
I have read all the comments and did as far I knew about Github. Thanks to everyone who told about  my mistakes And sorry @checkbot I don't know what a live link is

### CODE REVIEW

**Comment by itsguneetsingh** [comment]
I don't know what a live link is

**Comment by niccokunzmann** [comment]
@Guneetconvent2002 Cool. A question: the image is quite big which leads to longer load times of the page and the repository.
Do you want to resize the image to 240x240px as the other images are, too? What are your thoughts?

**Comment by niccokunzmann** [comment]
The live link is: http://Guneetconvent2002.github.io/gci16.fossasia.org

**Comment by itsguneetsingh** [comment]
the problem is that my faces' image also doesn't fit in 240x240px

**Comment by niccokunzmann** [comment]
I see. Can you use this image? 
image

**Comment by itsguneetsingh** [comment]
yeah sure

**Comment by niccokunzmann** [comment]
You do not need to close this. You can edit the git-branch by pushing a new commit.

**Pull request closed without merging**
