### PR TITLE
#545 , #465 point 13 issue resolved #554

### LINKED ISSUE #545: Resize Picture "images/students/zahari.jpg"
The picture [images/students/zahari.jpg](https://raw.githubusercontent.com/fossasia/gci16.fossasia.org/0965c0e8e430d77397067dd0718769db6d65ccff/images/students/zahari.jpg) is skewed.
We can resize it, so it is in the 240x240 dimensions.

### LINKED ISSUE #554: Problem with bio of some student/s
There are some students who have kept a lengthy bio! 
screenshot_3
This should be fixed :)
If anyone wants to work on this issue please tell!

### PR DESCRIPTION
**Pull request by kartikhsr**
Resolved #545 and #465 #554 point 13 issue 
https://kartikhsr.github.io/gci16.fossasia.org/ live link
@codein-dwij @animeshsinghweb @rhemon

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@kartikhsr Please checkout this, it still have some issues I guess: https://github.com/fossasia/gci16.fossasia.org/issues/554#issuecomment-267340237

**Comment by animeshsinghweb** [comment]
@kartikhsr Can you remove 'container' from 'footer' class?
It would cause some issues with Travis, and also conflict with #555

**Comment by kartikhsr** [comment]
@animeshsinghweb oops haan i removed it, shall i add it again and then commit, or you had done it?

**Comment by animeshsinghweb** [comment]
@kartikhsr When you resolve an issue please make sure at that particular PR you just push the branch which resolves that issue. It becomes easier for maintainer and admin to catch up commits and revert if any problems, and more importantly to be organized.
If you want to do some other changes, you can request another PR for that, but all changes with just 1 fix is unfair.

You can remove them out, do just what you need to do with issues and then recommit or rather `-amend` and `push` them up.

**Pull request closed without merging**
