### PR TITLE
Added details and profile picture to website

### PR DESCRIPTION
**Pull request by goelsnigdha**
I have made the required code changes and further request for those changes to be merged with the repository.

### CODE REVIEW

**Comment by hemantjadon** [comment]
@goelsnigdha According to the task you also have to add your profile pic in the student section of the gci17 website.

Please add that so we can move forward.

**Comment by goelsnigdha** [comment]
As in upload the picture and add the code, right?

**Comment by hemantjadon** [comment]
Yup only these two things. :)

**Comment by goelsnigdha** [comment]
I seem to have made these changes. Please review

**Comment by hemantjadon** [comment]
@goelsnigdha 
Sorry but I am only able to see that you have added your pic and details in yml file.

What required is that your profile pic should appear on the gci17 site so add the appropriate code in `index.html` If you have any doubt ask anyone at `fossasia.slack.com` at `#gci` channel.

**Comment by goelsnigdha** [comment]
Done the needful. Please check the same.

**Comment by hemantjadon** [comment]
Merge conflicts here.

* Please provide the link to the gh-pages of your fork

* Also the link to your task

**Comment by goelsnigdha** [comment]
Task: https://codein.withgoogle.com/tasks/5741070096793600/?sp-organization=6707477701722112&sp-is_beginner=True

gh-page: https://github.com/goelsnigdha/gci16.fossasia.org-1/blob/gh-pages/_data/students.yml

**Comment by hemantjadon** [comment]
@goelsnigdha
No not the link to `students.yml` file but gh-pages deployed site of your fork

**Review by tradzik — CHANGES_REQUESTED** [review]
Commits need to be [squashed](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before merged. Please fix also merge conflicts. Thanks.

**Comment by hemantjadon** [comment]
@goelsnigdha 
Please fix the merge conflicts.
Also provide the link to live "gh-pages".

**Comment by jigyasa-grover** [comment]
@goelsnigdha 

As @tradzik  & @hemantjadon pointed, pls do the following:

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Comment by jigyasa-grover** [comment]
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
