### PR TITLE
Added the Github issues section

### PR DESCRIPTION
**Pull request by Jantje19**
I've added the Github issues section. I hope it's what you expected.

I think I fixed the Travis build.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can u post the link for the administrative for a review

**Comment by Jantje19** [comment]
Do you mean [this](https://codein.withgoogle.com/tasks/6586215379763200/) link?

**Comment by niccokunzmann** [comment]
The travis build failed, see below.

**Comment by abishekvashok** [comment]
There are space inconsistency errors

**Comment by oanarosca** [comment]
When we mean the link, we mean the link to your gh-pages from your forked repository, or a screenshot showing the result of your changes. In this case, the link we're looking for is [this one](https://Jantje19.github.io/gci16.fossasia.org). Keep that in mind and don't forget to add it to every pull request you make!

**Comment by niccokunzmann** [comment]
@Jantje19 Can you resolve the merge conflicts?
Also, is it ok, if we merge first and then we show you how to remove the errors?

I did not understand them until jig08 told me.

Most is called "Trailing whitespaces" https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181373794#L384
```
|  20|    |-- reject pull-requests: <----- here is a space at the end of the line
|    |  20|+- reject pull-requests:
```

SpaceConsistencyBear - all items must be aligned at the same number of spaces
```
|   6|    |-	font-size: 10px;
|    |   6|+    font-size: 10px;
```

If you think that some of these errors are useless, please create an issue so we can remove them.

**Comment by niccokunzmann** [comment]
I saw your push :) looks good to me.

**Comment by Jantje19** [comment]
Did Travis work?

**Comment by niccokunzmann** [comment]
I do not know if travis worked. Usually it shows up here, but there is nothing:
capture

**Comment by niccokunzmann** [comment]
What do you think? Can you resolve the merge conflict?
This is hard if you only use the web interface. What do you use? Github Desktop or the git shell?

**Comment by Jantje19** [comment]
I don't like github desktop, and I don't know all the terminal commands. So I use the webversion

**Comment by niccokunzmann** [comment]
Have a look here: https://try.github.io/
It could last an hour of your time.
Or you can implement one more hour and upload files and we do not merge them.

**Comment by Jantje19** [comment]
Ok, will try

**Comment by Jantje19** [comment]
I really don't know how to do that, I've looked all across the internet but I can't find it. Please help.

**Comment by Jantje19** [comment]
I can't figure out the conflict

**Comment by niccokunzmann** [comment]
You can only resolve the conflict in the command line or github desktop. You can not change a file to have no conflict. In the contributing.md file, there are tutorials. You can provide us with screenshots, if you get stuck.

**Comment by niccokunzmann** [comment]
Todo:

1. merge
2. squash

**Comment by Jantje19** [comment]
Ok, thnx for the help

**Comment by kaine119** [comment]
*Admins: I'm coming from [this task](https://codein.withgoogle.com/dashboard/task-instances/4901061976391680/)*

@Jantje19: I'd like to enhance the issues section you've added, as well as help fix any merge conflicts. Perhaps we could work on your fork?

**Comment by m1guelpf** [comment]
@Jantje19 You can solve merge conflicts using Github web from [this](https://github.com/fossasia/gci16.fossasia.org/pull/216/conflicts) link.

**Comment by niccokunzmann** [comment]
@kaine119 You can work based on @Jantje19's work.
capture

it does not need to be merged for this. If you do this, you can help and resolve the conflicts.
Also, @Jantje19 can give you access to the repository (in the settings) and you both can work together on this.
let me know, if you need help :)

**Comment by niccokunzmann** [comment]
@Jantje19 Now, the whole file is different I can not really help because I do not know what is important.
Do you still know what the most important commits are?
Then, you can create a new pull-request and use `git cherry-pick`

like this for the first commit:
`git cherry-pick ba20a03`

Also, I can do this but then, tell me, which commits are the most important ones.

**Comment by abishekvashok** [comment]
well @niccokunzmann I can see an issues section already there. I think we will let her make it more interesting in a new PR.

**Comment by kaine119** [comment]
@Abhi2424shek: are you referring to me? b/c I'm a dude.

Shall I create another PR?

**Comment by abishekvashok** [comment]
Bro @kaine119 i referred to @Jantje19 , but you may work on any issues in this repo

**Comment by kaine119** [comment]
@Abhi2424shek oh, sorry about that. I'll create a PR to work on the latest issues section.

**Comment by abishekvashok** [comment]
@kaine119 sure go ahead

**Comment by jigyasa-grover** [comment]
>I'll create a PR to work on the latest issues section.

Closing this then.

**Pull request closed without merging**
