### PR TITLE
Adding info for student section

### PR DESCRIPTION
**Pull request by S-ulphuric**

### CODE REVIEW

**Review by daminisatya — APPROVED** [review]
Good job

**Comment by S-ulphuric** [comment]
At Last!
Thank You!

**Comment by hvardhanx** [comment]
@S-ulphuric You have added the image in the wrong place. Please add it in the `images/` folder. Cheers.

**Comment by S-ulphuric** [comment]
That was a silly mistake. But, Thanks for the heads up!

**Pull request merged**
