### PR TITLE
created adaptive slider

### PR DESCRIPTION
**Pull request by ghost**
improved top slider by aded ability to adapt to tablet or mobile phones sizes

### CODE REVIEW

**Comment by ghost** [comment]
https://nolik2000.github.io/gci16.fossasia.org/

**Comment by niccokunzmann** [comment]
Task: https://codein.withgoogle.com/dashboard/task-instances/5113924347232256/

**Comment by niccokunzmann** [comment]
The previous pull-request is #229. Can we close #229?

**Comment by niccokunzmann** [comment]
@nolik2000 I see, you are putting a lot of work into this. Please help me understand one thing so I can merge: Can you add the existing slider information to your slider?
Deleting the existing one will remove work from other students like you, who created a slider.

**Comment by mariobehling** [comment]
@nolik2000 Hi, this repository has an automated test to ensure the website works. Right now this test (travis test) is failing. Please click on the "Details" button for more info. Could you check, please?

**Review by daminisatya — CHANGES_REQUESTED** [review]
Address the changes.

**Comment by ghost** [comment]
I don't understand why checks failed(((

**Comment by niccokunzmann** [comment]
The tests want to have a newline at the end of the file. https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181761949#L403

If you solve issue #235, you may remove this error for a lot of people. Maybe, we can also disable the tests for some files which are these small JavaScript files. It makes no sense to test them.

**Comment by jigyasa-grover** [comment]
With reference to [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
