### PR TITLE
H2 issue #506

### PR DESCRIPTION
**Pull request by animeshsinghweb**
Also fixed few bugs over social media section like proper grid
for .yt and .blog-sec images hover effects and added link to the
images.

Refer the issue #506 
My GH page: https://animeshsinghweb.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by hoangvanthien** [comment]
I love this new style! 👍

**Comment by animeshsinghweb** [comment]
@hoangvanthien  Thanks mate. 👍 
There's some more modification coming in it, I'm glad you liked it.
It was a modified version of @ankitrgadiya New design PR. :)

**Comment by hoangvanthien** [comment]
However, there is a consequence. Could you please ensure that our menu item will also be highlighted as we scroll through the content?

**Comment by animeshsinghweb** [comment]
@hoangvanthien Great you pointed out, can you open a new issue on that, so we can work out accordingly. 👍

**Comment by hoangvanthien** [comment]
@animeshsinghweb Why didn't you squash commits before merging? Also next time do not merge your own PR.

**Comment by codein-dwij** [comment]
It seems he has squashed his commits @hoangvanthien

**Comment by animeshsinghweb** [comment]
@hoangvanthien It was **squashed** before merging as @codein-dwij said, here is the [PR commit merged](https://github.com/fossasia/gci16.fossasia.org/commit/568f11d58db74917a1935d8f1c2ed225d78827ec).
.
Ok, I wouldn't squash my own commit from this time, 👍

**Pull request merged**
