### PR TITLE
Uploaded an image and info of Bill Acha (FOSSASIA mentor)

### PR DESCRIPTION
**Pull request by ghost**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

Added Bill Acha's information to the mentors section and uploaded an (240x240) image to the mentor image files. live link: https://github.com/balderasdiana27/gci16.fossasia.org

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@balderasdiana27 Please resolve merge conflicts

**Comment by robbyoconnor** [comment]
@balderasdiana27 please read -- I told you how to mark them...Just leave the checkboxes and check them after you open the PR. You didn't do everything there. Please only check things you've actually done.

**Comment by robbyoconnor** [comment]
@balderasdiana27 this still has more changes than just adding Bill Acha...It's not mergable in its current state.

**Comment by robbyoconnor** [comment]
you still have not removed irrelevant changes. Please delete your fork, make changes, and open a new pull request

**Comment by ghost** [comment]
sorry i was offline

**Pull request closed without merging**
