### PR TITLE
PR for task: Add your photo to students section in FOSSASIA GCi website.

### PR DESCRIPTION
**Pull request by adityak1121**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- I have made a new PR because my image name was not correct in my credentials in students.yml, so I corrected my image name so that it can appear in the website, sorry for this mistake.

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
K looks good to me.

**Comment by abishekvashok** [comment]
Hey you are already in it.

**Comment by adityak1121** [comment]
I know that I am already in it but my image did not display in the website when I launch it on a browser, so I reviewed my credentials in students.yml and found that my image name was not correct in it, so corrected it, and send this New PR.

**Comment by robbyoconnor** [comment]
You resolved merge conflicts but also deleted all your changes. You want to keep your changes and tell git where to place them...

**Comment by robbyoconnor** [comment]
@adityak1121 -- You resolved merge conflicts but also deleted all your changes. You want to keep your changes and tell git where to place them...

**Comment by robbyoconnor** [comment]
Fixed it -- no need to do anything. Please be careful next time.

**Comment by robbyoconnor** [comment]
@fossasia/gci16-maintainers: Please check that images exist and if it doesn't either fix it or ask the student to do so. Optimistic merging gone wrong in this case.

**Comment by adityak1121** [comment]
Sorry, thank you!! :smile:

**Pull request closed without merging**
