### PR TITLE
Resolves #528, making mentors shown in the map

### LINKED ISSUE #528: Mentors are not showing up on the map!
@Princu7 you added it right but we can't see you in:
image
@BrainBuzzer any guesses bro

### PR DESCRIPTION
**Pull request by abishekvashok**
The mentors where not seen in the map but this should do all the needed
to pop them out.

Live preview: http://abhi2424shek.github.io/gci16.fossasia.org
image

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@Abhi2424shek I can't find the markers on your GH-Pages. Can your provide me with an image?

**Comment by abishekvashok** [comment]
@animeshsinghweb please wait bro...

**Comment by abishekvashok** [comment]
Done everything @fossasia/gci16-maintainers @Princu7 take a look at this now! @Princu7 @jig08 @robbyoconnor I salute you for adding your lat and lng values

**Comment by animeshsinghweb** [comment]
@Abhi2424shek Great work mate. :)

**Comment by abishekvashok** [comment]
@animeshsinghweb expect me always :)

**Comment by animeshsinghweb** [comment]
@Abhi2424shek hahaha! Sure as always. 👍

**Pull request merged**
