### PR TITLE
Adding the image of harshit dwivedi in the mentors section changed the extention from jpg to png

### PR DESCRIPTION
**Pull request by Srijanjha**
Changed the extention of the image harshit1.jpg to harshit1.png

### CODE REVIEW

**Comment by abishekvashok** [comment]
@SrijanJha28 please add some info in the PR body and also resolve the conflicts

**Comment by Srijanjha** [comment]
the conflicts page is not opening can you solve it for me

**Comment by abishekvashok** [comment]
@SrijanJha28 next time you gotta do it, learn to fetch from upstream by going to the contributing.md and find the merge conflicts resolving guides there

**Comment by Srijanjha** [comment]
ok thanks

**Comment by abishekvashok** [comment]
@SrijanJha28 I wont merge till you:

- provide a summary in the Pull Request description, containing, at less, your live link.
- Please add your live link or a preview screenshot to the PR body.

And if possible do the squashing work after checking the tutorials in the contributing.md file

**Comment by robbyoconnor** [comment]
I would recommend you install git on your system.

**Comment by Srijanjha** [comment]
yes i have it installed

**Comment by Srijanjha** [comment]
and what is a live link?

**Comment by robbyoconnor** [comment]
I'm actually gonna merge this -- I just looked at his site -- and it's broken right now. This bad merge is my fault. @SrijanJha28 -- **TEST YOUR WORK!**  -- not doing so will lead many projects to lose faith in the quality of your work.

**Pull request merged**
