### PR TITLE
Resolves #140 added image scale alert in readme file

### LINKED ISSUE #140: Find image quality and scale images.
Some student images are very big. This means a slow loading of the website.
Please

- find a good image size
- scale existing images
- Find a way to make new images scaled to the right size:
  - document somewhere where new images are added that there should be a certain size
  - ...?

### PR DESCRIPTION
**Pull request by abishekvashok**
Added an image_optimizer please review and merge @niccokunzmann

### CODE REVIEW

**Comment by abishekvashok** [comment]
Hah don't merge now let me make it responsive and solve a cross request problem

**Comment by abishekvashok** [comment]
I would also resolve the Travis build issues just give me some time

**Comment by abishekvashok** [comment]
Thats, all now please review @jig08 @hemantjadon @niccokunzmann . I just updated the readme.md, and that should do it, right?

**Comment by jigyasa-grover** [comment]
@hemantjadon @Abhi2424shek This PR just corrected the README ?🤔

**Comment by hemantjadon** [comment]
@jig08 There was a message general message to be added in Readme.md to ask students not to add too high-res photos while adding their information.

Do we have to revert ??

**Comment by jigyasa-grover** [comment]
@hemantjadon Not exactly, but just sometime before I saw an optimizer added in here too before the squashing and build fixing took place.
Is it @Abhi2424shek  ?

**Comment by abishekvashok** [comment]
@jig08 yes, I tried to do for an image compressor in javascript and html using an api but cross-orgin-requests in jekyll never came true. That's why I just had to limit this commit really short. if u all want me to make one I could do it with python, a python app, but that would require downloading...

**Comment by abishekvashok** [comment]
what's your opinion @hemantjadon should i make an optimizer in python?

**Comment by hemantjadon** [comment]
@jig08 I think we can have a separate issue regarding the addition of a separate optimiser and just add a readme for now 
What do you think ?

**Comment by jigyasa-grover** [comment]
Cool.

**Comment by abishekvashok** [comment]
k, I would give in a PR, in some time! Just wait @jig08 @hemantjadon

**Comment by hemantjadon** [comment]
@Abhi2424shek Open a relevent issue first.

**Comment by abishekvashok** [comment]
Sure, @hemantjadon

**Pull request merged**
