### PR TITLE
Fix the Thanks section's displaying issues

### LINKED ISSUE #647: Thankyou for contribution not displaying names correctly
screenshot_15
I don't know what that thing is! First the name should be appearing on the top and not below and second the thing should be placed in the Contributors box and not outside it!
If anyone wants to work on this please tell :)

### PR DESCRIPTION
**Pull request by hoangvanthien**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request (replace the text as instructed)

- Fix #647 
- Besides, there WAS another problem not mentioned: contributors section didn't display all people. It somehow stopped fetching.
screen shot 2016-12-29 at 16 48 04
- I removed `contributors.js` because it is more convenient to fetch contributors list ONCE in `main.js`.
- I changed the structure and CSS of the Thanks section (see in file changes) to adapt easier to diverse screen resolutions.

Comments: The simple solution for the #647 is adjusting `margin-top`. However, I found a really serious bug in `contributors.js` that variable `j` is not handled when it reaches the ending iterator of the array --> runtime error. Moreover, the JS code changing html content of `#name` **must not** be run in recursive function (i.e. while fetching the list). 

Live link: https://hoangvanthien.github.io
(Please compare the given link with the original GCI site in phone-size browser and desktop-size browser)

### CODE REVIEW

**Review by robbyoconnor — APPROVED** [review]
Looks good to me!

**Comment by robbyoconnor** [comment]
I'm gonna merge this!

**Comment by hoangvanthien** [comment]
Ah! I forgot because I had edited it several times! Should I squash your commit into mine?

**Comment by robbyoconnor** [comment]
No need.

**Comment by ankitrgadiya** [comment]
@hoangvanthien Perfect!, Thanks

**Pull request merged**
