### PR TITLE
please see the changes I have made and suggest me if anything else is to be done

### PR DESCRIPTION
**Pull request by ghost**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by ghost** [comment]
I got my mistakes, I'll resolve them.

**Comment by oanarosca** [comment]
Please check the boxes in the PR template. If you need help solving the merge conflicts, see the contributing.md file, or join our Slack channel for live help :)

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
I resolved merge conflicts however your photo needs to be `240x240` -- Read the directions closer.

**Comment by ghost** [comment]
@oanarosca I'm having trouble opening the website from my forked repository (to screenshot it) can you help?

**Comment by ghost** [comment]
@robbyoconnor Okay sir I'll change that

**Comment by oanarosca** [comment]
Your version of the website is at https://aneesh987.github.io/gci16.fossasia.org @aneesh987

**Comment by ghost** [comment]
@oanarosca sorry to bug you again and again, but i can't see my photo there. Is there any problem with what i have submitted?

**Comment by ghost** [comment]
screen shot 2017-01-15 at 4 34 13 pm
#this is the screenshot

**Comment by abishekvashok** [comment]
@aneesh987 you can bug us when ever you want as long as you are good, plus the thing you are looking at is the contributors section pls see the students section. You will appear in the contributors section after you have made at least 4 contributions (i.e, PRs merged).  Also to get the PR body updated pls.

**Review by abishekvashok — CHANGES_REQUESTED** [review]
your image name is not correct!

**Comment by robbyoconnor** [comment]
@aneesh987 rename your image please. Also resize it so it is 1:1 (`240x240` [w x h]).

**Comment by robbyoconnor** [comment]
This PR will be closed on January 16th at 1700 UTC. @aneesh987 fix this please.

**Comment by ghost** [comment]
I'm at school right now,i'll do it in a while

**Comment by robbyoconnor** [comment]
@aneesh987 no problem! Just do it before 16:59 UTC!

**Comment by ghost** [comment]
i've uploaded the image and corrected it's name. I would really like to thank all of you to take out time and help me with such an easy task i wasn't able to do(actually you guys did it). I hope to improve and come back to contribute to the fossasia organisation. Shout out to you all @robbyoconnor @Abhi2424shek @oanarosca

**Comment by oanarosca** [comment]
@aneesh987 no problem, we're here to help :) could you please put the image into `images/students` folder?

**Comment by ghost** [comment]
done @oanarosca

**Comment by oanarosca** [comment]
And remove the one from the root dir, you accidentally left it there.

**Comment by ghost** [comment]
👍

**Comment by oanarosca** [comment]
Good job!

**Comment by ghost** [comment]
I never learned this much so easily, when I opened Github for the first time, it was almost like horror, now it's all pleasant.Thanks again

**Pull request merged**
