### PR TITLE
Student Addition

### PR DESCRIPTION
**Pull request by DeeprajPandey**
Added Student Information (Deepraj Pandey)

### CODE REVIEW

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Too many commits for a small change, Please Squash

**Comment by DeeprajPandey** [comment]
You mean close pull request and reopen with fewer commits?

**Comment by hemantjadon** [comment]
@DeeprajPandey 
No, Definitely not.
What you need to do is follow these guides and squash your commits 
https://davidwalsh.name/squash-commits-git
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by DeeprajPandey** [comment]
Using GitHub on Browser. There isn't the squash and merge button in the pull requests tab. :/

**Comment by hemantjadon** [comment]
You will have to use the command line tools.
Check that video link and tutorial

**Pull request closed without merging**
