### PR TITLE
Code changes to reduce page-load time

### PR DESCRIPTION
**Pull request by DeeprajPandey**
Update main.css

Catching up with compressed Images (#1)

* Warn if needs squash

* Adding Mentor: Yathannsh (#406)

* Adding Mentor: Yathannsh

Adding cml content for yathannsh

* Added Yathannsh's Profile

* adding Tran Bao Nguyen in student (#355)

* Add files via upload

* Update students.yml

* Minor Travis fix

* Add squash info

* Small fix

* adding kunal's blog (#450)

* Compress and optimize images (#451)

* Compress JPG

* Optimize PNG

* Fix mentor image (#452)

* Compress JPG

* Optimize PNG

* Fix yathannsh's image

* Fixed inconsistencies in yml, html and css files

* Fixed some inconsistencies in js files

### CODE REVIEW

**Comment by DeeprajPandey** [comment]
Instead of rebasing, I squashed the 10 commits ahead of my branch by mistake. Hope it's okay. :)

**Comment by m1guelpf** [comment]
@DeeprajPandey Could you try to fix Travis?

**Comment by m1guelpf** [comment]
@DeeprajPandey Please add commit https://github.com/fossasia/gci16.fossasia.org/commit/468b6f4a8b990b6c15481d1ee01a15067cee6a7d to fix Danger

**Comment by m1guelpf** [comment]
@DeeprajPandey Let's wait for Travis

**Comment by DeeprajPandey** [comment]
@m1guelpf The commit you merged was the only one I introduced. Rest were added by others. Hope you'll look into this.
As I had squashed and merged the commits ahead of me when I was working on my changes, they started showing up as my changes too (should have rebased my commit)

**Comment by DeeprajPandey** [comment]
@m1guelpf fixed travis. Submitting another PR with the fixes.

**Pull request merged**
