### PR TITLE
Implemented the new design to Students and Mentors Sections 

### PR DESCRIPTION
**Pull request by Elgayar**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

Circilized them, made them more compact and made required adjustments to get all sections consistent with the newly implemented design.

Solves issue #969
Live Link: https://elgayar.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by Elgayar** [comment]
Why is Travis failing this time?

**Comment by robbyoconnor** [comment]
@fossasia/gci16-maintainers -- Opinions?

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
@Elgayar the hover adjustments didn't work well... Test this out by hovering on all the students. Also kill the debugging statements.

**Comment by Elgayar** [comment]
The hover adjustments were to make the overlay as a circle instead of a square, hovering on students is a JavaScript bug that is already opened in issue #968 #971 @robbyoconnor

**Comment by robbyoconnor** [comment]
This hover bug has nothing to do with #968.

**Comment by robbyoconnor** [comment]
#971 is a bug I JUST opened -- I'm shocked nobody else saw it...

**Comment by Elgayar** [comment]
#958 and #948 sorry :joy:

**Comment by robbyoconnor** [comment]
#971 too. Nobody reported that behavior as far as I can tell.

**Pull request merged**
