### PR TITLE
Fixing the ruby tests

### PR DESCRIPTION
**Pull request by abishekvashok**
This is strictly in development please dont merge out here. Merge only
if the script runs fine on travis.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Yes its worked @jig08 @hemantjadon @niccokunzmann @Princu7 see the preview:
image

The link to my task:  https://codein.withgoogle.com/dashboard/task-instances/6211477637693440/

Mergin this since this is now perfect Hurray! :)

**Comment by niccokunzmann** [comment]
@Abhi2424shek Even if you are a maintainer, do not merge your own pull-requests. Let other people do that, please.

**Comment by abishekvashok** [comment]
@niccokunzmann sorry for that... How's the test.

**Comment by niccokunzmann** [comment]
No need to be sorry. It was not written as a rule. Now, it is.

**Pull request merged**
