### PR TITLE
Added my MBDyn logo to website.

### PR DESCRIPTION
**Pull request by sudo-panda**
Task: https://codein.withgoogle.com/dashboard/task-instances/5464743651311616/

### CODE REVIEW

**Comment by Princu7** [comment]
@Baidya99 Thanks for the request. Some things you need to do-

* Add the link to your live gh-pages for easier and faster reviewing.
* Squash all your commits into one and rename it to something useful like "Added MybDn logo to website". You can look at the pinned items in FossAsia GCI channel on slack for more information.!!

**Comment by sudo-panda** [comment]
Could use explain how to make a live gh-pages using my own fork online.

**Comment by shubham-padia** [comment]
@Baidya99 Have a look at https://pages.github.com/ for the same

**Comment by sudo-panda** [comment]
Could you tell me how to do it without having to download git.
That is if there is a way.

**Comment by pa1pal** [comment]
@Baidya99 Whenever you fork a gh-pages repo and made a simple change will make your page live. I looked into your profile and found that the forked repo name is docs.baidya.org and it is live. 
[https://baidya99.github.io/docs.baidya.org/](url)

**Comment by sudo-panda** [comment]
Thankyou to all especially @pa1pal.

**Comment by sudo-panda** [comment]
https://baidya99.github.io/docs.baidya.org/ is the link to my live gh-pages as stated by @pa1pal

**Pull request merged**
