### PR TITLE
A new look.

### PR DESCRIPTION
**Pull request by ankitrgadiya**
I did it for fun actually, but if anybody's interested, we can work on it. 
A new design
Added Comments for sections
I'm enjoying to work on website

More work needed. 
* I don't know where contributor section's css is. 
* Blog section, I'm gonna fix this soon. A probably better option can be to use 2 columns and make cards wider.  
* Need some help with Latest issues section.
* In social section 2 of them are not showing so I'm unable to fix them. 

Fixing Issues : #465 #455 #495 
[Live Link](http://ankitrgadiya.me/gci16.fossasia.org)

### CODE REVIEW

**Comment by m1guelpf** [comment]
@ankitrgadiya The logo section is broken, the issues section could be improved by using tabs, and the text in the contributors section is strange.
Anyway, awesome work!

**Comment by abishekvashok** [comment]
Make the blog section just like the contributors section @ankitrgadiya then about the backgrounds i would recommend material design colours.

**Comment by abishekvashok** [comment]
I would also be happy if you could resolve the test.

**Comment by ankitrgadiya** [comment]
I'm working on fixing things

**Comment by niccokunzmann** [comment]
@ankitrgadiya If you need help or input to problems or ideas, you are welcome to write :)

**Comment by ankitrgadiya** [comment]
@niccokunzmann Sure!

**Comment by ankitrgadiya** [comment]
* Fixed Contributor section now its more consistent now.
* Added transition in Map section

Suggestion:
A lot of students are using same Photo for both Blog and Student Section, and those who are not using the same are using much wider photos. So, we can use same photo for blog and student section. This will also improve the loadtime.

**Comment by hemantjadon** [comment]
This Seems to me a nice work 👍 
@ankitrgadiya please fixup the merge conflicts so we can go ahead :)

**Comment by ankitrgadiya** [comment]
@hemantjadon Still need to fix a lot of things so don't merge right now
I'll try to fix all today itself

**Comment by myfrom** [comment]
Are you animating box-shadow? It's really slow and not recommended to do so especially that the page is already junky.

**Comment by niccokunzmann** [comment]
@Witus13 You can open an issue when it is merged.

**Comment by ankitrgadiya** [comment]
A lot of photos in Blog section are changed. I went ahead and took screenshots from the website and added them because a lot of the screenshots were changed to get 1:1 ration and degraded quality. Also I fixed photos from Blog and Design Section to fit properly. (keeping in mind size of photos to be as small as possible. )

@Witus13 Check the Live link its loading pretty fast. [Live Link](http://ankitrgadiya.me/gci16.fossasia.org)

I asked a few times for some help in Latest Issue section and I'm still asking for help.

This version is now good to merge just the Latest issue section as mentioned above is problematic and the code is more consistent now.

I just checked and a lot of issues are getting fixed due to this.
@oanarosca @m1guelpf @Abhi2424shek @niccokunzmann

**Comment by myfrom** [comment]
I rather mean it sometimes lags in animations, etc. I watched to many Chrome Developers' videos 😜 Anyway, when this will get merged I'll experiment with this box-shadow animations and see if I can make it faster

**Comment by ankitrgadiya** [comment]
@Witus13 Sure! Lets wait for getting it merged

**Comment by niccokunzmann** [comment]
Can you create many small pull-requests based on this one?
The problem I have with large pull-requests is: 

- I can not understand them right away
- Although we may think it is perfect, time will tell, we have problems and we can not revert without reverting good things.
- We can not revert, because too much will be based on this.
- There should be one issue/problem per pull-request. (true, this is not stated anywhere but should be in my belief)

**Comment by niccokunzmann** [comment]
@fossasia/gci16-maintainers Can one of you come ahead and merge? I can not :) I am not the standard and should not be. So, please help them.

Actually I do not really have experience with what I stated as a problem. So, we can try it out.

**Comment by ankitrgadiya** [comment]
@niccokunzmann i dont know if i can create small PRs. I've changed a lot of things which are very basic in site. I agree that It wont be perfect as I'm also a learner.

**Comment by gaeun** [comment]
The loading time seems good to me at least.
The layout of the Latest Issues and Loklak tweets section is a bit broken but I guess we could fix that later... Could you resolve the merge conflicts? @ankitrgadiya

**Comment by abishekvashok** [comment]
I could help out guys let me see this resolve the conflicts and merge

**Comment by codein-dwij** [comment]
@ankitrgadiya I have added a reference to issues you have fixed. Add similar references if you think you have fixed an issue.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek please don't, i'll resolve on my own so that it will not creafe a mess again.

**Comment by Princu7** [comment]
Great work @ankitrgadiya. Resolve it soon.

**Comment by ankitrgadiya** [comment]
I fixed merge conflicts. Newly added logos are optimised. [Live Link](http://ankitrgadiya.me/gci16.fossasia.org/)

**Comment by codein-dwij** [comment]
Can you squash them?

**Comment by codein-dwij** [comment]
Please resize the images and fix the trailing whitespaces :) Also try squashing the commits in one.

**Comment by ankitrgadiya** [comment]
Hey, do not merge yet wait for one last commit

**Comment by codein-dwij** [comment]
Awesome !

**Pull request merged**
