### PR TITLE
Add Twitter in Social Media

### PR DESCRIPTION
**Pull request by PolBaladas**

### CODE REVIEW

**Comment by PolBaladas** [comment]
https://polbaladas.github.io/gci16.fossasia.org/

The twitter Widget style can be changed from Twitter's widget console.

**Comment by daminisatya** [comment]
@PolBaladas Oops you have merge conflict. if you have any problem resolving your conflicts you can ping in the slack group. !

**Comment by PolBaladas** [comment]
Done! I was going to merge the PR myself but it's better if you make sure there are no probs.
Thanks!

**Review by daminisatya — APPROVED** [review]
great!

**Comment by PolBaladas** [comment]
:+1:

**Comment by hemantjadon** [comment]
Cool @PolBaladas 👍

**Pull request merged**
