### PR TITLE
Update students.yml

### PR DESCRIPTION
**Pull request by mercuryprasad**
Hi I am 17 years old student. My name is Prasad. I am participating in GCI16. As a part of it I am uploading my details here.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Hi please add your image into the images/students/ folder @mercuryprasad .

**Comment by animeshsinghweb** [comment]
@mercuryprasad Please read the instruction at students.yml you are supposed to add your details at last or anywhere in the last 3. The people who had enrolled first should be above. :)

>  # New members please add your credentials to a random position in the file.
>  # This is to remove conflicts with other people adding their credentials.

This doesn't means at first anyways. :D

**Comment by animeshsinghweb** [comment]
@mercuryprasad There is conflict in students.yml please resolve it too. 👍

**Comment by abishekvashok** [comment]
@mercuryprasad see the contributing.md file to see the merge conflict resolving tutorials, if you could not help out with them we could help you but convey back to us, and besure to add your image.

**Comment by robbyoconnor** [comment]
@mercuryprasad are you going to resolve your merge conflicts?

**Comment by robbyoconnor** [comment]
You need to clone the repository on your computer, make changes there, and then push them up. The current state of this PR is not good. I am going to close it. Please make a new one with the proper filenames at *240 x 240 [w x h]* -- or even include the file in your commit ;)

**Pull request closed without merging**
