### PR TITLE
Added GCI logo.

### PR DESCRIPTION
**Pull request by harshit98**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

This is my first contribution to open source. I have added the GCI logo. Fixes issue #938

### CODE REVIEW

**Comment by harshit98** [comment]
Fixes issue #938

**Comment by m1guelpf** [comment]
@harshit98 LGTM, but lets wait for Travis.

**Comment by oanarosca** [comment]
It's a bit too large on my screen. Could you fix this? Also, welcome to the community, we're looking forward to seeing more contributions from you :)
screenshot from 2017-01-25 20-24-28

**Comment by harshit98** [comment]
snip
I have fixed the size issue. Above is the screenshot of it, how it looks.

**Comment by m1guelpf** [comment]
Merging as the Travis bot will take care of Coala

**Pull request merged**
