### PR TITLE
Done according to the Descriptions

### PR DESCRIPTION
**Pull request by Mridulbirla13**
Thank you for your pull request!

Please acknowledge each of the following before submitting your pull request.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- leave it unchecked. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Here is my forked repository - (https://github.com/Mridulbirla13/gci16.fossasia.org)
- Participating in GCI 2016
  Here is my Task instance link - (https://codein.withgoogle.com/dashboard/task-instances/6180548856774656/)

### CODE REVIEW

**Comment by robbyoconnor** [comment]
This is invalid.

**Comment by robbyoconnor** [comment]
@Mridulbirla13 

1. You were supposed to read and ackowledge the text that was there -- read it. 
2. You didn't follow directions at all.

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Can't understand why you are changing the whole file

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
You're changing the whole file -- you ignorted the pull request template without bothering to read it. Had you read it, we make clear what we want.

**Comment by robbyoconnor** [comment]
@Mridulbirla13 revert your changes. You changed the line-endings. 

Edit it through your text editor. Why doesn't github respect .gitattributes :/

**Comment by robbyoconnor** [comment]
@Mridulbirla13 -- I added back the pull request template -- check each of those off.

**Comment by robbyoconnor** [comment]
@Mridulbirla13 -- also your image filename isn't correct. I'd recommend you [install git locally on your system](https://git-scm.com/download)

**Pull request closed without merging**
