### PR TITLE
GCI Task update image and credentials

### PR DESCRIPTION
**Pull request by Dodecane**

### CODE REVIEW

**Review by hemantjadon — APPROVED** [review]

**Comment by codethejason** [comment]
If you're doing the add your photo to the site task, please add your actual photo to the site in the students section.

**Comment by tradzik** [comment]
Could you [squash](gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) all the commits into one please?

**Comment by hemantjadon** [comment]
Please resolve the merge conflicts also

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Remove the binary file `Thumbs.db`.

**Pull request closed without merging**
