### PR TITLE
Update blogs.yml

### PR DESCRIPTION
**Pull request by abhijeetmanohar66**

### CODE REVIEW

**Review by abishekvashok — DISMISSED** [review]
Where's the blog image bro, don't leave empty fields if u don't have an image

**Comment by niccokunzmann** [comment]
@Abhi2424shek I think it is ok if a blog has no image.
@abhijeetmanohar66 Thanks for your contribution. I would request a minor change:
The travis build checks if the website works correctly and is visible in this version (green).
It has a problem:
https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181372812#L400
The yaml wants all items (lines starting with "-") in the same number of spaces.
You put a space before the "-", so the file can not be understood by the website-builder. Could cou remove this space and see if it works builds?

**Comment by abishekvashok** [comment]
K @niccokunzmann but what you say about empty fields, we could maybe add a test for it.

**Comment by niccokunzmann** [comment]
@Abhi2424shek #237 - the issue for the logo

**Comment by rhemon** [comment]
Please fix merge conflicts and squash your commits. You can look into CONTRIBUITNG.md file for tutorials.

**Comment by niccokunzmann** [comment]
Great @abhijeetmanohar66! You resolved the yaml error.
In the mean time other students have added their blogs and there is a conflict which git can not resolve automatically. If you resolve it, I would like to merge.

**Comment by m1guelpf** [comment]
@abhijeetmanohar66 You should resolve merge errors and squash all the commits. See contribuiting.md for more info

**Comment by jigyasa-grover** [comment]
With reference to [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
