### PR TITLE
Added Blog and its image

### PR DESCRIPTION
**Pull request by Srijanjha**

### CODE REVIEW

**Comment by Elgayar** [comment]
There are many commits, consider squashing them into one. @SrijanJha28

**Comment by abishekvashok** [comment]
@SrijanJha28 can you squash them and provide a screenshot or a live link to it, in this case the live link is:
https://srijanjha28.github.io/gci16.fossasia.org/

It is determined according to this pattern:
`https://<username>.github.io/<repo_name>`

I can see your changes are working well, but I recommend to add a description and the live link to the PR body as pointed out by danger bot. :/
Overall I am not that satisfied with your work because I mentioned so many times that you should add a description, however I will merge this but next time you yourself will have to squash, if you can't follow the tutorials then ping anyone of us on slack, we are ready 24/7 [at least I will be ready to help you].

@Elgayar we alwyas have the squash and merge button!

**Comment by Elgayar** [comment]
I wanted him to be able to use it from his command line, the goal at the end is to learn new things! But anyways, no problem!! @Abhi2424shek

**Comment by abishekvashok** [comment]
@Elgayar he's a beginner see my post it states next time. we won't annoy him now we can make him learn no problem bro ;) Happy coding...

**Pull request merged**
