### PR TITLE
Dovansan

### PR DESCRIPTION
**Pull request by dovjay**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Add my picture to the student section
- Add my info on student .yml

### CODE REVIEW

**Comment by Elgayar** [comment]
Please resolve the conflicts so that we can merge :) @dovansan

**Comment by Elgayar** [comment]
You can join the slack channel for help!

**Comment by robbyoconnor** [comment]
There is no reason for two pull  requests

**Comment by dovjay** [comment]
The second PR is a mistaken

2017-01-06 4:34 GMT+07:00 robbyoconnor <notifications@github.com>:

**Pull request closed without merging**
