### PR TITLE
Updated students.xml adding my info

### PR DESCRIPTION
**Pull request by animeshsinghweb**
This is another pull request made to solve the conflict caused at https://github.com/fossasia/gci16.fossasia.org/pull/47 
I had added my image and also updated the Students.yml adding my info.

### CODE REVIEW

**Comment by hemantjadon** [comment]
This is okay.

But as a part of the task you also have to add your profile pic in the student section of the gci16 website. Please do that so we can proceed.

Also you can keep on making changes in same PR there is no need to open a new one if you get stuck somewhere.
Also please do provide the link to your task and gh-pages of your fork for fast reviewing process.
Cheers :)

**Comment by animeshsinghweb** [comment]
Hello Hemant Sir,

> But as a part of the task you also have to add your profile pic in the student section of the gci16 website. Please do that so we can proceed.

I had added my image named animeshsinghweb.jpg in images folder of the repo. Do I have to add my image anywhere else, if so please let me know.

Thanks

**Comment by Princu7** [comment]
@animeshsinghweb On the main page of the gci 16, there is a section named students. You have to make changes in the index.html file and add your information there. You can look at the official site and code for more details.

**Comment by jigyasa-grover** [comment]
@animeshsinghweb 

Also,

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Thanks !

**Comment by animeshsinghweb** [comment]
Please have a look over here https://github.com/fossasia/gci16.fossasia.org/pull/108, this is the final pull with no conflict thanks for your help @hemantjadon  @Princu7  @jig08

**Comment by jigyasa-grover** [comment]
Closing this, following up in PR #108.

**Pull request closed without merging**
