### PR TITLE
[GCI Task] Added ainesh to students.yml

### PR DESCRIPTION
**Pull request by champforevaa**
Please Merge the pull request

### CODE REVIEW

**Comment by champforevaa** [comment]
Why isnt my profile showing on the main students.yml?

**Comment by hemantjadon** [comment]
Hey @champforevaa 
please squash your commits so we can merge this PR.

There are two ways in which you can squash.

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an **editor** where you will be asked for every commit whether you want to `pick or squash`. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Comment by champforevaa** [comment]
Hi @hemantjadon 
I have squashed the commits.

Now can the PR be merged?

Thanks!

**Comment by hemantjadon** [comment]
Submit task link so we can approve :)

**Pull request merged**
