### PR TITLE
Adding Abishek V Ashok (my name!) in students section.

### PR DESCRIPTION
**Pull request by abishekvashok**
As part of my first task at GCI, I have added my photo to the students section of the website.
The link to my task page is: https://codein.withgoogle.com/dashboard/task-instances/5169781940420608/ .

Thank you, happy coding...

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Hey @Abhi2424shek 

* Add this information in `index.html` also.
* Rename your commit to something meaningful, such as "Adding <-your-name-> in students/mentors section". Check this out [Github: Rewriting the most recent commit message](https://help.github.com/articles/changing-a-commit-message/)
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

Cheers !

**Comment by abishekvashok** [comment]
hey @jig08 how can I just view the link, I've forgot!!!

**Comment by jigyasa-grover** [comment]
Something like [Abhi2424shek.github.io/gci16.fossasia.org/](Abhi2424shek.github.io/gci16.fossasia.org/) should work ....

**Comment by abishekvashok** [comment]
Hey @jig08 , WOW THERE ARE SOME TERRIBLE problems, the build is failing may I work on it.

**Comment by abishekvashok** [comment]
Hey @jig08 ... I can't get what you are up to madam

**Comment by jigyasa-grover** [comment]
@Abhi2424shek We have made some changes currently, closed/reopened PR to re-start the build.

**Comment by abishekvashok** [comment]
Yes I see the problem with the docker!

**Comment by abishekvashok** [comment]
Now the branch will be fine! @jig08 . Thanks for spontaneous replies.

**Comment by jigyasa-grover** [comment]
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section". Check this out [Github: Rewriting the most recent commit message](https://help.github.com/articles/changing-a-commit-message/)

* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

**Comment by abishekvashok** [comment]
Before that @jig08 , while testing I find that only 9 students names are showing so let me work then I squash it madam! :)

**Comment by abishekvashok** [comment]
Someone messed up with the index.html file, let me see...

**Pull request closed without merging**
