### PR TITLE
Contributor Section

### PR DESCRIPTION
**Pull request by alejoheredia**

### CODE REVIEW

**Comment by Princu7** [comment]
@Heredroky Thanks for the request. Can you please post a link to your GitHub pages for easier review of the request?

**Comment by alejoheredia** [comment]
Wait a moment please. I have just realized that the last 2 commits of this repository have a failure with the YAML file, can you please check that?

**Comment by Princu7** [comment]
@Heredroky Yes there seems to be an error due to the mismatch of the position of the  '-' in the pull request #31 .  Also the contributor section seems to be already added via the pull request #15 . Maybe please correct the incorrect syntax in the yml file and send the request. Thank you!

**Comment by hemantjadon** [comment]
@Heredroky 
It's extremely nice of you to point out the issues. Keep it up :) 
Your work seems to be nice 👍 
Also the new changes seems to be good.
Cheers :) 

Please post the link to your gh-pages as mentioned by @Princu7 :)

**Comment by alejoheredia** [comment]
I've corrected it!!! :) 
Here it is my url if you want to check the changes I've made: [https://heredroky.github.io/gci16.fossasia.org/index.html]

**Review by Princu7 — APPROVED** [review]
@Heredroky Great work. Thanks for fixing the issue. Keep it up!!

**Comment by alejoheredia** [comment]
@hemantjadon 
Thank for the comment :D

**Comment by hemantjadon** [comment]
@Heredroky 
Nice work for the start. 
Keep it up. :) 
Have a great Code-In :)

**Comment by alejoheredia** [comment]
The css in the page: http://gci16.fossasia.org/index.html isn't working. 
But in my page: https://heredroky.github.io/gci16.fossasia.org/index.html  it works. 
Do you know what's happening?

**Comment by alejoheredia** [comment]
Never mind guys

**Pull request merged**
