### PR TITLE
Deleted repeating pictures of Lee and Adarsh in students section

### PR DESCRIPTION
**Pull request by vickyjjj**
For whatever reason, I accidentally left Lee's and Adarsh's pictures in the index.html code from my last pull request. I fixed this by removing their data from the students section for loop. Attached is screenshot of noted issue. Linked [here](https://github.com/vickyjjj/vickyjjj.github.io) is my fork.
screen shot 2016-12-03 at 8 51 16 pm

### CODE REVIEW

**Comment by abishekvashok** [comment]
@vickyjjj could you try to squash the commits,

**Comment by hemantjadon** [comment]
@vickyjjj Please quickly provide the the link to your test site. So I can review

**Comment by vickyjjj** [comment]
@hemantjadon How do I do that? The Javascript doesn't allow the pictures to show up properly on my end, so I'm missing some sort of download/installation and I'm not sure what.

**Comment by hoangvanthien** [comment]
Should we revert the PR?

**Comment by vickyjjj** [comment]
@hoangvanthien You know, that would be a good idea because I have no idea how to squash commits or make my link "live" (although it would be nice if someone could provide a link so I can know for future reference). And I'll just add my picture and information in a new, separate pull request, and this pull request and my original one can both close. Sorry for all the hassle.

**Comment by hoangvanthien** [comment]
Your default branch is `gh-pages`. In order to make a page, as far as I know, you should switch to `master` branch. :) Then you will access https://vickyjjj.github.io/ successfully.

**Comment by hemantjadon** [comment]
Here is your link https://vickyjjj.github.io/vickyjjj.github.io/

**Comment by hemantjadon** [comment]
Things which might help in future

* When there is the code on the gh-pages branch and gh-pages is enabled for that repository,
then that static page is hosted by github automatically at `https://<your-username>.github.io/<your-reponame>`, you can use to see your hosted site.

**Comment by vickyjjj** [comment]
@hoangvanthien @hemantjadon Right, thanks so much!

**Comment by vickyjjj** [comment]
Anyways, it seems like pull request #154 fixes the student section better than this pull request has. So I'll close it. Thanks for the help with Github pages.

**Comment by hemantjadon** [comment]
Well @vickyjjj Your work was also decent, You did a good task Identifying the issues you faced. That's is what more important. Get on to a new issue and keep the spirits high.

Keep Coding :)
Cheers :)

**Pull request closed without merging**
