### PR TITLE
Added a responsive navbar with smooth scrolling to anchors

### PR DESCRIPTION
**Pull request by oscarwong67**
Added a navbar that resizes and collapses on mobile, built in jQuery and HTML. It allows users to instantly navigate to any anchor link to a main section, and it even smooth scrolls.

### CODE REVIEW

**Comment by hemantjadon** [comment]
@oscarwong67 
Please resolve the merge conflicts.
Also provide the link to your gh-pages so that we can see this working.

**Comment by oscarwong67** [comment]
@hemantjadon I have fixed the merge conflicts. gh pages will be coming soon, guess you can take a look then

**Comment by oscarwong67** [comment]
https://oscarwong67.github.io/gci16.fossasia.org/ @hemantjadon here is the gh pages, I have also resolved all merge conflicts!

**Comment by hemantjadon** [comment]
Hi this seems nice

Few UI tweaks maybe required 

* Student section is not aligned properly

* The navbar is not symmetrical horizontally 

   * In my opinion we can remove the top blue header and make the navbar more symmetrical

Btw please mention which task is this a part of

**Comment by oscarwong67** [comment]
@hemantjadon that's odd, I'll try to fix the student section in the morning. Right I'll play around with the navbar as well

This is going to be a part of the feature/claim an issue task, but I haven't even claimed the task yet because my previous one has no response yet from the organization

**Comment by hemantjadon** [comment]
@oscarwong67 mention your previous task link and subsequent PR in slack "#gci".

> This is going to be a part of the feature/claim an issue task, 

It's okay with me, But keep in mind that to avoid the duplication of work you should first claim the task then only start working on it.

**Comment by oscarwong67** [comment]
@hemantjadon thanks for the heads up, next time I'll claim it first

I'll do that as soon as I hopefully  claim the task tomorrow (the previous task is for another organization)

**Comment by oscarwong67** [comment]
@hemantjadon I've claimed the task, I'll leave a message in slack as soon as I fix the merge errors

**Comment by hemantjadon** [comment]
Squashing your commits will be required. See the slack channel "#gci" as many links have been pinned regarding the same.

**Comment by oscarwong67** [comment]
@hemantjadon I've fixed the merge issues, and the student section is aligned. I will squash the commits right now

**Comment by oscarwong67** [comment]
@hemantjadon alright, I've fixed the issues you've outlined (site looks a bit better), and I've squashed my commits into "add navbar". The commit afterward occurs automatically, so I think this is the best I can squash(?)

**Comment by oscarwong67** [comment]
https://oscarwong67.github.io/gci16.fossasia.org/ - preview, by the way. 

Also, I have claimed the task "Website: Add a feature or fix an issue for the GCI website from the github issue tracker". I have linked the PR there, and in the slack #gci channel.

**Comment by oscarwong67** [comment]
the check failed for the final commit, but the final commit has no changes and I do not know how to not have it, as every time I squash my commits into one the "merge" commit is always created after (and fails the check)

**Comment by oscarwong67** [comment]
@hemantjadon all my newest changes are in the "added responsive navbar" commit - all of them. No changes are in the "Merge branch...." one - it was automatic. Preview is still:  https://oscarwong67.github.io/gci16.fossasia.org/

**Comment by oscarwong67** [comment]
@hemantjadon hopefully my merge conflicts are resolved, and i've definitely squashed the commits. If not, could you squash them when merging the PR? because regardless, every time I squash it always creates a merge commit right afterwards which means that I always end up with at least two

**Comment by oscarwong67** [comment]
@hemantjadon do you think you could squash the latest commits when merging the PR instead? not sure if that'd make it easier than me always ending up with a merge commit(?)

**Comment by oscarwong67** [comment]
alright i've finally got the linting errors down, i'll try to squash my commits(?)

**Comment by hemantjadon** [comment]
Yup squash the commits and we will proceed then

**Comment by oscarwong67** [comment]
@hemantjadon alright, I think I've squashed the commits? at least locally, the old ones are gone.

(I ran these commands: git reset --soft HEAD~10 and git commit), then pushed

is there something I should do differently?

**Comment by hemantjadon** [comment]
@oscarwong67 you didn't have to use `reset` 

* You have to squash the commits not remove them entirely. 

* You will have squash them till you have only one commit in this PR.

There are two ways in which you can do this.

* While pushing another commit, you can amend to the previous commit. git commit --amend (when you already have a commit existing and you want to amend to it) instead of doing git commit -m "message" every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 5 commits of yours which you want to squash into single, then the command goes git rebase -i HEAD~5. Which leads to an editor where you will be asked for every commit whether you want to pick to squash. type squash for all the 5 commits present and exit. The rebase continues and you have force push the changes, as in git push -f origin .

This might be a bit confusing, but please watch this https://www.youtube.com/watch?v=qh9KtjfjzCU

Please feel free to ask for help.

**Comment by oscarwong67** [comment]
@hemantjadon since some of my local commits are gone, do you think it'd be easier to squash everything locally, then just create a new PR? since this PR already has 29 commits...

**Comment by hemantjadon** [comment]
you can use `git push --force` to update your local changes here forcefully.

**Comment by oscarwong67** [comment]
@hemantjadon i've somehow managed to squash all of the commits that I personally made down to one, then the merge commit was made automatically after that. Is there a way to avoid this or does that not matter?

**Comment by niccokunzmann** [comment]
@oscarwong67 Can you resolve the merge conflicts and notify me? [task](https://codein.withgoogle.com/dashboard/task-instances/6710449120739328/)

**Comment by oscarwong67** [comment]
@niccokunzmann i've resolved all merge conflicts, should be good on that front

**Comment by hemantjadon** [comment]
Well @oscarwong67 Seems like you have created a lot of commits(46) and you will need to squash them.

There are two ways in which you can squash.

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an **editor** where you will be asked for every commit whether you want to `pick or squash`. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

Also as your PR contains v very large number of commits you can just close this one and open up the new one 👍 

Cheers :)

**Comment by oscarwong67** [comment]
Will open up a new one as that's probably easier than trying to squash a ridiculous number of commits.

**Pull request closed without merging**
