### PR TITLE
blog post about gci and FOSSASIA

### PR DESCRIPTION
**Pull request by hillamu2**
http://hillamu2.edublogs.org/
blogpost
blogpost about fossasia

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@oanarosca  @PolBaladas @rhemon @Abhi2424shek  Pls guide the newbie :)

**Comment by m1guelpf** [comment]
@hillamu2 You have to work on the gh-pages branch, you're working on a revert branch

**Comment by oanarosca** [comment]
Hello! As stated in your task description, you must add the info about your blog in _data/blogs.yml, and your screenshot into images/blogs folder, in gh-pages. But make sure that before you do this, you update your fork (i.e your copy of this repo), so that you're up to date with the latest changes. Read the contributing.md file, and if you have any questions, join our channel on slack so we can help you :smile:

**Comment by m1guelpf** [comment]
Please reopen this in gh-pages branch

**Pull request closed without merging**
