### PR TITLE
GCI Task: Added image and student credentials

### PR DESCRIPTION
**Pull request by kmehant**
Added image and student credentials

### CODE REVIEW

**Comment by kmehant** [comment]
Mentors of this task @mariobehling @hpdang @SoongChee Gi Please check my submission for the first task. Thank you!

**Comment by Princu7** [comment]
@kmehant Thanks for the pull request. You have to post the link to the website (via your GitHub repo) for easier testing and review. You can have a look at the GitHub pages.
https://pages.github.com/

**Comment by kmehant** [comment]
@Princu7 Thank you. Will post it soon

**Comment by kmehant** [comment]
@Princu7 Sir, not able to see my changes. Can you please help me? 

https://kmehant.github.io/

**Comment by Princu7** [comment]
@kmehant No need to call me Sir. :smiley: It looks like the containers for the images of students and mentors have not been yet added to the basic site of GCI 16. That's why you are not able to see any changes. You can look at the source code of the previous GCI 15 site to take a look at the format

https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/index.html
Wait for the mentors of this task to respond. They will give you a better idea and guidance :+1:

**Comment by SaptakS** [comment]
@kmehant firstly, the folder name is `_data` instead of `modify_data`. Secondly it is not being shown because the website hasn't been set up based on the data. Once it is set, it will get shown.

**Comment by kmehant** [comment]
@Princu7 Sure Thank you, @SaptakS Thank you will modify the folder name!

**Review by daminisatya — APPROVED** [review]

**Comment by kmehant** [comment]
@SaptakS @Princu7 My blog post is here :) 
http://mehant-alphaunitedteam.blogspot.in/2016/11/my-first-patch-to-fossasia-under-gci.html

**Comment by kmehant** [comment]
Thank you for merging my code

**Comment by mariobehling** [comment]
Just to reconfirm. The desired outcome of the task is to show the student images on the website. Currently there are no images on the page http://gci16.fossasia.org yet. So, let's progress on this. Cheers.

**Pull request merged**
