### PR TITLE
Removed hover shadows on issue categories and sections, simplified titles.

### PR DESCRIPTION
**Pull request by dannymout**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request
Link to the website: https://dannymout.github.io/gci16.fossasia.org/
- I've made two UI/UX changes. First, I've simplified the titles of all the sections. I found it unnecessary to have a box around it and a shadow. It's a bit too much, so it's just a simple white h2 now, it looks a lot cleaner. The second thing I've done is removed `:hover` shadow on the sections. I've done this because having a shadow that appears on hover makes the user think it's a button or something interactive when it's not.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
May I ask the rationale for this? I actually like it the way it is right now.

**Comment by dannymout** [comment]
@robbyoconnor In my opinion, a shadow appearing when hovering over an object is really only appropriate when the object is something like a button, checkbox, something the user will click. But it's just the background of the section that has the shadow hover effect.

With the titles, I removed the backgrounds because I didn't feel they matched the look of the website. It seems as if you're going with a material design look. Material design cards almost never have transparent backgrounds. The titles are in a what seems to be, transparent material card. And the rest of the website has the profile cards, which also don't have transparent backgrounds to them, they're completely white. So, I decided it would look best to just remove them.

**Comment by robbyoconnor** [comment]
@fossasia/gci16-maintainers, @fossasia/fossasia-gci  -- your opinions?

**Comment by ankitrgadiya** [comment]
@dannymout @robbyoconnor I like the current version, and I want it to be like that.

**Comment by abishekvashok** [comment]
I also express my opinion in favour of the current one however the shadow's depth can be reduced.

**Comment by Elgayar** [comment]
My opinion is the same as @ankitrgadiya I honestly like it more the way it is currently.

**Comment by hoangvanthien** [comment]
@dannymout I love your new simplicity. The shadow style is not really charming to me. But should you consider to wrap titles inside boxes? They look... empty.

**Comment by myfrom** [comment]
IMO removing the shadow is good but the titles look better as they are now.

**Comment by abishekvashok** [comment]
So we have a deadlock at 2:2 whats the other opinions. @robbyoconnor r u around.

**Comment by robbyoconnor** [comment]
I'm in favor of rejecting this.

**Pull request closed without merging**
