### PR TITLE
Decorated and Enhanced Thanks Section + Contributors Section (Circilized It!)

### PR DESCRIPTION
**Pull request by Elgayar**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- I made the thank you section more colorful and enhanced, the font was increased, it is not a separate eye-catching section with a different background color than the other sections!
Solves #930

Live Link: https://elgayar.github.io/gci16.fossasia.org/#contributors

### CODE REVIEW

**Comment by Elgayar** [comment]
Screenshot: 
image

**Comment by Elgayar** [comment]
Now that's something creative! #929 
image
@mariobehling

**Comment by mariobehling** [comment]
Thanks. Very nice!

**Comment by Elgayar** [comment]
Glad you liked it! @mariobehling

**Pull request merged**
