### PR TITLE
i did it as per the task description.

### PR DESCRIPTION
**Pull request by itsguneetsingh**
hope this is correct

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why was this merged...he changed the entire file vs adding his entry..

**Comment by robbyoconnor** [comment]
To top it off...it's got mixed line-endings now.

**Comment by animeshsinghweb** [comment]
@robbyoconnor Seems it is fixed now.

**Comment by abishekvashok** [comment]
@animeshsingh i could see the M still there

**Comment by animeshsinghweb** [comment]
@Abhi2424shek check official file: https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/_data/students.yml

**Comment by abishekvashok** [comment]
@animeshsinghweb sorry I forgot about coala, coala and travis fixed it for us @robbyoconnor 

image
My script is working!

**Comment by animeshsinghweb** [comment]
GG @Abhi2424shek  👍

**Comment by robbyoconnor** [comment]
I fixed it in 28eb70bafe305e63b8ad310b31cb30d577c0e095.

**Comment by robbyoconnor** [comment]
@Abhi2424shek your script was not working. I renamed it. Also I excluded the coala-fix branch from travis because it will start to get rather redundant.

**Comment by abishekvashok** [comment]
@robbyoconnor so you too deserve credits,
saluting you sir...
Sorry for not giving you credits and thanks for helping me out.
I thought coala fixed it sorry for that too @robbyoconnor 
Will you forgive me sir please ?

**Comment by robbyoconnor** [comment]
@Abhi2424shek -- I just know ruby well and the coding conventions -- so I brought it into line with those. 

By the wthat ^M is CR (Carriage Return)...the fact the ENTIRE file changed 

No student should change the whole file.

**Comment by abishekvashok** [comment]
@robbyoconnor I too hold the same view.
Next time sir when a student merged a PR and there is an error let him work on it we may help but not make a PR or commit for him. ok sir :)

They should learn right? :) :) :)

**Pull request merged**
