### PR TITLE
Add my image. More responsive.

### PR DESCRIPTION
**Pull request by hoangvanthien**
Change columns occupation of student’s grids. Change width of contributors section. Add my image and my social media links.

### CODE REVIEW

**Comment by hemantjadon** [comment]
@hoangvanthien Please provide link to gh-pages of your fork for easy reviewing.
Also please specify the task

**Comment by hoangvanthien** [comment]
@hemantjadon 
My fork: https://github.com/hoangvanthien/hoangvanthien.github.io
Task: https://codein.withgoogle.com/dashboard/task-instances/5604087416487936/

The task is to add my photo into FOSSASIA student section. Although I finished this task before, but at that time I only added files into images folder and information into yml file. But a few hours ago, Mr. Mario Behling asked to make my photo appear on the site. And I did as I was asked. 

While I was doing my task, I found out something that need to be redecorated so I fixed them too.

**Comment by daminisatya** [comment]
@hoangvanthien I can't see the contributors list? is your fork in sync with the main branch?

**Comment by hemantjadon** [comment]
@hoangvanthien 
This might help https://help.github.com/articles/syncing-a-fork/
Please sync your fork.

**Comment by hoangvanthien** [comment]
@daminisatya @hemantjadon 
I synced before I made changes. Did you mean the "contributors-list" id in the index file? I also questioned why there is nothing in contributors list too. But it turns out that the information of this part is generated and shown through **main.js** file.

**Comment by hemantjadon** [comment]
@hoangvanthien 
You will have to sync again as the changes have been made after you last synced.

And also now there is a "student-section" please see the main http://gci16.fossasia.org/
And according to the task you have to add your profile pic there also.

**Comment by hoangvanthien** [comment]
I synced. What do I need to do next?

**Comment by hemantjadon** [comment]
@hoangvanthien 
I am still not able to view the Contributors and students list on your fork.

**Comment by hoangvanthien** [comment]
How could it be possible? I updated from fossasia before I made changes. After I changed, I created a pull request and synced to my own fork. Again I've just synced as you asked me to do. I can see my changes on my fork on github.com. Can you please capture your screen where you expect to see contributors and students list? Because everything I added seems to be clear to me!

**Comment by hoangvanthien** [comment]
Is it okay now?
https://hoangvanthien.github.io

**Comment by daminisatya** [comment]
@hoangvanthien Cool. looks perfect now,

**Comment by hemantjadon** [comment]
@hoangvanthien 
Nice work 👍 

Keep Coding :)

**Comment by hoangvanthien** [comment]
I understand the problem. I need to sync 'gh-pages' with 'master' so that my site will run properly. Thank you for helping me. 👍

**Comment by hemantjadon** [comment]
Anytime :) 
Also can you check for why student section heading not seemed to be Styled?
It seems in your repo but not in main site
I think it is related to the removal of "head" class in `h1` of heading.

**Comment by hoangvanthien** [comment]
I don't know. I met the same problem a few minutes ago but **now they are beautiful** on gci16.fossasia.org

**Comment by hemantjadon** [comment]
Yup cool
Maybe some Caching issue.
Anyway nice work

**Pull request merged**
