### PR TITLE
Improved Design V2 Section

### PR DESCRIPTION
**Pull request by ankitrgadiya**
- Improved Design V2 Section

Original
screenshot from 2016-12-27 01-43-09

```<!-- Safe Edit -->```

Changed
screenshot from 2016-12-27 01-42-42
screenshot from 2016-12-27 01-42-45

### CODE REVIEW

**Comment by Elgayar** [comment]
Again, why don't you provide a live link? :D @ankitrgadiya

**Comment by Elgayar** [comment]
You can as well provide a live link from the new branch you created. Just push it to your origin.

**Comment by ankitrgadiya** [comment]
@Elgayar I discussed this with mentors and they said screenshots is sufficient as I'm working on different branches. But Still I'm merging changes to my gh-pages so that you can see the live preview.

**Comment by ankitrgadiya** [comment]
@Elgayar [Live Preview](https://ankitrgadiya.github.io/gci16.fossasia.org/)

**Comment by Elgayar** [comment]
Great Job! Keep coding! @ankitrgadiya

**Comment by ankitrgadiya** [comment]
@louisgag I tried pinging you but you didn't replied.
Actually before this cards were taking the shape of the logo which was not looking good. Check this [PR](https://github.com/fossasia/gci16.fossasia.org/pull/670)

Also it wasn't consistent. This layout will not change shape no matter what now, and we are asking students to submit there logos in 1:1 ratio which will look good with this layout. And I'm keeping an eye on all logos so if logos are not in 1:1 ratio I'm resizing them. 

Please don't revert this.

**Comment by louisgag** [comment]
@ankitrgadiya I appreciate that you care about presentation, but that doesn't solve the white bar issue and in the MBDyn logo task and I am not asking any specific aspect ratio, are you referring to another task I don't know of when speaking of a 1:1 ratio? https://codein.withgoogle.com/tasks/5760211514032128/ (note that this tasks is only open to me and Andrea as mentors)

**Comment by ankitrgadiya** [comment]
@louisgag I'm not talking about tasks, I'm taking about [this](https://github.com/fossasia/gci16.fossasia.org#adding-logos). 
If white bar is an issue then we'll try to fix it, no problem in that. I mean just due to white bar we cannot ruin the whole section right?

**Comment by louisgag** [comment]
@ankitrgadiya ok fine, I won't mingle this anymore. All the Best.

**Comment by ankitrgadiya** [comment]
@louisgag Thanks :-)

**Comment by louisgag** [comment]
@ankitrgadiya made the white bar an issue: https://github.com/fossasia/gci16.fossasia.org/issues/731

**Pull request merged**
