### PR TITLE
Added my info in index.html, students.yml and modified the designs of the site

### PR DESCRIPTION
**Pull request by animeshsinghweb**
Hello,

I had done many changes to the repository and had resolved many bugs (especially in index.html).
Please refer to my commits for having a glimpse of the changes, and you can compare them by going to http://gci16.animeshsingh.in/ (gh-page) and compare to the original one.

My current task is https://codein.withgoogle.com/dashboard/task-instances/4646195228049408/

Is it ready for submission? Am I missing anything in the code?

Thanks.

### CODE REVIEW

**Comment by Princu7** [comment]
@animeshsinghweb Thanks for the request. Your changes look good. But there are some scope of improvements. First of all, remove the issues which are causing the Travis build to fail. You can use coala to properly lint the code.
After you are done resolving the issues, you have to squash your commits into one. Cheers

**Review by hemantjadon — CHANGES_REQUESTED** [review]
@animeshsinghweb 

* The travis build is also failing please check for the linting (indentation/spaces) and use coala for fixing the build.

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"

* Also provide the link to live gh-pages from your forked repository or relevant screenshot for easier review.

Cheers !

**Comment by animeshsinghweb** [comment]
@hemantjadon  I had fixed the gh-pages linting and Travis issues, but having some troubles in squashing. Can you guide me?
Thanks.

**Comment by hemantjadon** [comment]
Hi @animeshsinghweb 

There are 32 commits here so you must squash those so that we can merge.

There are two ways in which you can squash.

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an editor where you will be asked for every commit whether you want to pick to squash. type `squash` for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Comment by hemantjadon** [comment]
Before squashing please check for linting errors, Here are the build logs for your latest commit
https://travis-ci.org/fossasia/gci16.fossasia.org/builds/180929174

You can use `coala` for linting

**Comment by animeshsinghweb** [comment]
@hemantjadon, I appreciate your sincere support.
 I had fixed the linting error myself before, but it reappeared due to a recent pull.
I am using Cloud9 and I am getting troubles installing Coala over there. Any help?
Thanks.

**Comment by abishekvashok** [comment]
Please don't enter your info to index.html add it to students.yml

**Comment by hemantjadon** [comment]
@webhaikal 
Please also add your info to `students.yml`.(you may use a different PR)
Also provide the task link after adding your info so we can approve

**Comment by hemantjadon** [comment]
@animeshsinghweb 
Please also add your info to students.yml.(you may use a different PR) [use 1 commit for this only] :P
Also provide the task link after adding your info so we can approve

**Comment by hemantjadon** [comment]
@animeshsinghweb 
We are now using the `student.yml` file for generating the student section so you have to put up your information there only.

**Pull request closed without merging**
