### PR TITLE
Added Praveen Patil (Gnovi) to mentors

### PR DESCRIPTION
**Pull request by kekesh**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- I added @wavicles to the section for mentors along with his social media.

Preview:
image

Live website:
https://redblacktrees.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why are you chaning The students file?

**Comment by kekesh** [comment]
I think the student changes are from before - my repository was not up to date. I will make a new pull request after I fix that.

**Comment by robbyoconnor** [comment]
Then rebase your branch -- it shouldn't contain this -- I fixed it.

**Comment by robbyoconnor** [comment]
Cherry-picked in 5361fb6d0849f7e11a78a2444c55d16feb78ee90

**Comment by robbyoconnor** [comment]
@redblacktrees always rebase or merge changes before you make a new pull request. 
`git remote add upstream https://github.com/fossasia/gci16.fossasia.org`
`git pull --rebase upstream gh-pages` 
`git push origin gh-pages`

**Comment by kekesh** [comment]
Thank you, I will do this in the future.

**Pull request closed without merging**
