### PR TITLE
Done as asked

### PR DESCRIPTION
**Pull request by itsguneetsingh**

### CODE REVIEW

**Comment by abishekvashok** [comment]
@Guneetconvent2002 can you add a new line at the end of the students.yml file as a new EOF is required and remove some whitespaces not needed after your info like `"name: name    "` after the name you are seeing the spaces right so fix them up. After that we will merge your request

Else good work :)

**Comment by animeshsinghweb** [comment]
@Guneetconvent2002.
Please **edit** your image 'images/blogs/Guneet.JPG'
- Rename is to `guneet.jpg` - it is a better practice to use lowercase name in files.
- Resize your image dimensions is `600x398px` and you are supposed to use `240x240px` (if your uploading your dp, but my last point would make it invalid).
- Please use a portrait image, your image seems to be 90 deg tilted.
- Please squash your image size, your image file size is approx 5.8MB, which is too much, Try to bring it below atleast 800kb, using online image compressing softwares.
- Also rename your image url from `blog_img: Guneet.jpg` to `blog_img: guneet.jpg` following my point number 1.
- **MORE IMPORTANT** - Since, you are submitting this for a task (as I can guess), it is irrelevant to use your own dp (display picture) to submit. Please take a screenshot (google, if you don't know how to take a screenshot) of your blog, and use that image by deleting your current one. Take examples of the existing blog images.

**Comment by mananwason** [comment]
@Guneetconvent2002 Also please see why there are so many changes being shown. I think you're using a different indentation than the one used in this file. Please see if you can fix that. Thanks

**Comment by robbyoconnor** [comment]
@Guneetconvent2002 you should not have that many changes to add yourself. Please fix this.

**Comment by robbyoconnor** [comment]
I'd recommend trashing your branch, closing this pull request and doing it properly.

**Pull request closed without merging**
