### PR TITLE
Solves #795: Fixed mentor popup

### LINKED ISSUE #795: Students/Mentors info popup bug on mobile
Popup is not displaying correctly in small viewport
info not displaying correctly

### PR DESCRIPTION
**Pull request by gaeun**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Fixed #795 for mentors as well

# Preview

- Live link: https://gaeun.github.io/gci16.fossasia.org/
screen shot 2017-01-03 at 9 46 36 pm

### CODE REVIEW

**Comment by gaeun** [comment]
@robbyoconnor Do you think this is good enough?

**Comment by Elgayar** [comment]
@gaeun I think it would be better if you put an "X" in the top corner instead of "Close", this could be another issue anyways. Because it's not related to this one in particular.

**Comment by robbyoconnor** [comment]
@gaeun the close button is clobbering some of the text so no -- I don't think it's good enough...You need to adjust the modal for mobile...

**Comment by robbyoconnor** [comment]
It actually looks ok...however i'm using your PR to check something

**Comment by robbyoconnor** [comment]
@gaeun go ahead and work on your next task -- soon as CI returns -- I'm gonna merge this.

**Comment by robbyoconnor** [comment]
(sorry for spam)

**Comment by robbyoconnor** [comment]
\o/

**Pull request merged**
