### PR TITLE
Added social media section and styled it

### PR DESCRIPTION
**Pull request by oanarosca**
Added Facebook and Google+, bootstrap file and a main css file. See the result at https://oanarosca.github.io/gci16.fossasia.org

### CODE REVIEW

**Comment by daminisatya** [comment]
@oanarosca Cool, Looks great! But can you provide me a link to the corresponding GCI task?

**Comment by oanarosca** [comment]
Sure! Here you go: https://codein.withgoogle.com/dashboard/task-instances/4939600946528256/

**Comment by daminisatya** [comment]
selection_338

Can you fix this broken icon to the top right corner? Looks like the other half is missing!

**Comment by hvardhanx** [comment]
LGTM. Nice work!  :)

**Pull request merged**
