### PR TITLE
Improvements to social media section

### PR DESCRIPTION
**Pull request by myfrom**
Related to #625. Now widgets load smaller size when on phone. I also deferred the importing of widgets until load event happens so page loads 10 seconds faster ⏩.
My code does not require jQuery or any other library and should work in any browser in which the current page works.
[Live demo](https://witus13.github.io/gci16.fossasia.org/)
[GCI task](https://codein.withgoogle.com/dashboard/task-instances/5631023930933248/)

There's a bug with GitHub widget but it says that API limit exceeded so probably not caused by my edits

### CODE REVIEW

**Comment by myfrom** [comment]
Is this checkbot really necessary? Is there a way to make it not brake my build?

**Comment by robbyoconnor** [comment]
@Witus13 yes there is and I just did it.

**Comment by myfrom** [comment]
@robbyoconnor Thanks 😄 Can I use this in my future PRs?

**Comment by robbyoconnor** [comment]
Yes add `<!-- Safe Edit -->` anywhere in your description.

**Comment by robbyoconnor** [comment]
This looks good. @fossasia/gci16-maintainers -- if you see percy failing due to visual differences being found..it's expected. So long as Travis passes and it doesn't look like crap and/or change the entire file and line-endings(which shouldn't happen -- git will do magic to convert them for us) -- we're good to go

**Comment by robbyoconnor** [comment]
Good job!

**Pull request merged**
