### PR TITLE
Image and credentials

### PR DESCRIPTION
**Pull request by BohJieQi**

### CODE REVIEW

**Review by daminisatya — CHANGES_REQUESTED** [review]
That code looks great! But can you please resolve your conflict.

**Comment by daminisatya** [comment]
@BohJieQi This can help you resolve the conflicts :) 
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by BohJieQi** [comment]
Okay, thank you! Is the new commit okay?

**Comment by jigyasa-grover** [comment]
@BohJieQi  Nope, still there....

**Comment by jigyasa-grover** [comment]
As @daminisatya  says, check out [(video) How To Manually Fix Git Merge Conflicts](https://www.youtube.com/watch?v=g8BRcB9NLp4) for help :)

**Comment by robbyoconnor** [comment]
Resolve the conflicts and I will accept you task until then I am sending it back.

**Comment by BohJieQi** [comment]
Okay, I have created another pull request, sorry for the inconvenience caused!

**Comment by jigyasa-grover** [comment]
@BohJieQi Closing this then. thanks !

**Pull request closed without merging**
