### PR TITLE
Added my logo design for MBDyn to the website

### PR DESCRIPTION
**Pull request by Dodecane**

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@LeeCareGene Thanks !

Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> logo design for MBDyn" and we are good to go ...

**Comment by Dodecane** [comment]
Umm i squashed mine but more commits came out

**Comment by Dodecane** [comment]
oops

**Comment by jigyasa-grover** [comment]
@LeeCareGene Cool, you squashed it... could you also rename it to something meaningful, such as "Adding <-your-name-> logo design for MBDyn" and we are good to go ...

**Comment by Dodecane** [comment]
Ok done

**Comment by jigyasa-grover** [comment]
umm @LeeCareGene I guess it didnt work out well.

Check out [Github: Rewriting the most recent commit message](https://help.github.com/articles/changing-a-commit-message/) for help.

**Pull request closed without merging**
