### PR TITLE
apurvjainblog.jpg

### PR DESCRIPTION
**Pull request by ApurvJain123**
name : Apurv Jain
blog_link :http://apurvjain123.edublogs.org/2016/12/04/about-me/

### CODE REVIEW

**Comment by ankitrgadiya** [comment]
Hey, @ApurvJain123 
You will also have to edit a file called _data/blogs.yml and add your info there.
After editing push again and it will show here. 
Checks are failing but its not because of you so don't worry about that.

**Comment by jigyasa-grover** [comment]
Read [gci16.fossasia.org#blog-post](https://github.com/fossasia/gci16.fossasia.org#blog-post) to know about adding your blog-post to the website.

**Comment by ankitrgadiya** [comment]
@apoorvk You have to add your info in the already existing files, you dont have to create your own.

**Comment by niccokunzmann** [comment]
@ApurvJain123 What are your thoughts? How would you like to go on. If you have any quastion, please ask me.

**Comment by ApurvJain123** [comment]
It was my task to create PR on GC16 FOSSASIA but sometimes I got confused so there was problem but I will correct it. :)

**Comment by rhemon** [comment]
@ApurvJain123 at line 94 can you add a space after `article_link: `  and there are some other build fails.
I have resolved merge conflict for you.

**Comment by rhemon** [comment]
and whats the purpose of the About_Me file?

**Comment by ApurvJain123** [comment]
thank u :)

On 11 Dec 2016 10:21, "Ridhwanul Haque" <notifications@github.com> wrote:

@ApurvJain123 <https://github.com/ApurvJain123> at line 94 can you add a
space after article_link: and there are some other build fails.
I have resolved merge conflict for you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/gci16.fossasia.org/pull/356#issuecomment-266263329>,
or mute the thread

**Comment by ApurvJain123** [comment]
How to merge it.

**Comment by niccokunzmann** [comment]
@ApurvJain123 I merged it. You can look at the website and see if everything is right. If not, you can create an issue or a new pull-request.

**Comment by niccokunzmann** [comment]
If you like to do me a favor: The png file is quite large. 0.2mb. Can you try if jpg is smaller? Maybe not it is not. I do not know.

**Pull request merged**
