### PR TITLE
Blog Section added with Instruction in Readme Fixes #68

### LINKED ISSUE #68: We need to add the blog section
Students who are finishing the blog task are unable to add their post and link to the website since we have no section for it. We need to build that feautre.

### PR DESCRIPTION
**Pull request by rhemon**
Here is the my version link :
https://rhemon.github.io/gci16.fossasia.org/
also view in github: https://github.com/rhemon/gci16.fossasia.org

I have added the blog section by adding a blog.yml file where student can get add their blog post, and then the page takes its data from that. 
I also added a bit of my information on student.yml

### CODE REVIEW

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Resolve merge conflicts please.

**Comment by rhemon** [comment]
where can i see the merge conflicts?

**Comment by rhemon** [comment]
and i m not really understanding this merge conflict thing, first of all the changes in index.html file wernt done by me, as I have mentioned in commit description, that when I first tried to to sync, I suddenly had some error, and after that I had those changes which were probably done by other student. Secondly in students.yml the change that I have made was removing the blog part from my description and created a separate blog.yml file where I have added it. It would be helpful if you could tell me what I could do to resolve the merge conflict. Thanks

**Comment by rhemon** [comment]
and also i am not sure if its only in my browser but it seems like some weird changes have occurred in the http://gci16.fossasia.org/ 
screen shot 2016-12-01 at 8 11 16 pm

**Comment by hemantjadon** [comment]
Hi @rhemon 
* You can see the conflicts here in the PR section. (See Below).

* It is not always necessary that part of code you changed will only cause merge conflicts.

* Sometimes what happens is some PR's which were generated after yours were merged first, and thus the conflicts arise from them.

* You can resolve the conflicts using the CLI.

* The simple tutorial which will be helpful https://githowto.com/resolving_conflicts

* *Don't be afraid* of merge conflict, they are bound to come in the open source world and you must understand how to handle them.

**Comment by rhemon** [comment]
Thanks for the link, I will be doing that.

**Comment by hemantjadon** [comment]
Also in my browser things seem to be working fine.
Please specify more details if problem persists.

**Comment by hemantjadon** [comment]
Also you can watch this video to clear the merge conflicts.
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by rhemon** [comment]
Ok is this fine? but one question the part that I deleted in students.yml file, I had to bring it back, if i remove it will it cause merge conflict again?

**Comment by hemantjadon** [comment]
@rhemon 
You can delete the part from students.yml if it is not required and then resolve the conflicts.
Make sure that the part you delete is no longer required.

Also please link your gh-pages so we can see the changes easily.

Please see there is a merge conflict again in index.html

**Comment by rhemon** [comment]
Ah yeah sorry here its : https://rhemon.github.io/gci16.fossasia.org/
and yes i did remove the part that wasn't required

**Comment by hemantjadon** [comment]
Looks nice 👍 

Please Resolve the merge conflicts.

[UI-Tweak]

* Can there be an image regarding the blog instead of the initial words.

* Black text on green background is not prominent.

* Highlight the writers name

**Comment by rhemon** [comment]
Ok finally it shows no conflicts! I did the UI tweaks except the image, since I think its difficult without having all data, since every time students add posts will be different so positioning according to mine will not be same some else's. I still tried taking suitable picture but its not perfect, but if its ok for now I would like to keep it like this, and hopefully come back to edit the style better once I have more data
https://rhemon.github.io/gci16.fossasia.org/

**Comment by hemantjadon** [comment]
Cool @rhemon 👍 

But this will require updates in future.

Is this related to any task, if yes then please provide the link

**Comment by rhemon** [comment]
Yes this task :https://codein.withgoogle.com/dashboard/task-instances/5871370210639872/

**Comment by rhemon** [comment]
Yes that is why I do not wanna do all styling now, since I know as blog posts will be added the style I have now will probably get ruined, so I want to do this in future when it will have a lot of data added

**Comment by rhemon** [comment]
i hope that it is fine and wont be something that will be against my task

**Comment by hemantjadon** [comment]
@rhemon Sure it's fine for now.
But the task mentioned that you must address an issue.
I know you have worked hard on this, and the output is fine.

So follow these instrucrtions carefully.

* The main objective of the task was to make the student aware of `Issue Tracking` system in `github` which is very important in open-source projects.

* So go to the issue tab in the repository https://github.com/fossasia/gci16.fossasia.org/issues

* Raise a New issue naming it whatever new feature you have implemented.

* Then reference it in this PR by using `#` reference system of github.

**Review by hemantjadon — APPROVED** [review]

**Comment by hemantjadon** [comment]
Nice work @rhemon 
Keep It up :) 
Cheers on your 4th task :)

**Comment by rhemon** [comment]
Yeah thanks a lot

**Pull request merged**
