### PR TITLE
Moved 'Thanks contributor' to top

### PR DESCRIPTION
**Pull request by ankitrgadiya**
Issue #647 
* Moved 'Thanks contribution' to the top of Contribution section
[Live Link](http://ankitrgadiya.me/gci16.fossasia.org)

It will not look good if we place it inside Contribution box.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Let me see the preview...

**Comment by abishekvashok** [comment]
It does not look good on mobile

**Comment by ankitrgadiya** [comment]
@Abhi2424shek I didn't changed the section at all, I just moved it on top.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Oh wait now I know what you're talking about. I'll add margin on top.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek I added margin on top. Check now

**Comment by robbyoconnor** [comment]
This broke things.

**Pull request merged**
