### PR TITLE
Added animeshsinghweb in _data and uplaoded image and fixed few UX bugs

### PR DESCRIPTION
**Pull request by animeshsinghweb**
I added my image and students.yml and blogs.yml and fixed few bugs.

My task: https://codein.withgoogle.com/dashboard/task-instances/4646195228049408/
My GH-Pages: https://animeshsinghweb.github.io/gci16.fossasia.org/

Thanks.

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@hemantjadon can you check now and accept the PR?
Thanks.

**Comment by hemantjadon** [comment]
You need to squash the commits before we can merge.

There are two ways in which you can squash.

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an **editor** where you will be asked for every commit whether you want to `pick or squash`. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Comment by shubham-padia** [comment]
@animeshsinghweb In addition to what @hemantjadon said, i cannot open the gh-pages link you have provided. Look into that too .

**Comment by animeshsinghweb** [comment]
@shubham-padia 
I got what was the serious issues going on. I hadn't created any branch on my repo and was directly working on it. Hence, I removed that repo and re-forked and I would do the things again.

I hope this time all will go right.
I will update you guys in few moments, once I am done.

Thanks.

**Comment by animeshsinghweb** [comment]
Guys I would be updating on this PR https://github.com/fossasia/gci16.fossasia.org/pull/190
Thanks.

**Comment by jigyasa-grover** [comment]
>Guys I would be updating on this PR #190

Closing this.

**Pull request closed without merging**
