### PR TITLE
added myself

### PR DESCRIPTION
**Pull request by Jokubasdk**

### CODE REVIEW

**Comment by Jokubasdk** [comment]
@checkbot sorry but I don't really understand what you mean

**Comment by Elgayar** [comment]
@Jokubasdk Why did you remove the pull request template?

**Comment by Jokubasdk** [comment]
@Elgayar As far as I know I didn't delete anything and I don't really know what a pull request template is.

**Comment by Elgayar** [comment]
https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/.github/PULL_REQUEST_TEMPLATE.md

@Jokubasdk This should be in your PR's description. 
However, I can't merge anyway because Travis has failed, so try and fix it.

**Comment by robbyoconnor** [comment]
@Jokubasdk remember to read things.

**Comment by robbyoconnor** [comment]
@Jokubasdk -- i merged this.

**Comment by Jokubasdk** [comment]
@robbyoconnor @Elgayar So what exactly do I have to do? (I'm not very good with github)

**Comment by abishekvashok** [comment]
Just read the PR template and replace what ever it seems to replace and read and understand the contributing.md and the readme.md files

**Comment by Jokubasdk** [comment]
@Abhi2424shek I have read and understood those two .md files but it's still not clear to me what I should replace.

**Comment by abishekvashok** [comment]
When you submit a PR danger pops up a comment after that your PR body will be updated by danger, there in the PR body there will be a text which states to be replaced so when you submit a PR wait for danger to update your PR body and then replace only the specific parts of the PR body by reading it, (replace only the parts which states to be replaced)

**Comment by Jokubasdk** [comment]
@Abhi2424shek could you maybe help me in steps, because I still don't understand what I should do

**Comment by abishekvashok** [comment]
Ping me on slack for the same

**Comment by Jokubasdk** [comment]
I've sent you a message on slack

**Pull request merged**
