### PR TITLE
Added my data

### PR DESCRIPTION
**Pull request by VishalVakil**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by oanarosca** [comment]
Hi and thanks! Please solve the merge conflicts you created, so we can merge your changes. You can find info about this in the contributing.md file, or seek live help on our Slack channel. Best of luck!

**Comment by VishalVakil** [comment]
ok but which file is conflicting?

**Comment by oanarosca** [comment]
The students.yml file. You and another student probably tried to modify the same portion of the file, so now git doesn't know which version should be kept.

**Comment by VishalVakil** [comment]
How should I resolve it?

**Comment by oanarosca** [comment]
See [this video](https://www.youtube.com/watch?v=g8BRcB9NLp4).

**Comment by VishalVakil** [comment]
should I remake this repository and add my data

**Comment by VishalVakil** [comment]
thanks for your help!

**Pull request closed without merging**
