### PR TITLE
Restructure index.html

### PR DESCRIPTION
**Pull request by hoangvanthien**
https://hoangvanthien.github.io
The old website has problem with highlighting menu item as we scroll (http://gci16.fossasia.org). There was no issue opened about this.
The point is wrapping the right content in the right div/section.
I also added Map in menu item.

### CODE REVIEW

**Comment by abishekvashok** [comment]
I can't see any cha nga can you give an explanation and the next time don't merge your own PR.

**Comment by hoangvanthien** [comment]
@Abhi2424shek Yup. I'm sorry, my bad. I didn't read maintainer note. Since it's merged, you probably didn't see changes. 😢

**Comment by abishekvashok** [comment]
No probs... Happy coding 😊

**Comment by hoangvanthien** [comment]
@Abhi2424shek If you notice in "Files changed", you will see that I've put blog post, logo design, issues, ... inside div projects. By doing this, scrolling through these will highlight the item "Projects" on menu bar. 

Again, I shouldn't have merged my own PR, which makes comparison really difficult. 😢

**Comment by abishekvashok** [comment]
No problems at all happy coding bro don't feel bad at all I ask you sorry if I hurt your feelings really sorry. ☺

**Pull request merged**
