### PR TITLE
Highlight the corresponding section in the navbar

### LINKED ISSUE #251: Highlight the corresponding section in the navbar
Currently, the navbar doesn't highlight the section on which we are present. It would be nice if it could highlight the corresponding section. Like if we are in the mentor section on the page, mentor should be highlighted on the navbar. Similarly, if we are on the students section, student should be highlighted on the navbar.

@jig08 @niccokunzmann @hemantjadon @daminisatya What do you guys think about this? Any student interested in taking this up?

### PR DESCRIPTION
**Pull request by hoangvanthien**
Fix #251 
Please visit https://hoangvanthien.github.io/ for the result.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@hoangvanthien Looks good to me

**Comment by oanarosca** [comment]
Great job! See and fix the inconsistencies and this can be merged :)

**Comment by m1guelpf** [comment]
Looks good to me, but Travis failed.

**Comment by hoangvanthien** [comment]
Okay okay, it was about trailing spaces. Wait me for a second.

**Comment by abishekvashok** [comment]
@hoangvanthien sure,

**Comment by hoangvanthien** [comment]
Erm... May I know how important deleting trailing spaces is; that Travis has to check every pull request?

**Comment by oanarosca** [comment]
It is configured to do so, it's for keeping code homogenous and tidy, or at least that's what I know. I myself consider trailing whitespaces the smallest problem of all, greater ones being no line breaks at EOFs and using tabs instead of spaces.

**Comment by m1guelpf** [comment]
@hoangvanthien Still failing...

**Pull request merged**
