### PR TITLE
Added photo and updated website

### PR DESCRIPTION
**Pull request by Dodecane**

### CODE REVIEW

**Review by Princu7 — CHANGES_REQUESTED** [review]
Really happy to see your dedication. But there are a few things that you still need to do -
* Close other pull requests opened by you
* Remove the thumbs.db file
* In the students.yml file, it should be
image:  ../images/leeCareGene.jpg
instead of 
image: leeCareGene.jpg

* Provide a link to the task instance that you are working on and a link to your updated gh-pages so I can review the change and approve it.
Cheers

**Comment by Dodecane** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5464377371131904/
leecaregene.github.io

**Comment by Princu7** [comment]
@LeeCareGene Great work. You seem to have removed most of the problems. Just one problem. Can you please check why your image appears on the right-hand side of the second row instead of being on the left.
Thanks. And one more tip, once you are done with a task, you need to click on the submit for review button so someone can review and approve it.

**Review by Princu7 — APPROVED** [review]

**Review by Princu7 — CHANGES_REQUESTED** [review]
Please check the position of the image in the students section. Also it seems like some merge conflicts have appeared. Try to remove them. Here is a video which explains about the same
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by Princu7** [comment]
@LeeCareGene It's great to see you constantly trying. I tried to look at the error and it seems to be fixed by the setting the _float_ property of _.row .col-lg-3_ to _right_ instead of left. You can find it in the _main.css_ file. Cheers!!. Correct it and make a new pull request with the commits squashed since the number of commits in this request has grown too much to be included in the main branch. Thanks!!

**Comment by Dodecane** [comment]
Can you help me with resolving the merge conflicts?

**Comment by Princu7** [comment]
@LeeCareGene I am a little busy with exams right now so can't thoroughly guide. Sorry. But you can look at the video I posted earlier about removing the conflicts. Also first make sure that your photo is aligned with the current structure of the site. After that, you can work on removing the conflicts. Cheers.

Merge conflicts video
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by Princu7** [comment]
@LeeCareGene I have looked at your code. You need to add your information inside the second div row itself. You don't need to create another div row or add outside the second div row. 
This part should be inside the second row div
```
<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
                            <div class="grid">
                              <figure class="effect-gcihover">
                                  <img src="images/leecaregene.jpg" alt="Lee Care Gene">
                                  <figcaption>
                                      <h2><span>Lee</span> Care Gene</h2>
                                      <p>
                                          <a href="https://www.facebook.com/lee.caregene" target="_blank"><i class="fa fa-facebook" aria-hidden="false"></i></a>
                                          <a href="https://github.com/LeeCareGene" target="_blank"><i class="fa fa-github" aria-hidden="false"></i></a>
                                          <a href="https://twitter.com/LeeCareGene" target="_blank"><i class="fa fa-twitter" aria-hidden="false"></i></a>
                                      </p>
                                  </figcaption>
                              </figure>
                            </div>
                        </div>
```

**Comment by Princu7** [comment]
@LeeCareGene Everything is fine now. Close the second row div. That's why the site looks weird. You have not closed the second row div.

**Comment by Dodecane** [comment]
I think i already fixed the students.yml file but it still says it is conflicting.

**Comment by Princu7** [comment]
@LeeCareGene Great. Finally, your website looks good. Now you only need to remove merge conflicts. 
Read the below link to get an idea
https://githowto.com/resolving_conflicts

It seems that you have two open PR's for the same task(this one and #44). Please close any one of them. 
Also since there have been too many commits for this pull request, you should squash all these commits into one and send a new request. You can learn about squashing the commits here
https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

**Review by Princu7 — APPROVED** [review]

**Comment by daminisatya** [comment]
Merge conflicts! :)

**Comment by Princu7** [comment]
@LeeCareGene Just one more conflict remaining. Way to go.!!

**Comment by Dodecane** [comment]
It conflicts everytime i try to add my own data into the index

**Comment by Princu7** [comment]
@LeeCareGene Did you pull from the main repository and then made a pull request? If you don't, then it may show merge conflicts.

**Comment by Dodecane** [comment]
how do i do so?  Make a pull request on Github?

**Comment by Dodecane** [comment]
Nvm found it

**Comment by Dodecane** [comment]
Thanks for the help :)

**Comment by Princu7** [comment]
@LeeCareGene Wow. You finally did it. Great work. You deserve a cookie. Just one little problem. The number of commits in this pull request are very much and it won't be a good idea to directly merge into the main branch. You have to just squash the commits into one. Here is the link which shows how to squash.
https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit
 
When you have squashed the commits into one, make a new pull request with a link to your task. Cheers!!

**Review by Princu7 — CHANGES_REQUESTED** [review]
Just squash the commits into one and send a new request. Thanks.

**Comment by hemantjadon** [comment]
Oh boy another Conflict! 

Well worry not. Just resolve this with a calm mind.

And you will probably have to squash the commits as they are way too high.
Refer to this video for how to squash the commits.
https://www.youtube.com/watch?v=qh9KtjfjzCU

You have done all the hardwork till here just try and finish it up 
Cheers :)

**Comment by Dodecane** [comment]
Done. (just hope someone doesn't make changes before i'm done squashing)

**Comment by Dodecane** [comment]
Squashing doesnt work. It keeps showing errors like this:
```error: could not apply 4790f70... Update index.html

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply 4790f7006c5b608b46b473242c86ebe6ae6e8901... Update index.html
```

**Comment by hemantjadon** [comment]
When this appears it means that you have `reabase conflicts`

* Fire up the code editor and resolve the conflicts.

* These are just like merge conflicts but in your own code

* Think carefully about which part of code to keep and which not to.

**Comment by Dodecane** [comment]
I don't understand

**Comment by Dodecane** [comment]
Can someone help me?

**Comment by hemantjadon** [comment]
Hey Worry not,
https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by Dodecane** [comment]
But every single commit gives this error

**Comment by Dodecane** [comment]
and if i do `rebase -i HEAD~3` it gives me more than 10 commits and even if I don't do any changes it still shows the error

**Comment by hemantjadon** [comment]
* You will have to keep doing this for all commits

* you can take an easier path in this case but it will lead to loss of your work. 
 
   * Discard all the changes you made 

   * refork the repo now make changes again and 

   * submit a new PR

* Keep in mind that this can be done only in this scenario when your work is not big.

* This is definitely **NOT** a best practice.

* One day or another you will have to learn how to squash commits effectively.

Cheers :)

**Comment by Dodecane** [comment]
I'm pretty sure its not a problem with merging. Commits I didn't commit also show up

**Comment by Princu7** [comment]
@LeeCareGene Sorry. I was preparing for the exam and not able to respond. Please follow what @hemantjadon is saying. If it seems too difficult, then you should discard all changes you have made(maybe keep them saved in some file so you don't have to write them again). Refork the repo and make new changes. As Hemant Sir stated, this is definitely not a good practice, but you have already done much work on this task and must be feeling quite frustrated/exhausted. So do what you feel like. No one will mind or judge. Cheers!!

**Pull request closed without merging**
