### PR TITLE
Zahari Asparuhov

### PR DESCRIPTION
**Pull request by zahariasp**
new Student and Student project added

### CODE REVIEW

**Comment by m1guelpf** [comment]
@zahariasp 
```
The image ./images/students/dewansh.jpg is larger than 240px x 240px [w x h]
The image ./images/students/zahari.jpg is larger than 240px x 240px [w x h]
The image ./images/projects/MS.jpg is larger than 240px x 240px [w x h]
ImgChecker: There are images which exceed the expected dimensions as specified above
Please resize them sir... Happy coding
```

**Comment by robbyoconnor** [comment]
Why did you merge this @niccokunzmann ?  See [this comment](https://github.com/fossasia/gci16.fossasia.org/pull/541#issuecomment-267110099)...

**Comment by niccokunzmann** [comment]
@zahariasp PLease Can you have a look at the website if everything is correctly displayed?
Also, we have set up warnings if images do not have size we expect because either they are not displayed correctly or they are too big and make the page load slowly.
As @m1guelpf showed. So, if you see anything odd, you can always create another pull-request or issue :)

**Comment by robbyoconnor** [comment]
Let's not merge PRs when there are issues...

**Comment by niccokunzmann** [comment]
@robbyoconnor slack.

**Pull request merged**
