### PR TITLE
Added MBDyn logo

### PR DESCRIPTION
**Pull request by zehata**

### CODE REVIEW

**Comment by pa1pal** [comment]
@zehata Always give PR description.
In this case give the link of your repo's live page.

**Comment by zehata** [comment]
I would like to add an "MBDyn" logo to the page.

**Comment by pa1pal** [comment]
Yes @zehata. Good going. From the live page I mean the gh-pages of your project.
The project gh-pages are in form of username.github.io/reponame. Find your gh-page and give in the comments. Also browse your page for testing your work.

**Comment by zehata** [comment]
https://zehata.github.io/gci16.fossasia.org/

**Comment by pa1pal** [comment]
Nice @zehata. Squash all your commits into one and rename it to something useful like "Added MybDn logo to website".

**Comment by hemantjadon** [comment]
@louisgag Please review the work on logo.

**Comment by zehata** [comment]
Sorry, I'm not sure how to squash

**Comment by hemantjadon** [comment]
@zehata 
This might help you to squash the commits

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an **editor** where you will be asked for every commit whether you want to `pick or squash`. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)Here is something which might help you squash the commits.

**Comment by zehata** [comment]
I tried everything but it refuses to sync. Any idea?

**Comment by hemantjadon** [comment]
@zehata Can you please specify what is the exact error you are facing.

**Comment by zehata** [comment]
Is what i'm doing correct? Btw I have just reduced the colour palette to reduce its size significantly.

**Comment by louisgag** [comment]
The submit logo is fine be me, if the pull request is coherent this can be approved. Cheers. -Louis

**Review by jigyasa-grover — COMMENTED** [review]
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors/logos section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

**Comment by niccokunzmann** [comment]
Hi @zehata have a look here for a squashing tutorial: https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md#squash-commits
Also, when you squashed and merged, you can notify me @niccokunzmann. You have done a lot of work and I hope to see it on the website. If you face problems or feel discouraged, please tell.

**Comment by louisgag** [comment]
Hi Zehata, we'll get this fixed later, perhaps as another task for students more familiar with github and websites. So, please go on with other tasks and don't worry anymore about this issue !

**Pull request closed without merging**
