### PR TITLE
Progressive enhancements to social media section

### PR DESCRIPTION
**Pull request by myfrom**
Related #626. I made the social widgets start loading when users scrolls below Loklak section. It will make the page load faster and don't eat so much RAM unnecessary. My code does not require jQuery or any other library. It is a progressive enhancement so browser that doesn't support this feature willuse a fallback using `onscroll` handler. The feature is going to be a part of web standard and will probably be widely adapted. Here's [compatibility table](http://caniuse.com/#search=intersectionobserver).

[Live link](https://witus13.github.io/gci16.fossasia.org/)
[GCI task](https://codein.withgoogle.com/dashboard/task-instances/5631023930933248/)

### CODE REVIEW

**Comment by abishekvashok** [comment]
image
@Witus13

**Comment by myfrom** [comment]
@Abhi2424shek interesting... What browser are you using (what version)? Also didn't it apper after some time? Also clear cache and reload.

**Comment by abishekvashok** [comment]
@Witus13 still I get the same after reloading cache, I am using Google Chrome v55.0.2883.87 m on Windows 10 ;)

**Comment by myfrom** [comment]
@Abhi2424shek that's really weird as I also use Chrome 55.
Could you please check your console for message like loading social media widgets or something like that. 
I'll dig in it deeper when I'm back home

**Comment by abishekvashok** [comment]
non related to social media

**Comment by myfrom** [comment]
@Abhi2424shek I found it! I used a root relative link which obviously doesn't work on GitHub Pages. It would work on our page as it has it's own domain. I'm changing it only for demo now, should I change it also for the gh-pages branch?

**Review by abishekvashok — APPROVED** [review]
Nice work

**Comment by abishekvashok** [comment]
Please resolve the conflicts

**Comment by Witus13** [comment]
@Abhi2424shek Done, everything should be ok now

**Comment by abishekvashok** [comment]
@robbyoconnor sir can I ask why you are closing and opening the PRs

**Comment by robbyoconnor** [comment]
easy way to trigger travis build

**Comment by myfrom** [comment]
There are some errors because linter doesn't know `IntersectionObserver` API. How to tell it to ignore it?

**Comment by myfrom** [comment]
Thank you, sir

**Comment by robbyoconnor** [comment]
@Witus13 I don't mind helping when I can -- you did the bulk of the work.

**Comment by myfrom** [comment]
@robbyoconnor Can we merge it now?

**Pull request merged**
