### PR TITLE
Add header menu and ribbon, Clean up minor issues in code

### PR DESCRIPTION
**Pull request by gaeun**
This is in reference to issue #142. I also made minor changes to the code and replaced the default blue header with the slider + Github ribbon (just a general design improvement).
Here's a preview: https://gaeun.github.io/gci16.fossasia.org/.
This is the task instance: https://codein.withgoogle.com/dashboard/task-instances/5751507544702976/

### CODE REVIEW

**Comment by rhemon** [comment]
Have a look into the file [CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md). you will need to squash your commits into one

**Comment by rhemon** [comment]
and please add back at the top of index.html file  
```
---
---
```
This is required to run jekyll. In your branch, student, mentor, blog section are not working

**Comment by gaeun** [comment]
@rhemon Ooh, that's why you need the header. I see. Thanks for the reminder 👍

**Comment by hemantjadon** [comment]
@gaeun Hi please fix the Linting bugs in `maintainers.md`

Design seems to be nice 👍

**Comment by gaeun** [comment]
@hemantjadon Not sure what's wrong here? It says there's trailing whitespace on line 20, but I don't see any in the file...

**Comment by hemantjadon** [comment]
@gaeun please check again there is an error at line 20 i have just confirmed

**Comment by niccokunzmann** [comment]
Ups, my fault, I committed this file because I have admin rights and clicked the wrong button.

**Pull request merged**
