### PR TITLE
Issue #197: Add loklak web tweets API

### PR DESCRIPTION
**Pull request by gaeun**
This is for the task https://codein.withgoogle.com/dashboard/task-instances/5399005351641088/ and the issue #197 
Preview here: https://gaeun.github.io/gci16.fossasia.org/

I worked on this collaboratively with @Abhi2424shek and @PolBaladas. Please approve their tasks as well :)

### CODE REVIEW

**Comment by m1guelpf** [comment]
LGTM, but let's wait for Travis.

**Comment by m1guelpf** [comment]
@gaeun Please fix Travis

**Comment by m1guelpf** [comment]
@gaeun Let's wait for Travis

**Comment by gaeun** [comment]
@m1guelpf Ooh I should fix those

**Comment by gaeun** [comment]
I've fixed all the build fails, but the ones that remain occur because of class names in the HTML file. I didn't edit these in my commits, and for those builds to pass, I would have to overhaul the HTML file...

**Comment by abishekvashok** [comment]
@gaeun good job @m1guelpf hit the squash and merge after travis checks finish bro.

**Comment by abishekvashok** [comment]
And mentors here's the link to my task: https://codein.withgoogle.com/dashboard/task-instances/6282283227021312/
@hemantjadon @Princu7 @jig08 @niccokunzmann

**Pull request merged**
