### PR TITLE
Updated index.html adding my info and image

### PR DESCRIPTION
**Pull request by animeshsinghweb**
Updated index.html by adding my info and image to the student section

### CODE REVIEW

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Check for merge conflicts.

Do provide Task and your gh-pages link for quicker review process.

**Comment by animeshsinghweb** [comment]
Task: https://codein.withgoogle.com/dashboard/task-instances/4646195228049408/

**Comment by jigyasa-grover** [comment]
@animeshsinghweb 

* Is your image already in the `images` folder and data in `students.yml` ?
* Rename your commit to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Comment by animeshsinghweb** [comment]
Hey you can check my repo now.
http://gci16.animeshsingh.in/

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Resolve the merge conflicts please. Refer to the slack channel there are many Pinned Messages there which can help you to solve the merge conflicts.
Cheers :)

**Comment by animeshsinghweb** [comment]
@hemantjadon Thanks for your support. I actually I made the changes to the branch gh-pages itself.
Have a look here: https://github.com/fossasia/gci16.fossasia.org/pull/108
Thanks.

**Comment by jigyasa-grover** [comment]
>@hemantjadon Thanks for your support. I actually I made the changes to the branch gh-pages itself.
>Have a look here: #108
>Thanks.

Closing this.

**Pull request closed without merging**
