### PR TITLE
Add Map for Mentors

### PR DESCRIPTION
**Pull request by BrainBuzzer**
Added a single map to locate your mentors. Issue #1 

https://brainbuzzer.github.io/gci16.fossasia.org/

As I don't have any latitude or longitude info it doesn't show any makers the map.

### CODE REVIEW

**Comment by abishekvashok** [comment]
I would close and reopen to check the checks status. Hey there are some errors, some semicolon errors, undeclared variable errors and space inconsistencies,fix them I know you can,

**Comment by BrainBuzzer** [comment]
I've added those just to make it good for eyes. Anyways, I will change it I guess.

**Comment by BrainBuzzer** [comment]
I don't think so that I need to fix anything. It says google is not defined. It is taken from library anyways. Even though I have added a tab but it is considering it as space. (Even though it is configured as tab). And as far as semicolon goes, I'll fix that one.

**Comment by hvardhanx** [comment]
Resolve the conflicts.

**Comment by hemantjadon** [comment]
@BrainBuzzer @royalharsh @Abhi2424shek 
Any Idea why this PR is not going in a `Travis Build`?

**Comment by BrainBuzzer** [comment]
How do I solve them? I don't have any idea what this is?

**Comment by hvardhanx** [comment]
@BrainBuzzer  This should help: [Fix merge conflicts](https://www.youtube.com/watch?v=g8BRcB9NLp4)

**Comment by hvardhanx** [comment]
@hemantjadon This: [Pull Request isn’t being built](https://docs.travis-ci.com/user/pull-requests#My-Pull-Request-isn%E2%80%99t-being-built) .

**Comment by abishekvashok** [comment]
@hemantjadon @BrainBuzzer the tests are not appearing because this commit can't be merged, make it mergable (remove the conflicts) then it will work see the contributions.md file for tutorials, go ahead and do good.

**Comment by hemantjadon** [comment]
@royalharsh Thanks i was guessing this just wanted to make sure 👍

**Review by jigyasa-grover — DISMISSED** [review]
* Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

**Comment by BrainBuzzer** [comment]
I have resolved. And I have already added image in the issue.

Image

**Comment by rhemon** [comment]
@BrainBuzzer your tests failed. its mostly about white spaces i think. you can look into the details. even i dont have a strong understanding of those errors, so if you have problems ask here, even if I cant mentors and other students are available :P 

and also you need to add back this in index.html (at the top of the file):
```
---
---
```
this required for jekyll, as you can see with this removal, in your version of gh-pages you see all these : {% if ... %}. Its happening because by removing that, jekyll doesnt know anymore it has to read and build that file as well, so once you add back those two line at the top it will be working again

best of luck 👍

**Comment by BrainBuzzer** [comment]
Alright. Will be making those changes. I didn't know it was Jekyll.

**Comment by BrainBuzzer** [comment]
Can you please merge this? I'm stuck here for a week and can't take on another task. I've cleared all my errors. If you know how to solve a last few, give me an idea, I'll do it. Everytime it is adding some more merge conflicts and I have to clear them.

**Comment by BrainBuzzer** [comment]
I should add a live link to what? In the commit?

**Comment by m1guelpf** [comment]
@BrainBuzzer In the PR description.
For example: https://brainbuzzer.github.io/gci16.fossasia.org/

**Comment by BrainBuzzer** [comment]
@m1guelpf @jig08 @checkbot Please check this PR. It has only one error and that too is access denied for Danger

    Danger does not have write access to the PR to set a PR status.

I have removed all other errors and everything is normal.

**Comment by m1guelpf** [comment]
@BrainBuzzer Travis log:
```bash
$ docker run --volume=$(pwd):/app --workdir=/app coala/base coala -C
Unable to find image 'coala/base:latest' locally
latest: Pulling from coala/base
Digest: sha256:ca23c780f80469cda6d0e42e0bb1485fc36b45bb0c90e6e6198ff40dc341751a
Status: Downloaded newer image for coala/base:latest
Executing section Default...
Executing section html...
Executing section yaml...
Executing section css...
Executing section js...
[WARNING][10:19:21] Selected default action 'ShowPatchAction' for bear 'JSHintBear' is not applicable. Action not applied.
[WARNING][10:19:21] Selected default action 'ShowPatchAction' for bear 'JSHintBear' is not applicable. Action not applied.
[WARNING][10:19:21] Selected default action 'ShowPatchAction' for bear 'JSHintBear' is not applicable. Action not applied.
[WARNING][10:19:21] Selected default action 'ShowPatchAction' for bear 'JSHintBear' is not applicable. Action not applied.
[WARNING][10:19:21] Selected default action 'ShowPatchAction' for bear 'JSHintBear' is not applicable. Action not applied.
[WARNING][10:19:21] Selected default action 'ShowPatchAction' for bear 'JSHintBear' is not applicable. Action not applied.

javascripts/main.js
|   5| ••mentors•=•jsyaml.load(f);
|    | [NORMAL] JSHintBear:
|    | 'jsyaml' is not defined.

javascripts/main.js
|   8| ••var•map•=•new•google.maps.Map(document.getElementById('map'),•{
|    | [NORMAL] JSHintBear:
|    | 'google' is not defined.

javascripts/main.js
| 238| ••••marker•=•new•google.maps.Marker({
|    | [NORMAL] JSHintBear:
|    | 'google' is not defined.

javascripts/main.js
| 239| ••••••position:•new•google.maps.LatLng(mentor.lat,•mentor.lng),
|    | [NORMAL] JSHintBear:
|    | 'google' is not defined.

javascripts/main.js
| 242| ••••var•infowindow•=•new•google.maps.InfoWindow();
|    | [NORMAL] JSHintBear:
|    | 'google' is not defined.

javascripts/main.js
| 244| ••••google.maps.event.addListener(marker,•'click',•(function(marker,•content,•infowindow)•{
|    | [NORMAL] JSHintBear:
|    | 'google' is not defined.


The command "docker run --volume=$(pwd):/app --workdir=/app coala/base coala -C" exited with 1.
```

**Review by m1guelpf — CHANGES_REQUESTED** [review]
Please fix the Travis build

**Comment by BrainBuzzer** [comment]
@m1guelpf  @jig08 @royalharsh What should I fix in it? Should I remove JSHintBear from it?

**Comment by abishekvashok** [comment]
@m1guelpf he cant fix more, the variables would be initialized from another script we could let him pass, we don't have to pass all checks to merge the PR and in this case the variables are defined is'nt it [from the google library for maps]. @BrainBuzzer don't remove bears they are really precious and are on the verge of extinction :P and clam down bro.

**Comment by m1guelpf** [comment]
@Abhi2424shek You're rigth

**Comment by abishekvashok** [comment]
@m1guelpf good work, make sure you properly reviewed it.

**Comment by abishekvashok** [comment]
Oh no!
Now the issues are spread over the whole of repo, ok since I caused them i would get in a fix sorry guys.

**Comment by BrainBuzzer** [comment]
Where are the issues?

**Pull request merged**
