### PR TITLE
Few fixes and improved Design v2 section

### PR DESCRIPTION
**Pull request by ankitrgadiya**
* Design V2 section is more like previous Design section.
* Design V2 section photo optimised.
[Live version](http://ankitrgadiya.me/gci16.fossasia.org)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Previews

**Comment by abishekvashok** [comment]
Comparing old and new ones would make it easy reviewing

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Sure!
Previously
screenshot from 2016-12-17 21-49-44
My version
screenshot from 2016-12-17 21-49-39

**Comment by ankitrgadiya** [comment]
Previously
screenshot from 2016-12-17 21-51-22

My version with hover
screenshot from 2016-12-17 21-51-28

My version without hover
screenshot from 2016-12-17 21-51-30

**Pull request merged**
