### PR TITLE
Add 2 mentors to mentor section

### PR DESCRIPTION
**Pull request by gaeun**
This is the task: https://codein.withgoogle.com/dashboard/task-instances/4853271573299200/.
Here's a preview: https://gaeun.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by hemantjadon** [comment]
Please check for the failing build. Here are your build logs
https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181108670

**Comment by Will747** [comment]
Where can i find a list of mentors?

**Review by jigyasa-grover — COMMENTED** [review]
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Review by abishekvashok — COMMENTED** [review]
Dont put empty details, like Facebook:
Add only known things or enquire leaving things empty will in the website return you to Facebook.com and other sites!

**Comment by hemantjadon** [comment]
@gaeun Are you having some trouble with squashing in this PR?

**Comment by gaeun** [comment]
@hemantjadon Squashed all the commits, and I don't think there are build conflicts anymore. Thanks :)

**Comment by hemantjadon** [comment]
Ohh great work @gaeun :)

**Pull request merged**
