### PR TITLE
Adding my photo

### PR DESCRIPTION
**Pull request by kishanshetty1991**
need to add as per as the task in GCI

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by kishanshetty1991** [comment]
Adding Photo to GCI students as per as given task

**Comment by gaeun** [comment]
@kishanshetty1991 A few things: 1) Your comment here needs to be added to students.yml, not the PR. 2) Please replace the default text under "Things done in this Pull Request". 3) Include a live link or a screenshot of your changes. (Your live link can be accessed at http://username.github.io/gci16.fossasia.org/)
A thorough read of CONTRIBUTING.md would help you here.

**Comment by Elgayar** [comment]
Also, please solve the conflicts. @kishanshetty1991

**Comment by robbyoconnor** [comment]
Merged and fixed all issues with trailing whitespace in 8d2690b

**Pull request closed without merging**
