### PR TITLE
Added two new mentors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oanarosca** [comment]
Hello! Please solve the conflicts so we can merge your changes :smile: See [CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) if it is unclear to you how to do this, you'll find a video tutorial explaining this aspect.

**Comment by ghost** [comment]
I think I've solved the conflict

**Comment by ghost** [comment]
Is this OK or do i need to do something else to it?

**Comment by jigyasa-grover** [comment]
Not yet, conflicts are still there :)

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
* Are the corresponding images already there in `images` folder ?
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Pull request closed without merging**
