### PR TITLE
Added photo and information

### PR DESCRIPTION
**Pull request by manastaneja**
Thank you for your pull request! Please read and

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request (replace the text as instructed)

- Added my information and photo for students section of Fossasia's website.
Live link of the task: 
https://codein.withgoogle.com/dashboard/task-instances/5689112885460992/

### CODE REVIEW

**Comment by abishekvashok** [comment]
You are learning nice work...

**Comment by manastaneja** [comment]
@Abhi2424shek thanks. my pull request seems to be merged but my task is not accepted/closed yet. I have put up the link of the task in the PR body. please look into it . Thank you Sir.

**Comment by abishekvashok** [comment]
I am a student wait till some mentors look for it. No need to call me sir and beside to ping me when the need arises.

**Comment by robbyoconnor** [comment]
@Abhi2424shek This broke the build.

**Comment by robbyoconnor** [comment]
@fossasia/gci16-maintainers ALWAYS check why the build is failing and if it's failing **DO NOT MERGE**

**Pull request merged**
