### PR TITLE
Sayam Kanwar

### PR DESCRIPTION
**Pull request by sayamkanwar**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- I have uploaded my photo in the images folder and added my description in students.yml file. I have also tweeted about this on twitter.

### CODE REVIEW

**Comment by sayamkanwar** [comment]
Name: Sayam Kanwar, All sub tasks done which were asked!

**Comment by codein-dwij** [comment]
Please include a description in your PR :)
Also your PR name should be in this way "Adding [name_of_student/mentor] in Student/Mentor Section" or somewhat similar

**Comment by sayamkanwar** [comment]
name: Sayam Kanwar
  github: SayamK
  image: Sayam.jpg
  twitter: sayamkanwar
  facebook: sayamkanwar
  bio: 14, Web Designer, Web Developer, Quizzer
  lat: 28.667720
  lng: 77.064309

**Comment by sayamkanwar** [comment]
Sir, could you please review my work now as I need to claim other tasks too! :)

**Comment by m1guelpf** [comment]
@SayamK Let's wait for Travis

**Comment by codein-dwij** [comment]
Hello, You still did not understand what I mean to say
In your PR body , you need to add a description of changes you have done.

>  Things done in this Pull Request

                         Replace this with your change description


You will find this in your PR body

**Comment by sayamkanwar** [comment]
Okay Sir

**Comment by codein-dwij** [comment]
and yeah I am no mentor.. student like you(14 yrs old turning 15 next month)

**Comment by m1guelpf** [comment]
@codein-dwij @SayamK Same for me, you'll have to wait.

**Comment by sayamkanwar** [comment]
Sir, my pull request has been merged but still I am not able to claim other tasks, could you please help?

**Comment by codein-dwij** [comment]
You need to wait for a mentor to review the task which can take upto 24hrs. As said above we are not mentors :)

**Comment by sayamkanwar** [comment]
Okay

**Pull request merged**
