### PR TITLE
updating info

### PR DESCRIPTION
**Pull request by arpnakumari**

### CODE REVIEW

**Comment by gaeun** [comment]
Great! Next time, can you provide a live link so that we can preview the changes you made?

**Comment by gaeun** [comment]
@arpnakumari Oh, it seems like you didn't add an image of yourself to the images folder. Can you add arpna.jpg to the images so that your photo shows up on the website?

**Comment by arpnakumari** [comment]
@gaeun thanks for merging. added my image at required place. can you help me with  live link?

**Comment by gaeun** [comment]
@arpnakumari Sure! Live links can usually be accessed at http://your_username.github.io/reponame/.
So in my case, it's http://gaeun.github.io/gci16.fossasia.org/

**Comment by arpnakumari** [comment]
@gaeun can you link down any documentation page on live link ?

**Pull request merged**
