### PR TITLE
[WIP]Travis fix

### PR DESCRIPTION
**Pull request by m1guelpf**
Issue #566

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
0 file changed?

**Comment by abishekvashok** [comment]
Let's wait for trqvis

**Comment by abishekvashok** [comment]
And is it a WIP

**Comment by m1guelpf** [comment]
@niccokunzmann I fixed the jekyll build, but image is failing.

**Comment by animeshsinghweb** [comment]
@m1guelpf Which image (is causing troubles)?

**Comment by abishekvashok** [comment]
That's not a problem since you fixed Jekyll that should do it.

**Comment by m1guelpf** [comment]
Seems that the important things are fixed. Maybe I'll open another PR later fixing coala.
As I can merge and this needs a quick fix, can someone merge?
ping @niccokunzmann @animeshsinghweb @Abhi2424shek @fossasia/gci16-maintainers

**Pull request merged**
