### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by raghavdhingra**

### CODE REVIEW

**Comment by gaeun** [comment]
Can you provide a live link, or squash your commits if possible?

**Comment by abishekvashok** [comment]
Squashing is ok what is the first image named after a date for ☺

**Comment by ankitrgadiya** [comment]
@raghavdhingra Why is .lnk file added?? and if you want to add your photo in Students section you'll have to add your info in students.yml file according to instructions [here](https://github.com/fossasia/gci16.fossasia.org/#adding-yourselves-to-student-section)

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Add your image to /images/students at 240x240 dimensions and add your details to the student.yml file. You can surely do it keep up the good work ;)

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
Add an image at 240x240 -- anything more is not good. Also clean this up...

Your filenames are not good either. Please change those.

**Comment by robbyoconnor** [comment]
You need to clone the repository on your computer, make changes there, and then push them up. The current state of this PR is not good. I am going to close it. Please make a new one with the proper filenames at *240 x 240 [w x h]*.

**Pull request closed without merging**
