### PR TITLE
Added ignore statements to let the travis build properly

### PR DESCRIPTION
**Pull request by abishekvashok**
@Princu7 please review and merge

### CODE REVIEW

**Comment by abishekvashok** [comment]
Error please go away :P

**Comment by m1guelpf** [comment]
@Abhi2424shek Can you explain what you're trying to do?

**Comment by abishekvashok** [comment]
Trying to save others from JSHintBear Error. Actually @BrainBuzzer could'nt do anything with the variables but he could have added an ignore case, and that's what I am doing for other ;) so that their tests won't fail cause we merged a PR whose tests failed.

**Comment by m1guelpf** [comment]
@Abhi2424shek So, I merge it, wait for @Princu7 or what?

**Comment by abishekvashok** [comment]
No problems, let's see if we could make JSHintBear ignore those errors cause they wont appear on the website @m1guelpf

**Comment by m1guelpf** [comment]
@Abhi2424shek Travis passed, merge?

**Comment by abishekvashok** [comment]
Now yes, I see the checks passing, can you know please merge it so everyone's tests would now appear properly. If u r not sure @m1guelpf wait for a mentor like @Princu7 or @hemantjadon.

**Pull request merged**
