### PR TITLE
Adding credential of GCI16 student

### PR DESCRIPTION
**Pull request by AlexTurning**

### CODE REVIEW

**Review by daminisatya — CHANGES_REQUESTED** [review]
Great to see your first patch :D but according to the task you must provide with your image too :)

**Comment by daminisatya** [comment]
You also have a merge conflict, if any doubt on how to clear the conflict, feel free to ask !

**Comment by daminisatya** [comment]
@AlexTurning This can help you resolve the conflicts :)
https://www.youtube.com/watch?v=g8BRcB9NLp4

**Comment by jigyasa-grover** [comment]
@AlexTurning Updates on this pls ?

**Comment by niccokunzmann** [comment]
Closing because of https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md

**Pull request closed without merging**
