### PR TITLE
This isn't meant to ever be merged

### PR DESCRIPTION
**Pull request by robbyoconnor**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request (replace the text as instructed)

- Replace this with your change description

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Okay that works

**Comment by abishekvashok** [comment]
Yep but isn't the danger log a bit large i mean see the number of times there's the line whoch states to fix line endings

**Comment by robbyoconnor** [comment]
@Abhi2424shek, fixing that now.

**Comment by abishekvashok** [comment]
Go on keep up the good work! 👍

**Comment by robbyoconnor** [comment]
gg

**Comment by robbyoconnor** [comment]
\o/

**Comment by robbyoconnor** [comment]
This is a github bug that file uploads don't respect .gitattributes in the repository... this fixes a gripe I had with students.

**Comment by abishekvashok** [comment]
Looks fine shall we close this! 👍

**Comment by robbyoconnor** [comment]
Not yet

**Comment by robbyoconnor** [comment]
@Abhi2424shek after this build goes red -- we can close it.

**Comment by robbyoconnor** [comment]
:grinning: :grinning: :grinning: :grinning: :grinning: :grinning: :grinning: :grinning: :grinning:

**Comment by abishekvashok** [comment]
👍 🕹

**Pull request closed without merging**
