### PR TITLE
Update blogs.yml

### PR DESCRIPTION
**Pull request by anastasia200010**
https://anastasia2000.edublogs.org/

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@anastasia200010 LGTM. Can you provide me the live GH-Page link of your repo or an image which demonstrate your PR?

**Comment by anastasia200010** [comment]
https://www.facebook.com/radac.anastasia

**Comment by animeshsinghweb** [comment]
@anastasia200010 I meant your live GH-Page like `http://yourusername.github.io/yourRepoName` or something like that where I can investigate. 👍

**Comment by animeshsinghweb** [comment]
@anastasia200010 are you having any problem? Let me know.

**Comment by abishekvashok** [comment]
Nice clean code @anastasia200010 @animeshsinghweb why are we waiting lets merge this then.

**Comment by anastasia200010** [comment]
https://github.com/anastasia200010?tab=repositories

**Comment by animeshsinghweb** [comment]
@anastasia200010 I didn't meant that, anyways you Pull Request is now merged.
Happy Coding, Happy Learning.

**Comment by abishekvashok** [comment]
@anastasia200010 @animeshsinghweb means this url don't forget this: https://anastasia200010.github.io/gci16.fossasia.org

This is the url provided for your repo by github, github will only provide such urls if it's hosted on the gh-pages branch. This is the format:
`https://<username>.github.io/<repository_name>`

If you have any doubts feel free to ask here we are all here to help you or pling us on slack.

**Pull request merged**
