### PR TITLE
Get students from _data/students.yml

### PR DESCRIPTION
**Pull request by webhaikal**
Rather than having a students data static, why not use the _data/students.yml file already available? Previous PR was #83. Made this new PR for easier readability and squashed commits. @hemantjadon 

Preview: https://webhaikal.github.io/gci16.fossasia.org/

### CODE REVIEW

**Review by Princu7 — APPROVED** [review]
Idea seems fine to me. But the pictures in the students section don't seem to be appearing. Can you please check it.  @hemantjadon @jig08 @daminisatya Please give your reviews.

**Comment by hemantjadon** [comment]
@webhaikal 
There was no need to change PR. But now as you have done it, Please check the following:

* Merge conflicts

* Why some of the images are not fetching in site. (Your previous PR was working good)

**Comment by webhaikal** [comment]
@hemantjadon The pictures aren't showing because some of the students are using this "../images/student-pic.png" rather than having just "student-pic.png". Also I suggest to merge this first before merging other commits that changes the index.html.

Saw that some PRs made by students are adding their credentials to the index file directly.

**Comment by hemantjadon** [comment]
* Please edit those entries which seems falsy.

* Resolve the merge conflict.

* We will then merge this ASAP.

**Review by jigyasa-grover — COMMENTED** [review]
@webhaikal 

This [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

**Comment by shubham-padia** [comment]
@webhaikal This issue has been resolved in another pull request. Please close this.

**Comment by hemantjadon** [comment]
@webhaikal
Please also add your info to students.yml.(you may use a different PR)
Also provide the task link after adding your info so we can approve

**Comment by webhaikal** [comment]
@hemantjadon my info is already in students.yml and already completed the task

**Comment by hemantjadon** [comment]
@webhaikal 
Please send your task for review, If you already have please provide the link

**Pull request closed without merging**
