### PR TITLE
Make latest issue section more compact and make it into a three colum…

### PR DESCRIPTION
**Pull request by abhishek1995s**
screenshot from 2017-04-05 12-09-45

### CODE REVIEW

**Comment by abishekvashok** [comment]
Pls check the failing tests :)

**Comment by abhishek1995s** [comment]
@Abhi2424shek its working perfectly fine in my local system. Is there any way to know why its failing test

**Comment by abishekvashok** [comment]
Yea, see the Travis section at the end of the PR or go to the Travis CI dashboard.

**Review by abishekvashok — APPROVED** [review]
Build is failing because of bad credentials and this one is fine

**Pull request merged**
