### PR TITLE
Added my blog to _data/blogs.yml

### PR DESCRIPTION
**Pull request by Jerry2001**

### CODE REVIEW

**Comment by Princu7** [comment]
@Jerry2001 Thanks for the request. You also need to include some more things in your pull request

* Always include the link to the task which you are completing through this pull request. Also, post the link to your live gh-pages or relevant screenshot for easier and faster reviewing.

* Squash your two commits into one and rename it to something useful like "Added Jerry2001 to blog section". 

* If you need any help regarding the squashing or any other issues, you can ask us here or in the slack or gitter channel.

**Comment by Princu7** [comment]
@Jerry2001 As you might be seeing, your pull request has failed the Travis test. No problem. It appears that your code has some trailing whitespaces due to which the Travis build is failing. You can look at the details section of the build to get more information regarding it.

**Comment by niccokunzmann** [comment]
@Jerry2001 What are your thoughts, how would you like to go on?

**Comment by niccokunzmann** [comment]
@Jerry2001 Thanks for your contribution! If you like, you can also join the slack channel as described here: https://github.com/fossasia/gci16.fossasia.org#finding-support

**Comment by niccokunzmann** [comment]
@Jerry2001 can we close #259 now?

**Pull request merged**
