### PR TITLE
Improved Footer

### PR DESCRIPTION
**Pull request by ankitrgadiya**
Original
screenshot from 2016-12-27 00-18-05
Changed
screenshot from 2016-12-27 00-18-17

```<!-- Safe Edit -->```

### CODE REVIEW

**Comment by Elgayar** [comment]
Can you please provide a live link instead of a screenshot? @ankitrgadiya

**Comment by ankitrgadiya** [comment]
@Elgayar I did it on separate branch actually.

**Comment by Elgayar** [comment]
Anyways, if that's your live link: https://ankitrgadiya.github.io/gci16.fossasia.org/
Then it's not working, try reviewing your code again. @ankitrgadiya

**Comment by ankitrgadiya** [comment]
@Elgayar Again I did it on separate branch, if you want I can serve from that branch temporarily.
[Branch](https://github.com/ankitrgadiya/gci16.fossasia.org/tree/Feat/Footer)

**Comment by oanarosca** [comment]
The background color of the footer should stay `#e12b00`, since it's the standard color used in all FOSASSIA pages, as stated by Jigyasa in an older issue, and another mentor suggested that the link icon color should be left black.

**Comment by ankitrgadiya** [comment]
Don't get me wrong but @oanarosca  Black link colors are surely not looking good. About the footer color, as we are using material design so I picked up one from there. As we are working on a website our aim should be to make it good looking, is what I think.
@Elgayar [Live Link](https://ankitrgadiya.github.io/gci16.fossasia.org/)

**Comment by ankitrgadiya** [comment]
Or we can pick colors like this.
screenshot from 2016-12-27 02-11-00
This way we'll we able to keep black links and it will match Fossasia's main website.

**Comment by abishekvashok** [comment]
Hey @ankitrgadiya you can still post a live link if you are on another branch

Just go to repository settings of your fork and under Cname i think you will find the option to select which branch you want to deploy. Check it out and give out the live link.

And about the colour schemes as some mentors stated according to @oanarosca you could follow up the design of the Fossasia.org website but I don't have a good attitude towards cloning it down instead I love to have more creativity here

**Comment by robbyoconnor** [comment]
That will then be included in his PR.

**Comment by robbyoconnor** [comment]
I like it being White.

**Comment by robbyoconnor** [comment]
I retract my opinion

**Comment by robbyoconnor** [comment]
I'm 50/50 on this -- I like it -- but I'm not really a part of FOSSASIA (only during Google Code-In) -- so @jig08 -- what's your opinion? It's very clean in my opinion...

**Comment by jigyasa-grover** [comment]
@robbyoconnor I like the preview provided here https://github.com/fossasia/gci16.fossasia.org/pull/708#issuecomment-269240510
@ankitrgadiya I'd like to see a clean design similar to this :)
Cheers !

**Comment by abishekvashok** [comment]
@ankitrgadiya now you know what to do, code!

**Comment by ankitrgadiya** [comment]
@jig08 @Abhi2424shek  I'll do it. Thanks

**Comment by ankitrgadiya** [comment]
@jig08 @robbyoconnor @Abhi2424shek @Elgayar How's this guys
screenshot from 2016-12-27 17-47-09


[Live Preview](https://ankitrgadiya.github.io/gci16.fossasia.org/)

**Comment by abishekvashok** [comment]
@ankitrgadiya awesome!

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Thanks

**Pull request merged**
