### PR TITLE
foto to mentor section

### PR DESCRIPTION
**Pull request by ghost**
foto

### CODE REVIEW

**Comment by Princu7** [comment]
@Thanks for the request. Please do the following task
* A link to your gh-pages for faster and easier reviewing of the request.
* Add the link of the task(if any) which you are completing through this request so I can approve it.
Cheers!!

**Comment by ghost** [comment]
https://nolik2000.github.io/gci166.fossasia.org/

**Comment by ghost** [comment]
I have fixed it

**Comment by hemantjadon** [comment]
@nolik2000 
Task Link Please So we can approve (If you have completed other part of task)

Nice Work :)

**Comment by niccokunzmann** [comment]
Task Link: https://codein.withgoogle.com/dashboard/task-instances/5206744831623168

**Comment by ghost** [comment]
@hemantjadon  thanks))

**Pull request merged**
