### PR TITLE
Fixes #117 (blogs section)

### LINKED ISSUE #117: Suggestion: Make the UI more consistent
I noticed a bit of inconsistency in the UI of the website. The students and blog post sections were very different in design compared to the mentors and contributors section. First of all, the students section, doesn't have the separate box that sticks out to show the title. Secondly, the contributor and mentor sections have a material design card look, while the students section doesn't. The cards on the student section have the names on top of the pictures causing the text to be less visible to the user. The padding is also a lot different on the students section, there is nearly no padding on the very left, very right and on the very bottom. The animations for the social media links is significantly different from the one used in the mentors section and the box around the social media links is offset whenever the name of a student exceeds more than a line. The text that says student is not all uppercase and also has a shadow unlike the top two sections. For the students section, I highly suggest reusing the mentors section with the student profile pictures, names and social media links. The blog post section has different padding from the other sections and also doesn't retain the material design card style. The font, once again, is not all uppercase and the divs that have the blog posts in them don't seem to be scaling properly with blog post titles that have lots of characters. 

- [x] Students section consistent with the design of the other sections
- [x] Latest Issue section title needs to be part of the actual box.
 
- [x] MBDyn logo section consistent with the design of the other sections
- [ ] Blog Post section consistent with the design of the other sections

These are all the things that I noticed on the version that is up on the [Fossasia website](http://gci16.fossasia.org).

### PR DESCRIPTION
**Pull request by myfrom**
My changes related to #117 - I modified the blogs section to make it look more unified with the rest of UI.  
[Demo](https://witus13.github.io/gci16.fossasia.org/)  
[My GCI task](https://codein.withgoogle.com/dashboard/task-instances/5483972958093312/)

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Can you resolve the merge conflict?

**Comment by niccokunzmann** [comment]
When the PR is merged, it makes sense to submit the task.

**Comment by myfrom** [comment]
OK, I'll work on it when I get to my computer. Thanks for the advice! I haven't submitted yet, only commented on it with relatable links.

**Review by jigyasa-grover — COMMENTED** [review]
* Squash all your commits into one
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

**Comment by myfrom** [comment]
The demo link is up there.

Also, could you please help me? I had some mess in my local repository so I cleaned it up (delted it) and ran `git pull git@github.com:Witus13/gci16.fossasia.org.git gh-pages` and then `git rebase -i HEAD~3` but instead of what I expected (list of my three commits) I saw this 
screenshot 2016-12-07 at 20 05 59  
What have I done wrong?

**Comment by niccokunzmann** [comment]
Everything is fine. Probably, one of the commits is a merge commit. The merge commit includes a lot of other commits. You can squash a lot of them. I think, beginning from your first commit, to the top and then use a nice message for that.

**Comment by myfrom** [comment]
I messed up, I'll start a new PR tomorrow

**Pull request closed without merging**
