### PR TITLE
Adding navbar and photo

### PR DESCRIPTION
**Pull request by alejoheredia**

### CODE REVIEW

**Comment by alejoheredia** [comment]
preview: https://heredroky.github.io/gci16.fossasia.org/index.html

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Please match the size of the photo on the site with others

**Comment by alejoheredia** [comment]
What's the size?

**Comment by hemantjadon** [comment]
@Heredroky 
The size similar to photos of other students

**Comment by jigyasa-grover** [comment]
Also, Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

**Pull request closed without merging**
