### PR TITLE
Add Swagger_to_Markdown

### PR DESCRIPTION
**Pull request by PolBaladas**
Add Swagger_to_Markdown

https://codein.withgoogle.com/dashboard/task-instances/6404475510063104/

TODO: Improve displaying parameters.

### CODE REVIEW

**Comment by hemantjadon** [comment]
Nice work @PolBaladas 

Cheers :)

**Comment by PolBaladas** [comment]
Thanks!

**Comment by PolBaladas** [comment]
Any ideas on how to improve displaying params @hemantjadon @rafalkowalski ?

http://www.jsoneditoronline.org/?id=3029fc0a2433c239c71124dcac86d220


[SwaggerToMarkdown.pdf](https://github.com/fossasia/gci16.fossasia.org/files/625617/SwaggerToMarkdown.pdf)

**Comment by rafalkowalski** [comment]
@PolBaladas maybe you can iterate via params and then display it 
```key: value```

**Comment by PolBaladas** [comment]
Yeah I did that with a recursive function that went all over the JSON. I think that given a specific value the script decides to be tired and stop doing the recursive thingy.

I think i'm about to fix it... Thanks!

**Comment by PolBaladas** [comment]
Did it! Yay

**Comment by rafalkowalski** [comment]
Good job! But change folder name Swagger_to_Markdown to swagger_to_markdown/ to scripts/swagger_to_markdown/. Remove one dot from swagger..markdown

**Comment by PolBaladas** [comment]
Done!

**Comment by PolBaladas** [comment]
Thanks!

**Pull request merged**
