### PR TITLE
Changing the image type

### PR DESCRIPTION
**Pull request by zahariasp**
Changing the image type
http://gci16.fossasia.org/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Please resize your pictures dimensions -- it's not 1:1 and that's why it's skewing.

**Comment by niccokunzmann** [comment]
@zahariasp There does not seem to be a change in this pull-request. https://github.com/fossasia/gci16.fossasia.org/pull/544/files
What would you like to achieve? You can close it if you like.

**Comment by niccokunzmann** [comment]
I saw it! Thanks!

**Comment by niccokunzmann** [comment]
Can you give me that link to the task again, so I can accept?

By the way: I will update the task, so it says that it must be quadratic and maximum 240x240. Because that the the maximum size allowed by the tests at this point. If you like, you can create another PR to speed up the website.

**Pull request merged**
