### PR TITLE
Get students from _data/students.yml

### PR DESCRIPTION
**Pull request by webhaikal**
Rather than having a students data static, why not use the _data/students.yml file already available?

Preview: https://webhaikal.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by jayvdb** [comment]
:+1:  We will need to revise the task a little, but IMO it makes sense to avoid lots of merge conflicts, and we should be showing the participants how to build things correctly, without unnecessary duplication.

**Comment by hemantjadon** [comment]
@webhaikal Great PR
as mentioned by @jayvdb We will need to revise the task before merging this PR.

Keep Coding :)

**Review by hemantjadon — APPROVED** [review]

**Comment by daminisatya** [comment]
I feel this is required to reduce extra work! Please try to get in this ASAP!

**Comment by hemantjadon** [comment]
@webhaikal Just fixup the merge conflicts so that we can merge this.

**Comment by webhaikal** [comment]
@hemantjadon I've fix the merge conflicts. Don't know how to squash these commits when it is pushed though..

**Comment by hemantjadon** [comment]
Hey @webhaikal 

* There are some linting errors also, you can use coala to fix them.

* Also for squashing commits see this video

https://www.youtube.com/watch?v=qh9KtjfjzCU

* The squashing process is similar to merging but with one extra step

See these documented tutorials: 

* https://www.atlassian.com/git/tutorials/rewriting-history/

* https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by webhaikal** [comment]
@hemantjadon that means just after squashing do git push --force? Shouldn't doing that messes up the tree?

**Comment by hemantjadon** [comment]
@webhaikal 
It should not.

Though it is not a best practice to do a force push, but it will not effect the tree in this case In my opinion.

* The best practice is to use `git commit -amend` to have all your changes in one commit.

* And submit the PR only when you are satisfied that your changes are good, and will not require further modification.

* Though the Best practice is not followed, this is still a good PR, And try to follow the best practices in future.

* Keep in mind that you fix the `Build Errors` before squashing so that both problems are solved.

* For solving `Build Errors` please check `coala` for how to fix linting errors automatically

**Comment by hemantjadon** [comment]
Closing this as New PR has been opened #109 

@webhaikal 
There is no need to open up new PR's when you have the old ones.

* This results in loss of communication (Messages and points get lost in between)

* You should fix the issues with the code in same PR itself

**Pull request closed without merging**
