### PR TITLE
Added: My photo in Student section

### PR DESCRIPTION
**Pull request by ankitrgadiya**
My Photo with Name and links is added in Students section.

### CODE REVIEW

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
Why is `Gemfile.lock` file modified ?

**Comment by ankitrgadiya** [comment]
I don't know, I didn't modified it manually. Maybe because I install jekyll. But I'm not sure.

**Comment by ankitrgadiya** [comment]
Can I like copy and paste the default one from upstream and push changes??

**Comment by jigyasa-grover** [comment]
>Can I like copy and paste the default one from upstream and push changes??


Pls rephrase.

**Comment by ankitrgadiya** [comment]
Can I copy the Gemfile.lock from upstream repo and paste it in my local repo and push it again?

**Review by jigyasa-grover — APPROVED** [review]

**Comment by ankitrgadiya** [comment]
I've applied and I'm already in FOSSASIA organization.

And by live link do you mean [this](http://ankitrgadiya.me/gci16.fossasia.org/)

**Pull request merged**
