### PR TITLE
Added image

### PR DESCRIPTION
**Pull request by AgamAhluwalia**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by AgamAhluwalia** [comment]
All done

**Comment by abishekvashok** [comment]
@AgamAhluwaila can you update the PR body and describe what are you trying to do in this PR, why are you adding an image alone? Please read the readme.md and contributing.md files ;)

**Comment by robbyoconnor** [comment]
@AgamAhluwalia 

1. [Read the directions](https://github.com/fossasia/gci16.fossasia.org#adding-yourselves-to-student-section). 
2. Your image is too big 
3. Stop checking the checkboxes when you didn't read them (when  you actually read them, then check the boxes :-)) 

I would recommend you delete your fork and refork, it's the easiest route. Otherwise, you can [join the chat on slack and get help](https://github.com/fossasia/gci16.fossasia.org#finding-support).

**Comment by robbyoconnor** [comment]
@AgamAhluwalia 

1. [Read the directions](https://github.com/fossasia/gci16.fossasia.org#adding-yourselves-to-student-section) for adding yourself as a student
2. Your image name is too big -- make your first name -- all lower-case. 
3. Stop checking the checkboxes when you didn't read them (when  you actually read them, then check the boxes :-)) 

I would recommend you delete your fork and refork, it's the easiest route. Otherwise, you can [join the chat on slack and get help](https://github.com/fossasia/gci16.fossasia.org#finding-support).

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
See above comments.

**Comment by robbyoconnor** [comment]
@AgamAhluwalia -- are you going to fix this?

**Comment by robbyoconnor** [comment]
@AgamAhluwalia bump once again.

**Comment by robbyoconnor** [comment]
@AgamAhluwalia we will close this pull request in 1 day if it does not get activity.

**Comment by robbyoconnor** [comment]
@AgamAhluwalia when you're ready -- make a new pull request. Closing due to lack of activity.

**Pull request closed without merging**
