### PR TITLE
Task: Add your photo to the GCI FOSSASIA Site Student Section and Tweet about it

### PR DESCRIPTION
**Pull request by nmtan2001**
Please tell me if I missed something. Thank you for reading

### CODE REVIEW

**Comment by m1guelpf** [comment]
@nmtan2001 Check https://github.com/fossasia/gci16.fossasia.org#adding-yourselves-to-student-section

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
Edit `students.yml` as well

**Comment by jigyasa-grover** [comment]
@nmtan2001 Any update on this ?

**Comment by jigyasa-grover** [comment]
Thank you very much, you have been added via PR https://github.com/fossasia/gci16.fossasia.org/pull/423 :)

**Pull request closed without merging**
