### PR TITLE
Fix position of Github username (Issue #231)

### PR DESCRIPTION
**Pull request by hoangvanthien**
#231 This is the second time we encounter this problem and I don't know why. Hope we won't meet it again. :)
Please refer to: #179 (Old issue) and #180 (Old PR)
After fixing: https://hoangvanthien.github.io/

### CODE REVIEW

**Comment by rhemon** [comment]
seems pretty good 👍

**Comment by jigyasa-grover** [comment]
@hoangvanthien Pls post before and after screenshots ? Also, was any issue pertaining to it opened before ?
Pls follow the [code practices in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) :)

**Comment by hoangvanthien** [comment]
I fixed the description which now provides link to recent issue and old issue and old merged pr. How about it now? @jig08

**Comment by oanarosca** [comment]
Looks alright to me, good job!

**Review by oanarosca — APPROVED** [review]

**Pull request merged**
