### PR TITLE
add animeshsinghweb to student-section

### PR DESCRIPTION
**Pull request by animeshsinghweb**
I added my image and updated students.yml and blogs.yml with my info and fixed few UX bugs.

My task: https://codein.withgoogle.com/dashboard/task-instances/4646195228049408/
My GH-Pages: https://animeshsinghweb.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Awesome!

**Comment by niccokunzmann** [comment]
There is a whitespace at the en dof the line:

    | 489|    |-    margin: 2em 0.1em; 

This causes an error. If you like, you can remove it.

**Comment by niccokunzmann** [comment]
or maybe we should change the whole errors with the spaces as the spaces are not problem. What do you think? I invite you to comment on #235.

**Comment by animeshsinghweb** [comment]
@niccokunzmann yes, and even that error would be hard for peers to guess. Thanks for considering that.

**Comment by animeshsinghweb** [comment]
And also @niccokunzmann @hemantjadon is my task approved so that I can move on to the next one?
Thanks.

**Comment by hemantjadon** [comment]
@animeshsinghweb Yes I just approved your task

Congrats :)
Keep Coding :)

**Comment by animeshsinghweb** [comment]
@hemantjadon Thanks.

**Pull request merged**
