### PR TITLE
Added Dwij's second blog in blog section

### PR DESCRIPTION
**Pull request by codein-dwij**
I have added my blog :)
GCI Task Link :
https://codein.withgoogle.com/dashboard/task-instances/5388186731675648/
Link To live gh-pages : https://codein-dwij.github.io/gci16.fossasia.org

### CODE REVIEW

**Comment by oanarosca** [comment]
Looks good, let's see if travis builds and then we can merge :)

**Comment by codein-dwij** [comment]
hmm lets see if there is no issue ;)

**Comment by oanarosca** [comment]
You're improving, Dwij, good job!

**Comment by codein-dwij** [comment]
Thanks :)

**Pull request merged**
