### PR TITLE
Added Google Maps API for Students Section

### PR DESCRIPTION
**Pull request by Elgayar**
Fixed issue #371

Implemented code for previewing locations of students on a Google Map, using the Google Maps API.

### CODE REVIEW

**Comment by gaeun** [comment]
Can you provide a live link and fix merge conflicts?

**Comment by Elgayar** [comment]
Hello! Here is a live link, and the conflicts has been resolved! Tell me if you need anything else :)

**Comment by Elgayar** [comment]
https://elgayar.github.io/gci16.fossasia.org/

**Comment by Elgayar** [comment]
@gaeun I think it's ready now.

**Comment by gaeun** [comment]
Please correct me if it's just me, but it seems like the mentor map isn't showing up on your live link. The student map seems great though!

**Comment by Elgayar** [comment]
Okay so the problem is much bigger than I thought, but Google Maps, doesn't allow more than 1 map to be displayed on the same page. I will try and find a solution.

**Comment by gaeun** [comment]
Ok, please let me know if you need any help! The Slack channel is also a great place to look for advice.

**Comment by Elgayar** [comment]
I did something much better, I made only one map, and the markers are labeled either with M for mentor or S for Student, and I guess that's much more professional, instead of having more maps, and this will also make mentors and students see their locations together. As well as the website performance would be better with loading one map instead of loading two.

**Comment by Elgayar** [comment]
Tell me what you think, check my live page again! I'd love to know your opinion.

**Comment by Elgayar** [comment]
@gaeun If everything is fine, please tell me what you think and merge so I could submit my task!

**Comment by gaeun** [comment]
@Elgayar Thanks! This looks great! Next time, can you squash all your commits into one?

**Comment by Elgayar** [comment]
Great! Thank you so much, I was honored to work with you! 
Don't forget to close issue #371 

Seeya! :D

**Pull request merged**
