### PR TITLE
Fix image slider

### LINKED ISSUE #434: Slider about CodeHeat not displayed properly - PR #432
I made a pull request to add a slider containing a image of almost the same size as the previous ones and the with text regarding 'CodeHeat'. The PR got merged but no text is being displayed and the image is also too zoomed in. 
Please help. 
Thanks.

### PR DESCRIPTION
**Pull request by hoangvanthien**
Fix #434 
Additionally, I've repaired the slider's CSS structure. Now it allows contributors to add more slides in `slides.yml` without any problems. Slider's height is resized in order to fit with the menu bar.
See the difference at: https://hoangvanthien.github.io

### CODE REVIEW

**Comment by oanarosca** [comment]
Looks good! :+1:

**Comment by nikhilchandak** [comment]
@oanarosca Though you have merged the commit, there seems to be no change in the slider about CodeHeat of the official website at http://gci16.fossasia.org/ . I had earlier opened the issue at https://github.com/fossasia/gci16.fossasia.org/issues/434  which is now closed but I don't see any change.

**Comment by hoangvanthien** [comment]
@nikhilchandak Could you provide a screenshot? It seems fine on my side.

**Comment by nikhilchandak** [comment]
@hoangvanthien Your live url is perfectly fine and even looks great with the slider. But I am talking about the official website of gci'16 .
fossasia - slider codeheat bug

**Comment by hoangvanthien** [comment]
@nikhilchandak 
screen shot 2016-12-13 at 21 10 58

**Comment by codein-dwij** [comment]
The errors are not in the code but on your side @nikhilchandak . Please try using a different browser and reload the page :)

**Comment by nikhilchandak** [comment]
Sorry for the inconvenience. @codein-dwij You're right. My browser's fault.

**Pull request merged**
