### PR TITLE
Yash Kumar Verma's details added

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- added details about myself  (@yashkumarverma) to the students.yml file

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Live Link to website 

https://yashkumarverma.github.io/gci16.fossasia.org/

**Review by gaeun — CHANGES_REQUESTED** [review]
Please remove the backslash in the facebook section, as this will result in an invalid URL.

**Comment by YashKumarVerma** [comment]
Just wanted to know one thing. Will this pull request be merged even if it has 2 commits?

**Comment by gaeun** [comment]
Yep, we can squash all your commits as we merge (although it's best practice to squash beforehand). So you can go ahead and make your changes :)

**Comment by YashKumarVerma** [comment]
but the problem is that i don't know how to squash them. The last time i did it... it messed things up

**Comment by jigyasa-grover** [comment]
@YashKumarVerma Dont worry about multiple commits at the moment, pls make the desired changes. Cheers !

**Comment by YashKumarVerma** [comment]
i have a better option. i'm closing this PR and making a fresh PR. :)

**Pull request closed without merging**
