### PR TITLE
New

### PR DESCRIPTION
**Pull request by ApurvJain123**

### CODE REVIEW

**Comment by Princu7** [comment]
Hello @ApurvJain123. Glad to see you contributing. Can you make some more changes please

* As stated by @niccokunzmann, please add your info to a random position instead of the start to reduce the number of merge conflicts that may arise.
* Please add a picture in the /images/blog section so that it gets displayed on the website.
* Always Provide a link to your gh-pages in the future for faster reviewing. It is http://apurvjain123.github.io/gci16.fossasia.org
* If you need more assistance, you can ask us here or in the slack or the gitter channel.

**Comment by niccokunzmann** [comment]
@ApurvJain123 Thanks for the contribution! Please have a look if your blog is correctly displayed. If you see any problems, you can create an issue or a new pull-request.

If you like to add images with fotos inside, please use jpg instead of png as it loads much faster and is smaller.

**Comment by jigyasa-grover** [comment]
@niccokunzmann Did you `SQUASH & MERGE` ?

**Comment by abishekvashok** [comment]
@jig08 I can see it's squashed and merged:
image

However we should make the tests green again as this makes it red. :)

**Comment by jigyasa-grover** [comment]
@Abhi2424shek +1

**Comment by niccokunzmann** [comment]
@jig08 yes.

**Pull request merged**
