### PR TITLE
Adding myself as a Student

### PR DESCRIPTION
**Pull request by kartikeya23**
image
I closed the prev one to remove the extra image

### CODE REVIEW

**Comment by Hesham-Burawi** [comment]
@kartikeya23 You have multiple commits I think you need to squash them.

**Comment by Hesham-Burawi** [comment]
see CONTRIBUTING.md file for more info

**Comment by abishekvashok** [comment]
@kartikeya23 do you have any difficulties squashing them?

**Comment by animeshsinghweb** [comment]
@kartikeya23 Please also resolve the merge conflicts.
 I'd suggest you, from next time while requesting for Pull Request make a new branch using `git checkout -b yourNewBranchName` and then you can do your changes there, commit, squash and request for PR.

**Comment by abishekvashok** [comment]
@animeshsinghweb that would prevent us valuable preview as https://username.github.io works only on gh-pages

**Comment by animeshsinghweb** [comment]
@Abhi2424shek That is not a problem I guess, people can anyhow preview their works in their isolated branch even (though not the .yml parts if not deployed properly). Also they can merge their branch to their `gh-pages` after making changes in the otherBranch`, and then they can `push` their `gh-page` branch and review. If all goes fine you can then go back to your 'otherBranch' and push to the remote origin and then request PR.

**Comment by abishekvashok** [comment]
Most of the parts of site are depended in Jekyll and you can do all that you do in another branch on the gh-pages branch :) ☺

**Comment by animeshsinghweb** [comment]
You meant **can't** above?
I know, but you can at least do your CSS part there. And for the rest you can merge your 'anotherBranch' to `gh-pages` and recheck it, and then push your `anotherBranch` and request PR.

Both methods are good, anyways you know that GH-Page branch would be getting continuous PR so that might be overwhelming to squash after PR for origin. 👍

**Comment by niccokunzmann** [comment]
@kartikeya23 Thanks for your contribution! Please check the website to see if everything was done correctly.

**Comment by kartikeya23** [comment]
@niccokunzmann , thanks for your help!

**Pull request merged**
