### PR TITLE
Support section in README #258

### PR DESCRIPTION
**Pull request by rhemon**
I added a finding support section in the README.md file so that it is easier for new comers to find and join the chatrooms and mailings lists. 

Task : https://codein.withgoogle.com/dashboard/task-instances/6087169976303616/

### CODE REVIEW

**Comment by rhemon** [comment]
error error 
go away go away
let me live in peace
error error
go away go away

Small, not that great poem made by me :P

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by rhemon** [comment]
thanks @niccokunzmann

**Comment by rhemon** [comment]
@niccokunzmann could also check my Task plz

**Comment by niccokunzmann** [comment]
Done.

**Comment by rhemon** [comment]
Thanks

**Pull request merged**
