### PR TITLE
Fixed unequal padding

### PR DESCRIPTION
**Pull request by ankitrgadiya**
#758 
[Live Link](https://ankitrgadiya.github.io/gci16.fossasia.org/)
- Fixed unequal padding for following sections
  - Blog Section
  - Design V1 Section
  - Design V2 Section

### CODE REVIEW

**Comment by hoangvanthien** [comment]
Do you mean inequality of padding-left?

**Comment by ankitrgadiya** [comment]
@hoangvanthien check the issue mentioned please. :-)

**Comment by hoangvanthien** [comment]
Ah! I see what you did there. Looks like you've centered the contents.

**Comment by ankitrgadiya** [comment]
@hoangvanthien Yep

**Pull request merged**
