### PR TITLE
Fixed text overflow issues resolves #373 and #130

### LINKED ISSUE #373: Fix Student Projects section
The projects section looks very strange...
ScreenShot
<table><tr><td><strong>Browser</strong></td><td>Chrome 55.0.2883.75</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 987</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></table>

### PR DESCRIPTION
**Pull request by abishekvashok**
These errors where looming large so I thought I could get a fix.

Current screenshot: [gci16.fossasia.org]
image

I can't provide the preview beacuse I am on another branch @jig08 please understand.

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@Abhi2424shek 
* Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

**Comment by abishekvashok** [comment]
I am sorry @jig08 I provided the link. :) Please review

**Comment by jigyasa-grover** [comment]
Verify the link above, there's a semi-colon 😉

**Comment by abishekvashok** [comment]
@jig08 upsss sorry updated.

**Comment by jigyasa-grover** [comment]
Also, a before-after screenshot shall be appreciated.

**Comment by abishekvashok** [comment]
Sorry wait I am on another branch, @jig08

**Comment by abishekvashok** [comment]
see the preview now :) thanks for merging @jig08 
image

**Pull request merged**
