### PR TITLE
Added smooth scrolling to the site's navbar

### PR DESCRIPTION
**Pull request by oscarwong67**
Created a smooth scrolling animation whenever you click on a link in the top navbar.

The GCI Task is "Website: Add a feature or fix an issue for the GCI website from the github issue tracker (FOSSASIA)".

Demo: oscarwong67.github.io/gci16.fossasia.org/ (notice that when you click on a link, you scroll smoothly down to the section instead of instantly being teleported)

### CODE REVIEW

**Comment by Princu7** [comment]
@oscarwong67 Thanks for the request. The website looks good and the scrolling works great. However, there seem to be some issues like with Travis like the "No line at End of File" or the "Extra whitespaces". Please see the detailed build log to correct the issue.
Also please post the link to your task in addition to the name of the task.
Cheers.

**Review by Princu7 — CHANGES_REQUESTED** [review]
Fix the Travis build error.

**Comment by oscarwong67** [comment]
@Princu7 here's the task: https://codein.withgoogle.com/dashboard/task-instances/6710449120739328/

Hopefully the linting errors should be fixed now.

**Comment by Princu7** [comment]
@oscarwong67 Nice. Now that you have fixed the linting errors, please squash your commits into one and give it a descriptive name like "Added smooth scrolling to Website". If you are not familiar with squashing the commits, you can check out the various links that have been posted on the FossAsia  GCI chat channel on slack.
Additionally, you can find help in the contributing guide of this project. You can check it out here.
https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md

**Review by Princu7 — CHANGES_REQUESTED** [review]
Please squash the commits into one.

**Comment by hemantjadon** [comment]
Work seems to be Nice. Please squash the commits so we can proceed.

**Comment by oscarwong67** [comment]
@hemantjadon @Princu7 the commits have been squashed!

**Review by Princu7 — APPROVED** [review]
Nice Job. Thanks for contributing

**Comment by oscarwong67** [comment]
@princu7 thanks for the opportunity!

**Comment by Princu7** [comment]
@oscarwong67 Please submit the task so we can approve it.

**Comment by oscarwong67** [comment]
@princu7 I'll do that, after I complete the required blog post

**Comment by oscarwong67** [comment]
@princu7 never mind, that's not required, I'll submit!

**Pull request merged**
