### PR TITLE
Adding Mentor : Yathannsh Kulshrestha

### PR DESCRIPTION
**Pull request by kartikeya23**
Adding both yml content and photo.

### CODE REVIEW

**Comment by kartikeya23** [comment]
Please ignore Dishant Khanna addition, it already existed...

**Review by shubham-padia — CHANGES_REQUESTED** [review]
* Please resolve the merge conflicts
* Squash all your commits into one
* Remove the extra photo of Mentor - Dishant Khanna as he has been already added.

Have a look at https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md#tutorials for tutorial on squashing and resolving merge conflicts

**Comment by niccokunzmann** [comment]
@kartikeya23 How would you like to go on. Would you like to try squashing?

**Comment by niccokunzmann** [comment]
Can you add your credentials to a random position in the file? May be you want to update this pull-request or open a new one. Several other people want to do the same task and if all add it to the end, several-1 people fail and need to do again. You can also talk to them, and collaborate.

**Comment by kartikeya23** [comment]
I'll prefer opening a new one, you may close this pull request...

@niccokunzmann, can you help me squash?

**Comment by jigyasa-grover** [comment]
Copy of PR https://github.com/fossasia/gci16.fossasia.org/pull/406 , closing this.

**Pull request closed without merging**
