### PR TITLE
Update blogs.yml

### PR DESCRIPTION
**Pull request by hillamu2**
pr
https://github.com/hillamu2/gci16.fossasia.org
hillamu2/gci16.fossasia.org

### CODE REVIEW

**Comment by hillamu2** [comment]
@oanarosca why am I still not authorised to  merge it?

**Comment by oanarosca** [comment]
Because only mentors and maintainers are able to merge :) When the travis build passes, I'll merge it

**Comment by hillamu2** [comment]
@oanarosca thanks a lot for your help :)

**Comment by hillamu2** [comment]
@oanarosca why is the check failing each and every time?

**Comment by oanarosca** [comment]
It seems that you have 2 whitespaces on line 66. I know these checks can be very frustrating, but they're neccesary so that we can keep the code clean. Remove the spaces, commit and push, the commit will be automatically added to this PR and then we can merge :)

**Comment by rhemon** [comment]
Twinkle twinkle, little bugs,
How I wonder what you are.
Up above the world of code,
Like a fire in the app.
Twinkle twinkle, little bug,
How I wonder what you are.

second version of my poem, dedicated to @hillamu2 :P 

and congrats on passing the checks

**Comment by oanarosca** [comment]
Good job! :tada:

**Comment by hillamu2** [comment]
@oanarosca thanks for your precious help

**Pull request merged**
