### PR TITLE
add kshitij info

### PR DESCRIPTION
**Pull request by kshitijsingla**

### CODE REVIEW

**Comment by abishekvashok** [comment]
Please resolve the conflicts and add something to the PR body please!

**Comment by ankitrgadiya** [comment]
@kshitijsingla Please resolve merge conflits. This is happening because your forked version is not updated with upstream. 
If you can't figure it out, ask on #gci, slack

**Comment by robbyoconnor** [comment]
I did part of it for you -- resolving the conflict -- you however need to resize your image so it is `240 x 240 [w x h]`

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
I did part of it for you -- resolving the conflict -- you however need to resize your image so it is `240 x 240 [w x h]`

This is in the directions. Attention to detail matters.

**Comment by robbyoconnor** [comment]
No need to squash, just resize the image.

**Comment by robbyoconnor** [comment]
Why did you close this @kshitijsingla ? Just resize the image and add it.

**Pull request closed without merging**
