### PR TITLE
Added 3 columns in 1 row in Social media section

### PR DESCRIPTION
**Pull request by harshit98**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request
I did some changes in social media section. Added 3 columns in 1 row instead of 2 columns in 1 row. As per the discussion, I did the changes in terms of design which is responsive for all types of screen size.

Fixes issue #978 #961 and #924 

Here is the live link -  https://harshit98.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
This is slightly better but still not good enough. Spacing is not consistent when the reflow happens due to reducing the viewport dimensions. See the screenshots below: 

image

image

image

image

image

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
There are still responsiveness issues. Narrow the browser window as much as you can and you will see the issues.

**Review by m1guelpf — COMMENTED** [review]
screenshot_2017-02-07-09-21-58

**Review by m1guelpf — CHANGES_REQUESTED** [review]
The youtube section looks strange and there are responsiveness issues.

**Comment by harshit98** [comment]
@m1guelpf So should I remove the Youtube section?

**Comment by m1guelpf** [comment]
@harshit98 You should ask @robbyoconnor 
But i'm only saying that you should fix it because it isn't fully responsive.

**Comment by abishekvashok** [comment]
@harshit98 could you resize it?

**Comment by harshit98** [comment]
@Abhi2424shek I tried to resize, but the problem is that if I do resizing, it again becomes 1 row with 2 columns. And if I shrink the size of social section like Youtube, the design will look good on phones but on laptops it will not be organized in a well mannered! That is why, in my opinion we should continue with this layout only.

**Comment by robbyoconnor** [comment]
@hanh00740 youtube section is fine -- but you need to figure out how to deal with the responsiveness issues. Spacing should be uniform.

**Comment by mariobehling** [comment]
Thanks, I am merging this as an improvement of the current state. Hope to see the final improvements requested here. Keep it up!

**Pull request merged**
