### PR TITLE
Added Sid Rao image and details for GCI task

### PR DESCRIPTION
**Pull request by ra0s**

### CODE REVIEW

**Comment by Princu7** [comment]
@imsuprem3 Thanks for the request. There are some more things that you have to do:

* Always attack the link to the task which you are completing through this pull request. Also provide a link to your live gh-pages for faster and easier reviewing. 

* Squash your commits into one with an informative message like "Added Sid Rao image and details". 

There have been many links posted regarding the above points. You can refer to contributing guide of this project for more information. Cheers.
https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md

**Review by tradzik — CHANGES_REQUESTED** [review]
Please squash your commits into one.

**Comment by abishekvashok** [comment]
Nice work now please squash them run 'git revise -i HEAD~2' in the git terminal (inside the working git repo) then a text editor pops up change pick in the second line to squash and save and exit the editor. After that another one pops up you can change the criteria message in it. Close it after saving and run 'git push -f orgin yourbranch' that must do it :)😉

**Comment by Princu7** [comment]
'git rebase -i HEAD~2'

**Pull request closed without merging**
