### PR TITLE
Added Tushar's info

### PR DESCRIPTION
**Pull request by awesometushar000**
Under GCI 2016 Task
https://codein.withgoogle.com/dashboard/task-instances/6371142912704512/

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@meets2tushar There is a merge conflict, please resolve it first and also you must squash your commits.
Please refer **Contrubuting.md** [link here](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) for help.

**Comment by awesometushar000** [comment]
ok

**Comment by awesometushar000** [comment]
Only those with write access to this repository can merge pull requests.
This is message from GH..

**Comment by animeshsinghweb** [comment]
@meets2tushar I know, you can't squash (you aren't a maintainer') and merge from github.
Had you read [CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) first?
Atleast resolve merge conflict.

**Comment by abishekvashok** [comment]
How's the status @meets2tushar i hope you are getting well dear.

**Comment by animeshsinghweb** [comment]
Closing in reference to PR #532 👍 
GG @meets2tushar :)

**Pull request closed without merging**
