### PR TITLE
Fixed the p overflow-x of the card by truncating the p

### PR DESCRIPTION
**Pull request by animeshsinghweb**
Also updated the README.md for better instructions.
Issue: #428

### CODE REVIEW

**Comment by abishekvashok** [comment]
Link?

**Comment by abishekvashok** [comment]
I will restart the build for you.

**Comment by abishekvashok** [comment]
I've added a code to the PR body for danger please don't remove it

**Comment by animeshsinghweb** [comment]
@Abhi2424shek Ok.
https://animeshsinghweb.github.io/gci16.fossasia.org/

**Comment by abishekvashok** [comment]
I am getting 404 error

**Comment by animeshsinghweb** [comment]
@Abhi2424shek Even me, I need to recheck what happened. I reforked this repo, and even push the gh-pages after merge.

**Comment by abishekvashok** [comment]
Please recheck.

**Comment by animeshsinghweb** [comment]
```
The page build completed successfully, but returned the following warning:

The CNAME `gci16.fossasia.org` is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```
I continuously receive in mail.

**Comment by oanarosca** [comment]
Looks good, just like I imagined it! Don't worry about the build failure, I'll merge this. Great job!

**Comment by abishekvashok** [comment]
Ahh i got it your branch is not gh-pages that's the reason for 404 it's i437

**Comment by animeshsinghweb** [comment]
@oanarosca Thanks.
Look at the site, it looks like that's what we need to do?
Isin't it @Abhi2424shek ?
Thanks BTW. We did it @oanarosca :)

**Comment by abishekvashok** [comment]
Yes nice

**Pull request merged**
