### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ArgonArnav**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by m1guelpf** [comment]
are you kidding me? Someone please add the `wontfix` label after closing this so it doesn't count for Hacktoberfest

**Comment by tabesin** [comment]
???

**Comment by ArgonArnav** [comment]
I am so sorry sir I am a newbie and was unaware of this kind of situation ,
some friend
of mine told me to do something what is called pull request to this repo in
order to get 5 pull requests so we get a free t shirt from Hactoberfest. I
sincerely apologise my actions and will be careful in the future.

Regards
Arnav Anand

**Comment by idealadarsh** [comment]
Its OK @ArgonArnav .
Be careful next time and try to make some meaningful changes. Before that I would recommend you to learn about it, that you are working on if not already familiar with it.

**Comment by ArgonArnav** [comment]
Thank you and I will for sure learn and contribute to Fossasia in the field
of Android because I am very much interested in contributing to this
organization after I learnt about the same today .

Regards
Arnav Anand

**Comment by abishekvashok** [comment]
Guys, guys why did we close this? Simple things also count right?

**Pull request closed without merging**
