### PR TITLE
Added my details as a student to FOSSASIA

### PR DESCRIPTION
**Pull request by animeshsinghweb**
Updated the students.yml by adding my details

### CODE REVIEW

**Review by hemantjadon — CHANGES_REQUESTED** [review]
@animeshsinghweb 
Seems good. 
Please resolve the merge conflicts so we can proceed.

**Comment by animeshsinghweb** [comment]
Done fixing the conflict issue,
Thanks.

**Comment by hemantjadon** [comment]
Conflicting issue doesn't seems to be fixed
Also as a part of the task you have to add your profile pic in the student section of the gci16 website.

**Comment by animeshsinghweb** [comment]
Thanks Hemant Sir,
OK I initiated another pull request https://github.com/fossasia/gci16.fossasia.org/pull/58
May be that work fine, do let me know if there is any problem or if I had missed anything.

**Pull request closed without merging**
