### PR TITLE
[WIP] Added live preview when hovering on a project

### PR DESCRIPTION
**Pull request by Elgayar**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

I have added a live preview iframe when hovering on a student's project
card.
I also intended not to implement that in JavaScript in order not to
affect the website's performance and speed, all was done in pure CSS.

Live Link: https://elgayar.github.io/gci16.fossasia.org/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why is this closed?

**Comment by Elgayar** [comment]
@robbyoconnor Because it's not working, I'll open it when I fix it.

**Comment by robbyoconnor** [comment]
Re-open it and add [WIP] to the title

**Comment by Elgayar** [comment]
Okay! Sorry tho, didn't know I should do that :D

**Comment by robbyoconnor** [comment]
yeh if you make a PR and it's not pergect -- simply append "[WIP]" to the beginning

**Comment by robbyoconnor** [comment]
@Elgayar https://travis-ci.org/fossasia/gci16.fossasia.org/builds/189908489

Run Coala local

**Comment by myfrom** [comment]
I think it would be better to inject them using JavaScript - loading all the iframes can make the load time amazingly big. Also, I think it would be better to create one iframes and then change it's `src` using JS. Also those should not render on mobile IMO

**Comment by abishekvashok** [comment]
For this i think the best approach would be to use asynchronous javascript onload finish and then display the iframes by Dom injection method.

**Comment by myfrom** [comment]
@Abhi2424shek Yup, it would be good. But I still think it would be even better if we create one frame and change `src` / position depending on needs. The site I already very hungry of RAM

**Comment by Elgayar** [comment]
So after doing some research, iframes are blocked by all modern browsers. However, there are workarounds that I am currently looking into. @robbyoconnor @Witus13 @Abhi2424shek 
If the workaround I'll reach eventually will affect the website's performance (because it will definitely be JavaScript), then I don't think it will be really necessary.

http://stackoverflow.com/questions/9158024/iframe-with-external-page-not-working

**Comment by Elgayar** [comment]
image

**Comment by myfrom** [comment]
Those pages would need to include http header `X-Frame-Options: ALLOW-FROM
https://gci16.fossasia.org/`

**Comment by abishekvashok** [comment]
Yep @Witus got it for you, i was about to go for the same that should work @Elgayar

**Comment by Elgayar** [comment]
Not supported in Chrome. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
@Witus13 @Abhi2424shek

**Comment by abishekvashok** [comment]
Can you changes some type of other workarounds iframes have too many security restrictions being imposed by browsers

**Pull request closed without merging**
