### PR TITLE
Revert "Add Gaeun Kim to students section"

### PR DESCRIPTION
**Pull request by GramescuDan**
logo for MBDyn by Melo5154
mbdyn logo

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Melo5154 Can you provide a reason of why are you removing Gaeun Kim from the students section.

**Comment by GramescuDan** [comment]
I didn't want to

**Comment by abishekvashok** [comment]
Ha but the commit does

**Comment by m1guelpf** [comment]
Looks like this PR and branch is only causing confusion.
Also, OP said that he didn't wat to do this.
Closed

**Pull request closed without merging**
