### PR TITLE
Dannymout Logo fixed

### PR DESCRIPTION
**Pull request by ankitrgadiya**
Current Version
screenshot from 2016-12-14 14-58-41

Fixed Version
screenshot from 2016-12-14 14-58-55

### CODE REVIEW

**Comment by animeshsinghweb** [comment]
@dannymout @ankitrgadiya Can you provide Link to the GH-Page?

**Comment by ankitrgadiya** [comment]
@animeshsinghweb  [Live Link](http://ankitrgadiya.me/gci16.fossasia.org)

**Comment by animeshsinghweb** [comment]
@ankitrgadiya Looks fine to me. Merging it. 👍

**Comment by ankitrgadiya** [comment]
@animeshsinghweb Thanks!

**Pull request merged**
