### PR TITLE
Removed Grey Background

### PR DESCRIPTION
**Pull request by Elgayar**
I have removed the grey background from the slider when it is resized.

### CODE REVIEW

**Comment by Elgayar** [comment]
Live Link: https://elgayar.github.io/gci16.fossasia.org/

**Review by robbyoconnor — APPROVED** [review]
LGTM.

**Comment by robbyoconnor** [comment]
Merging this.

**Comment by robbyoconnor** [comment]
I'm removing your waving octocat -- It's not working well and it's causing the build to go red (meaning it's not linting correctly. Otherwise solid work

**Comment by robbyoconnor** [comment]
@Elgayar did the waving octocat work for you? I didn't see it...

**Comment by robbyoconnor** [comment]
I added it back.. and ignored the long line for the linter.

**Comment by Elgayar** [comment]
@robbyoconnor Thanks for merging, I'll make another commit to make the waving octocat work properly, because it seems like it's not!
Have a nice day :)

**Pull request merged**
