### PR TITLE
Travis: Preserve coala's cache

### PR DESCRIPTION
**Pull request by yukiisbored**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

coala's cache are saved on $XDG_DATA_HOME/coala to speed up CI, we can
create a volume for that and preseve it's contents with Travis'
directory caching feature.

Closes https://github.com/fossasia/gci16.fossasia.org/issues/603

### CODE REVIEW

**Comment by m1guelpf** [comment]
@yukiisbored LGTM, but let's wait for Travis.

**Comment by yukiisbored** [comment]
@m1guelpf It looks like it'll fail because there are `https` declared in the hyperlinks, I'll fix it on a separate PR.

**Comment by abishekvashok** [comment]
K then @yukiisbored but we will wait for Travis to find that it will not fail except for the linting issues

**Comment by yukiisbored** [comment]
@Abhi2424shek HTMLLintBear ;) https://travis-ci.org/fossasia/gci16.fossasia.org/builds/191003065#L445

**Comment by abishekvashok** [comment]
It is working fine merging...

**Comment by m1guelpf** [comment]
@yukiisbored This is OK, looking to see you on other PR for fixing that :smile:

**Comment by abishekvashok** [comment]
Merged lol!

**Pull request merged**
