### PR TITLE
Added Hesham Burawi Blog to _data/blog

### PR DESCRIPTION
**Pull request by Hesham-Burawi**

### CODE REVIEW

**Comment by shubham-padia** [comment]
Please fix the spacing inconsistencies as mentioned in the logs at https://travis-ci.org/fossasia/gci16.fossasia.org/builds/181150623

**Comment by pa1pal** [comment]
@Hesham-Burawi Also do provide the PR description always. In this case give the links of your repo's live page and task.

**Comment by Hesham-Burawi** [comment]
I cant find the live link

**Comment by pa1pal** [comment]
@Hesham-Burawi I can see that you forked repo perfectly. But you renamed it with username.github.io. This should be done when you are making your Github profile gh-pages. Projects gh-pages are different it will follow this structure. username.github.io/reponame

**Review by daminisatya — CHANGES_REQUESTED** [review]
merge conflicts, also need to address mentor's comments. feel free to ask for help.

**Comment by Hesham-Burawi** [comment]
Here is the link:
https://hesham-burawi.github.io/Hesham-Burawi.github.io-/
what about the spacing inconsistencies the log dosnt exactly say where it is?

**Comment by Hesham-Burawi** [comment]
and task link:
https://codein.withgoogle.com/dashboard/task-instances/5433832503246848/

**Comment by abishekvashok** [comment]
See the log: 
```
|    |++++| /app/_data/blogs.yml
|  15|  15|   blog_img:
|  16|  16|   article: Participating in Google Code-in 2016
|  17|  17|   article_link: https://hoangvanthien.edublogs.org/2016/11/30/participating-in-google-code-in-2016/
|  18|    |-  
|    |  18|+
|  19|  19| - name: Hesham Burawi
|  20|  20|   blog: https://heshamburawi19.wordpress.com
|  21|  21|   blog_img: burawi19-logo.png
```

**Comment by abishekvashok** [comment]
Can u squash them down, see the contributing.md file for tutorials for squashing commits.

**Comment by Hesham-Burawi** [comment]
There I think I fixed it

**Comment by abishekvashok** [comment]
There are still conflicts. See the tutorials then squash the commits, I will assist you if anything goes wrong in between.

**Comment by niccokunzmann** [comment]
Now, the problem is that someone else edited the same files. Can you do a git pull?

**Comment by jigyasa-grover** [comment]
@Hesham-Burawi Any update on this pls ?

**Comment by Hesham-Burawi** [comment]
What exactly is a git pull. Sorry am quite new to this and am still trying to figure out how to get my terminal to the repos branch to squash the commits

**Comment by Hesham-Burawi** [comment]
or should I just start a new pull request

**Pull request closed without merging**
