### PR TITLE
Add foto to mentor's section

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by codethejason** [comment]
Please [squash](https://github.com/blog/2141-squash-your-commits) your commits.

**Review by tradzik — CHANGES_REQUESTED** [review]
Commits need to be squashed.

**Comment by hemantjadon** [comment]
Please check for merge conflicts :)

**Comment by jigyasa-grover** [comment]
@nolik2000 
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentor section"
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

**Comment by jigyasa-grover** [comment]
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
