### PR TITLE
Adding Deepraj Pandey to students section

### PR DESCRIPTION
**Pull request by DeeprajPandey**

### CODE REVIEW

**Comment by DeeprajPandey** [comment]
Why did the checks fail?! :/

**Comment by Princu7** [comment]
@DeeprajPandey Hello. The Travis build has failed because of some space or line length inconsistencies in the code. You can look in the details of the build to identify which lines are causing the issue. Additionally, you can use coala to help you with linting of the code.

**Comment by DeeprajPandey** [comment]
Hi!
There were 2 spaces one a new line in the students.yml file.
Hope it's merged now.
I can not get to other tasks of FossAsia unless I am done with this one.

**Comment by DeeprajPandey** [comment]
@hemantjadon I believe the commits are alright now and the review tag can be removed. :/

**Comment by Princu7** [comment]
@DeeprajPandey Thanks for the request. There are some scope of improvements:

* Always add the link of the task which you are completing and your gh-pages for easy reviewing.

* Please squash your commits into one with a descriptive name like "Adding Deepraj Pandey to students section". There have been many articles and videos posted on FossAsia #gci channel on slack on how to squash commits into one. Please have a look at them. Thanks!!

**Comment by abishekvashok** [comment]
Hey @Princu7 the student section is static, my PR #103 makes it dynamic, i think you should merge that first before merging this.

**Comment by hemantjadon** [comment]
@DeeprajPandey 

* Please squash your commits into one with a descriptive name like "Adding Deepraj Pandey to students section". There have been many articles and videos posted on FossAsia #gci channel on slack on how to squash commits into one. Please have a look at them. 

* We will remove the `review -` flag when the work is completed (squashing / merging)

Cheers :)

**Comment by abishekvashok** [comment]
@hemantjadon can you take a look at #103 , merging anything now will lead to trouble!

**Comment by DeeprajPandey** [comment]
image


@hemantjadon I think it's resolved now. ?

**Comment by hemantjadon** [comment]
I am still able to see the 9 commits here.
Please go ahead and squash them also.

**Comment by DeeprajPandey** [comment]
https://www.youtube.com/watch?v=g8BRcB9NLp4

I followed this. And you can check the screenshot from Powershell. What else should be done?

**Comment by DeeprajPandey** [comment]
Can you please send a screenshot of what is showing up on your end?

**Comment by DeeprajPandey** [comment]
Still 9?

**Comment by hemantjadon** [comment]
Here you go. Yup still 9.
screen shot 2016-12-03 at 12 27 28 pm

**Comment by DeeprajPandey** [comment]
image

Here's the link to that last commit:
https://github.com/DeeprajPandey/gci16.fossasia.org/commit/ea7077a0ff1f4e213edadc3e12ec75c21a097da2

**Comment by DeeprajPandey** [comment]
image

Is this allowed from your end?

**Comment by DeeprajPandey** [comment]
You would be having a Squash and Merge option on your end but the same isn't there on my end.

image

**Comment by abishekvashok** [comment]
Hey @DeeprajPandey you want help, try running `git log` and give me the screenshots

**Comment by DeeprajPandey** [comment]
@Abhi2424shek I am trying to squash the commits into one

**Comment by abishekvashok** [comment]
@DeeprajPandey run `git rebase -i HEAD~14`

**Comment by DeeprajPandey** [comment]
Did that already

**Comment by abishekvashok** [comment]
do it again and wait for a text editor to pop up and give me the screenshot

**Comment by DeeprajPandey** [comment]
image

I think I am on gh-pages.
can't get on to my branch

**Comment by abishekvashok** [comment]
hmm @DeeprajPandey give me a sec

**Comment by abishekvashok** [comment]
leave the shell and run git rebase -i , after that replace noop with:
```
pick commitfirst7hash commitname
and for next 13 commits
squash commitsfirst7hash commitname

```

**Comment by DeeprajPandey** [comment]
I am deleting the repo and starting again.
Meet you soon

**Comment by abishekvashok** [comment]
Hey @DeeprajPandey that wont help you

**Comment by DeeprajPandey** [comment]
@Abhi2424shek I will make the changes again and squash them before submitting the pull request.
not being able to work on other tasks is getting on my nerves now.

**Comment by abishekvashok** [comment]
@DeeprajPandey i squashed as stated above, you will have problems if you dont learn to squash... I am also on my nerves as I cant squash empty commits

**Comment by DeeprajPandey** [comment]
Your problem's resolved?

**Comment by abishekvashok** [comment]
nope, i think they are gonna squash and merge cause I have two empty commits

**Comment by hemantjadon** [comment]
Hey @Abhi2424shek @DeeprajPandey 
It is nice seeing you both working together and trying to help out. This is the beauty of OpenSource Cheers :)

And please be relaxed we will merge the request very soon. 
Sometimes we have some other stuff to do also, so please be calm and just relax. 
We get many task updates and PR's so some delays are bound to happen, as we can't just merge the PR's without proper validation as code quality will degrade.

Maybe try to think what next task you will do? How can you contribute further?

I hope you will understand.

Keep Coding :) Cheers :)

**Comment by abishekvashok** [comment]
@hemantjadon sure

**Comment by DeeprajPandey** [comment]
@hemantjadon I apologise for that. Being new to open source projects, I lost my calm a bit and that was uncalled for.
And I have figured it out. Either we can do what @Princu7 has suggested on @Abhi2424shek 's thread or rebase all the commits "before" submitting a pull request (which is what I did now) and I believe it will be alright now.
Thanks for helping us out. :)

**Comment by abishekvashok** [comment]
@DeeprajPandey then reopen your PR bro

**Comment by Princu7** [comment]
@DeeprajPandey No need of apologizing. We understand your excitement. We all have done the same mistakes before. It's all in good spirit. :+1:

**Comment by hemantjadon** [comment]
@DeeprajPandey 
There is absolutely no need for apologising. I can totally understand that you are excited about your tasks, I  just wanted to point out that there can some delays and all you need to do is patiently wait.

And it is all in a positive spirit, take no negatives here.

Cheers !! :)

**Comment by DeeprajPandey** [comment]
@hemantjadon @Princu7 I deleted that repository and started working again. Made 3 commits and rebased them on git. Pushed that to the main(gh-pages) branch on my repository.
Now, when I want to create a new pull request, I find that the request will be of 5 commits instead of 1.

Yes, the 3 commits were combined to 1 but that is added as a 4th commit instead of replacing the first 3.
Here's the screenshot (check the 4th commit). What should I do now?

image

**Comment by DeeprajPandey** [comment]
Never mind. figured them out. Thanks! :)

**Pull request closed without merging**
