### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Donaldxj**
[bio.txt](https://github.com/fossasia/gci16.fossasia.org/files/619708/bio.txt)
donald

### CODE REVIEW

**Review by daminisatya — COMMENTED** [review]
Please add changes to _data/students.yml

**Comment by robbyoconnor** [comment]
You need to re-read what @daminisatya told you to do...

**Comment by robbyoconnor** [comment]
until you do that -- don't submit your task for review.

**Comment by jigyasa-grover** [comment]
@Donaldxj Updates on this please ?

**Comment by jigyasa-grover** [comment]
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Comment by Donaldxj** [comment]
hello, sorry, my laptop broke down, can i reapply?

**Comment by jigyasa-grover** [comment]
@Donaldxj Sure, you can either re-open this or open a new PR. Cheers !

**Pull request closed without merging**
