### PR TITLE
tushar

### PR DESCRIPTION
**Pull request by tushar-121-patel**
good

### CODE REVIEW

**Comment by m1guelpf** [comment]
@tushar-121-patel What are you exactly trying to do?

**Review by m1guelpf — CHANGES_REQUESTED** [review]
Delete that folder, and add yourself to _data/students.yml

**Comment by niccokunzmann** [comment]
@tushar-121-patel please have a look if you are listed on the web page.

**Comment by niccokunzmann** [comment]
If not, we can figure it out.

**Pull request merged**
