### PR TITLE
adding NadunYashmika to the students section

### PR DESCRIPTION
**Pull request by nadunys**
Adding my name(Nadun Yashmika) to gci16 site of fossasia(gci16.fossasia.org).
https://github.com/yashNadun

### CODE REVIEW

**Comment by agwisniewska** [comment]
@yashNadun Please solve conflicts and also change the PR name to something like "Add ...your name... to the students section" You can also see CONTRIBUTING.md for further help.

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

**Comment by nadunys** [comment]
https://yashnadun.github.io/yashnadun.github/  link for github-pages

**Comment by jigyasa-grover** [comment]
To add yourself to the `students` section , you just need to add your picture in `images` folder and edit `students.yml`

Refer [Adding to student section](https://github.com/fossasia/gci16.fossasia.org#adding-yourselves-to-student-section)

Other changes, I believe, were not required :)

**Comment by nadunys** [comment]
Sorry about that, it was a mistake

**Comment by nadunys** [comment]
Now I think everything is OK now!

**Comment by Princu7** [comment]
@yashNadun Nice. You still need to make some more changes

* Resolve the merge conflicts. If you are not sure about how to do that, you can look at the contributing guide for this project. 

* Squash the commits into one and rename it to something descriptive and clear like "adding NadunYashmika to the students section". 

* If you more assistance to any of these tasks, you can ask us here or in the slack or the gitter channel of GCI.

**Comment by niccokunzmann** [comment]
@yashNadun Thanks for your contribution.You can have a look if your photo shows up on the page and if not, I am sure, we can find a solution.

**Pull request merged**
