### PR TITLE
add Melo5154 logo and profile

### PR DESCRIPTION
**Pull request by ashwini0529**
Closes https://github.com/fossasia/gci16.fossasia.org/issues/419

### CODE REVIEW

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

**Comment by ashwini0529** [comment]
Do I need to provide screenshot?

**Comment by jigyasa-grover** [comment]
Working fine, thanks !

But in future, you should always add it in the PR description.

**Comment by ashwini0529** [comment]
Yeah sure. Will keep that in mind!

**Pull request merged**
