### PR TITLE
Add profile for student: Simon Narang

### PR DESCRIPTION
**Pull request by simonnarang**
Added profile for Simon Narang to students page

This is for the google code in task https://codein.withgoogle.com/dashboard/task-instances/6302473901834240/

### CODE REVIEW

**Comment by simonnarang** [comment]
Did I do something to cause the build fail? It looks like it is something else

**Comment by robbyoconnor** [comment]
@simonnarang I ran it and it builds fine...I'm not sure what the error is about.

**Comment by abishekvashok** [comment]
The tests are running out not because of his problem @robbyoconnor they are failing because of some attributes in the js file which he didn't touch so we can merge this on....

**Comment by robbyoconnor** [comment]
@Abhi2424shek, as I said, I didn't know as I haven't been involved too much.

**Comment by abishekvashok** [comment]
@robbyoconnor it's ok to be merged!

**Comment by DeeprajPandey** [comment]
@Abhi2424shek did you find out where the issue is?
I think you can try removing the comment tags I added in the update tweet section in tweet.js

**Comment by abishekvashok** [comment]
@DeeprajPandey which issue are you refering of :)

**Comment by DeeprajPandey** [comment]
@Abhi2424shek danger fail

**Comment by abishekvashok** [comment]
@DeeprajPandey you need to add a  tag somewhere in your PR body if you are modifying the index.html as it is the core file that's all.

**Pull request merged**
