### PR TITLE
Adding Chien to students section

### PR DESCRIPTION
**Pull request by wermarter**

### CODE REVIEW

**Comment by daminisatya** [comment]
I thought i reviewed this before, is this a new one?

**Comment by wermarter** [comment]
Yes, it is. I had some troubles with the first one. And now this one...

**Comment by jig08** [comment]
@Wermarter 

* Check for TravisCI build failure (cc: @hemantjadon)
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Review by jigyasa-grover — COMMENTED** [review]
@Wermarter 

* Check for TravisCI build failure (cc: @hemantjadon)
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Comment by hemantjadon** [comment]
@Wermarter 

Please remove the changes you made in the `index.html` as we are now fetching the the students directly from _data/students.html. Make sure you have your data there.

Also please squash your commits after making the above changes

There are two ways in which you can squash.

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an **editor** where you will be asked for every commit whether you want to `pick or squash`. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Why do you need remove the first dashes Jekyll needs then and to insert your info don't alter index add it to the end of students.yml

**Comment by jigyasa-grover** [comment]
With reference to [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
