### PR TITLE
Added Popup window for mentors and student

### PR DESCRIPTION
**Pull request by rhemon**
Live Link : https://rhemon.github.io/gci16.fossasia.org/

Issue: #558

Added a pop window for mentors and students. and removed bio information from card

### CODE REVIEW

**Comment by rhemon** [comment]
why is there a conflict with _site stuff, thats supposed to be ignored, right? is it remvoed from .gitignore?

**Comment by abishekvashok** [comment]
@rhemon it's really good job mate :) please add it back to gitignore i think someone added it back

**Comment by rhemon** [comment]
if you can help it would be great or give me an hour. i just had to go out
so will look into it once i get back.  should be back within an hour

**Comment by abishekvashok** [comment]
@rhemon k take your own time.

**Comment by rhemon** [comment]
@Abhi2424shek  please check.

**Comment by abishekvashok** [comment]
@rhemon checking...

**Comment by abishekvashok** [comment]
@rhemon nice work merging...

**Comment by rhemon** [comment]
cool. now we need to tell others to modify their bio so that  on pop up there is a nice looking bio to read. same for mentors. can you create a issue on that?

**Pull request merged**
