### PR TITLE
Adding Deepraj Pandey in Students Section

### PR DESCRIPTION
**Pull request by DeeprajPandey**
Required changes in index.html to display new student's name in the Student section of the website.

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@DeeprajPandey Thanks !

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

**Comment by DeeprajPandey** [comment]
I am on Windows and how do I go about making changes using the command line?

**Comment by jigyasa-grover** [comment]
In `git` you can use the same commands for `Windows` as well.

Just a pro tip: Start using `*nix` (`Linux` or `OS X`) based OS in Open Source :wink:

**Comment by DeeprajPandey** [comment]
Thanks!
Will get a MacBook after the college decisions are out by March.
On the video, I see a checkout command which is followed by the address of the master branch. What would be its equivalent here?

I am sorry to be bothering you so much but this is the first time I am doing actual collaboration stuff on GitHub.

**Comment by jigyasa-grover** [comment]
These are mentioned in `command line instructions` link in this PR too :) 

screen shot 2016-12-02 at 5 22 09 pm

**Comment by DeeprajPandey** [comment]
image
Isn't.

But I think I found something on GitHub desktop.

**Comment by jigyasa-grover** [comment]
@DeeprajPandey Pls rephrase, I am unable to get your point.

**Comment by DeeprajPandey** [comment]
image

Came across this on the GitHub s/w for Desktop. So I think I am on to something.

Will get to it tonight. Thanks for helping! :D

**Comment by DeeprajPandey** [comment]
gtg

**Comment by jigyasa-grover** [comment]
:+1:

**Comment by DeeprajPandey** [comment]
Hi!
There?

**Comment by DeeprajPandey** [comment]
The conflict is fixed. Is it showing up okay now?

**Comment by jigyasa-grover** [comment]
@DeeprajPandey Nope.

**Review by daminisatya — CHANGES_REQUESTED** [review]
@DeeprajPandey Resolve the merge conflict, you got it again. Hope you understand to how to resolve!

**Comment by DeeprajPandey** [comment]
Let me go through all the steps again. :/

**Comment by DeeprajPandey** [comment]
image

@daminisatya why is my flow showing up like this? :/

**Comment by daminisatya** [comment]
@DeeprajPandey Good you are using some GUI tool for viewing the git flows, but i can help you resolving the conflict from command prompt itself. Please share the screenshot of the command prompt point to this repo first.

**Comment by DeeprajPandey** [comment]
image

I had closed the shell after resolving the previous conflict. Think I had written "git push origin master" instead of "git push origin gh-pages" last time.
Hope it's alright now.

**Comment by DeeprajPandey** [comment]
image

There was a <<<<<HEAD on line 142 and ====== on line 149 before closing inwith a >>>>>(bunch of codes) on line 155.
So, I guess Adarsh Kumar added his bit after me and added that before the equal sign and removed everything and tried commiting. This was the first time (when I tried pushing to master instead of gh-pages)

**Comment by DeeprajPandey** [comment]
@daminisatya are all the conflicts resolved now?

**Comment by daminisatya** [comment]
Ok, You have removed those HEAD and bunch of >>>> tags. that's cool. Check your students.yml file carefully. It shouldn't contain those tags anywhere. Then add you changes to the file. Now follow the steps
```
git add -u
git commit --amend
git push -f origin gh-pages
```

**Comment by daminisatya** [comment]
@DeeprajPandey Hope this helps (it should ;) if you can properly check the students.yml file and remove the conflicts properly (Also remember not to remove any data from the file while removing those HEAD tags)

**Comment by DeeprajPandey** [comment]
image

@daminisatya to go through those steps, I added a blank line so as to have something to commit.
Is it okay now?

**Comment by DeeprajPandey** [comment]
*blank line in the students.yml file

**Comment by DeeprajPandey** [comment]
image

And here's the screenshot from deeprajpandey.github.io as requested by @jig08 early on in the conversation.
Can I submit this task for review now?

**Pull request closed without merging**
