### PR TITLE
Added few logos

### PR DESCRIPTION
**Pull request by sudo-panda**
Resolves https://github.com/fossasia/gci16.fossasia.org/issues/478
[LIve](https://baidya99.github.io/gci16.fossasia.org/)

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Baidya99 LGTM, but let's wait for Travis

**Comment by m1guelpf** [comment]
@Baidya99 
```
Starting ImgChecker, authored by Abishek V Ashok for FOSSASIA with love
The image ./images/mentors/aviaryan.jpg is larger than 240px x 240px [w x h]
ImgChecker: There are images which exceed the expected dimensions as specified above
Please resize them sir... Happy coding
```
```
Executing section Default...
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 545| 545| }
| 546| 546| 
| 547| 547| .logos img {
| 548|    |-	padding:3em .6em;
|    | 548|+    padding:3em .6em;
| 549| 549| 	max-width:100%;
| 550| 550| 	max-height: 100%;
| 551| 551| 	margin:auto;
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 546| 546| 
| 547| 547| .logos img {
| 548| 548| 	padding:3em .6em;
| 549|    |-	max-width:100%;
|    | 549|+    max-width:100%;
| 550| 550| 	max-height: 100%;
| 551| 551| 	margin:auto;
| 552| 552| 	position: relative;
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 547| 547| .logos img {
| 548| 548| 	padding:3em .6em;
| 549| 549| 	max-width:100%;
| 550|    |-	max-height: 100%;
|    | 550|+    max-height: 100%;
| 551| 551| 	margin:auto;
| 552| 552| 	position: relative;
| 553| 553|     top: 50%;
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 548| 548| 	padding:3em .6em;
| 549| 549| 	max-width:100%;
| 550| 550| 	max-height: 100%;
| 551|    |-	margin:auto;
|    | 551|+    margin:auto;
| 552| 552| 	position: relative;
| 553| 553|     top: 50%;
| 554| 554|     transform: translateY(-50%);
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 549| 549| 	max-width:100%;
| 550| 550| 	max-height: 100%;
| 551| 551| 	margin:auto;
| 552|    |-	position: relative;
|    | 552|+    position: relative;
| 553| 553|     top: 50%;
| 554| 554|     transform: translateY(-50%);
| 555| 555| }
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 555| 555| }
| 556| 556| 
| 557| 557| .logos figure {
| 558|    |-	width:250px;
|    | 558|+    width:250px;
| 559| 559| 	height:200px;
| 560| 560| }
| 561| 561| 
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Tabs used instead of spaces.
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
| 556| 556| 
| 557| 557| .logos figure {
| 558| 558| 	width:250px;
| 559|    |-	height:200px;
|    | 559|+    height:200px;
| 560| 560| }
| 561| 561| 
| 562| 562| .yt {
[INFO][18:13:58] Applied 'ShowPatchAction' on 'stylesheets/main.css' from 'SpaceConsistencyBear'.
Executing section html...
Executing section yaml...
Executing section css...
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
[WARNING][18:14:01] Selected default action 'ShowPatchAction' for bear 'PHPCodeSnifferBear' is not applicable. Action not applied.
stylesheets/main.css
| 548| »   padding:3em•.6em;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
stylesheets/main.css
| 549| »   max-width:100%;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
stylesheets/main.css
| 550| »   max-height:•100%;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
stylesheets/main.css
| 551| »   margin:auto;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
stylesheets/main.css
| 552| »   position:•relative;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
stylesheets/main.css
| 558| »   width:250px;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
stylesheets/main.css
| 559| »   height:200px;
|    | [NORMAL] PHPCodeSnifferBear:
|    | Spaces must be used to indent lines; tabs are not allowed
```

**Comment by sudo-panda** [comment]
Why is Travis CI rejecting indentation with tabs?

**Comment by ankitrgadiya** [comment]
@Baidya99 You have to use spaces instead of tab.

**Comment by niccokunzmann** [comment]
I think because tabs and spaces should not be mixed in one file

**Pull request merged**
