### PR TITLE
Show all contributors (Fix #472)

### LINKED ISSUE #472: Not all contributors are showing up
In the contributors' section, it seems like only the people merging pull-requests show up.
capture
I would like that everyone who contributed is shown.

### PR DESCRIPTION
**Pull request by hoangvanthien**
https://hoangvanthien.github.io/
Recursion solved the issue #472 :D Now everyone who has contributed will be shown on our website!

### CODE REVIEW

**Comment by Princu7** [comment]
Great work @hoangvanthien. Now all contributors are visible!!

**Comment by hoangvanthien** [comment]
@Princu7 Thanks for your compliment. Should I merge my own PR now, or wait for other maintainer doing this?

**Comment by Princu7** [comment]
@hoangvanthien First, you need to remove the Travis errors. It seems like there are many trailing whitespaces. Also, you will have to ignore few bears before some lines in order for Travis to become green.

**Comment by hoangvanthien** [comment]
Due to the changes in `index.html` structure, in order to keep Travis green, we must also move `<h2>` tag outside class `row`. This was changed in #510. 

I suggest merging this PR first (after I fix trailing spaces) then opening another PR changing `index.html`. I think this is the only way to pass Travis. What do you think? @Princu7

**Comment by Princu7** [comment]
Danger faling the build @hemantjadon @Abhi2424shek Any guesses?

**Comment by abishekvashok** [comment]
@hoangvanthein you could have added a new commit

**Pull request merged**
