### PR TITLE
Split up responsibility and ability

### PR DESCRIPTION
**Pull request by niccokunzmann**
Problem: Just adding what maintainers can do to their responsibility may
overload them.

Solution: Responsibility and can-do abilities are divided. and ordered
by importance.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@fossasia/gci16-maintainers If you have time, please (review and) merge.

**Comment by oanarosca** [comment]
Looks alright, just fix the Travis build :sweat_smile:

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
Squash all your commits into one and rename it to something meaningful. @niccokunzmann 😉

**Comment by niccokunzmann** [comment]
My first squash^^

**Review by jigyasa-grover — APPROVED** [review]

**Comment by jigyasa-grover** [comment]
@niccokunzmann Great !

**Pull request merged**
