### PR TITLE
Fixes #242

### LINKED ISSUE #242: Issues section does not show issues with the label "feature" and does not have Read More link
The issues section currently does not show the issues with the "feature" label, and does not have a Read More text linking to the issue as instructed by this task:
https://codein.withgoogle.com/tasks/5739892873101312/
I would like to work on this

### PR DESCRIPTION
**Pull request by aryanbhasin**
Changes issues section to show only issues with "feature" label

### CODE REVIEW

**Comment by oanarosca** [comment]
Please provide a link to your changes :smile:

**Comment by aryanbhasin** [comment]
Do you mean this?
https://github.com/aryanbhasin/gci16.fossasia.org/commit/2e1bbc2327ff096aedce328cd9c8bcfa34f871f1

**Comment by oanarosca** [comment]
Whenever you're asked for the link, it is the live gh-pages from your fork where we can see the changes you have made, in this case [this](https://aryanbhasin.github.io/gci16.fossasia.org/). Keep it in mind whenever you create a PR! Also, it seems that the url is not quite right. Take a look at the JSON file and figure out what should be changed. If you need help, I could help you on Slack.

**Comment by jigyasa-grover** [comment]
With reference to [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

**Pull request closed without merging**
